themes/ndt2/assets/css/main.css

Not 100% sure this is the best fix, but currently the about page doesn't scroll vertically at all, and that's definitely not right. This can't be a problem with this theme generally (someone would have noticed before now) so something else weird is going on. Removing this line fixes it, but might break stuff elsewhere?

Stop disabling scrolling on about page

---

themes/ndt2/layouts/_default/single.html

If a lat/lng is in the location front matter, then we add a link to google maps and openstreetmap to the title:

Adds gmaps and osm links to page titles

---

content/daytrip/eu/gb/cole-museum-of-zoology.md
content/daytrip/eu/gb/witches-crag.md
themes/ndt2/layouts/_default/single.html

If sites have `external_url` set, then we add a link to the header of a page:

Add external link icon

---

config.toml
themes/ndt2/layouts/_default/single.html
themes/ndt2/layouts/partials/repository-link.html

Adds "View" and "Edit" links directly to GitHub resources on every page.
Adds a GitHub link in the top menu.
Uses git info to change front matter date on posts (in theory).

Adds a smattering of github integration

---

themes/ndt2/layouts/_default/single.html

Each page has generated OSM and GMaps links.
The OSM default zoom level (12) was too far out to be useful, and didn't match the zoom level on GMaps. So I have zoomed it in a lot more, which seems more useful.

Increase zoom level for OSM

---

themes/ndt2/layouts/_default/single.html

Change url to something that works consistently on desktop and mobile (when gmaps app is installed).

Maps url was brokeon on mobile fixes #32

---

themes/ndt2/layouts/_default/single.html
themes/ndt2/layouts/index.html

Prioritize link to our map on venue pages, and move external links down to the footer.

Shuffle map links around

---

content/daytrip/eu/gb/mathscity.md

**Venue:** MathsCity
**Location:** Upper Floor, Trinity, Shopping Centre, Leeds LS1 5AT
**Submitted by:** Katie Steckles
**Website:** https://mathscity.co.uk/
MathsCity is a hands-on maths activity centre, with puzzles, toys, a giant kaleidoscope and a human-sized bubble maker, as well as codebreaking activities, mathematical demonstrations and extra activities run during the holidays.
**Submission ID:** 7
**File:** `content/daytrip/eu/gb/mathscity.md`

New: MathsCity

---

content/daytrip/eu/gb/baston-lodge.md

**Venue:** Baston Lodge; childhood home of Alan Turing
**Location:** 1 Upper Maze Hill, St Leonards-on-Sea, Hastings, East Sussex
**Website:** https://en.wikipedia.org/wiki/Baston_Lodge
The house in which Alan Turing resided with his brother John as wards, while their parents were stationed abroad in the Indian Civil Service.
**Submission ID:** 9
**File:** `content/daytrip/eu/gb/baston-lodge.md`

New: Baston Lodge; childhood home of Alan Turing

---

content/daytrip/eu/gb/rendlesham-ufo-landing-site.md

**Venue:** Rendlesham UFO Landing Site
**Location:** Rendlesham Forest, Tangham, Woodbridge, IP12 3NF
**Submitted by:** Floppy
**Website:** https://www.forestryengland.uk/rendlesham-forest/ufo-trail-rendlesham-forest
A short woodland walk to a sculpture commemorating the Rendlesham UFO Incident in 1980.
**Submission ID:** 11
**File:** `content/daytrip/eu/gb/rendlesham-ufo-landing-site.md`

New: Rendlesham UFO Landing Site

---

content/daytrip/na/us/the-monterey-bay-aquarium.md

**Venue:** The Monterey Bay Aquarium
**Location:** 886 Cannery Row, Monterey, CA 93940, United States
**Submitted by:** JohnD
**Website:** https://www.montereybayaquarium.org/
A world class aquarium in its own right, Star Trek fans will recognise this as the location of the Cetacean Institute from Star Trek IV: The Voyage Home.
Sadly, the whale exhibit is no longer here after their mysterious release in 1986.
**Submission ID:** 13
**File:** `content/daytrip/na/us/the-monterey-bay-aquarium.md`

New: The Monterey Bay Aquarium

---

content/daytrip/eu/gb/riverside-museum.md

**Venue:** Riverside Museum
**Location:** 100 Pointhouse Rd, Glasgow G3 8RS
**Submitted by:** Alicolliar
**Website:** https://www.glasgowlife.org.uk/museums/venues/riverside-museum
Modern transport museum, mostly focused on Glasgow/Scotland, featuring vehicles from throughout the 20th century.
**Submission ID:** 15
**File:** `content/daytrip/eu/gb/riverside-museum.md`

New: Riverside Museum

---

content/daytrip/eu/gb/crofton-pumping-station.md

**Venue:** Crofton Pumping Station
**Location:** Crofton Beam Engines, Crofton, Marlborough, Wiltshire, SN8 3DW
**Website:** https://www.croftonbeamengines.org/about/
The oldest beam engine still in its original location -- made in 1812. Filling the top pound of the Kennet and Avon Canal, the engine still pumps water to the canal on steaming days.
**Submission ID:** 17
**File:** `content/daytrip/eu/gb/crofton-pumping-station.md`

New: Crofton Pumping Station

---

content/daytrip/eu/gb/leeds-industrial-museum.md

**Venue:** Leeds Industrial Museum
**Location:** Canal Road, Leeds, LS12 1QF
**Submitted by:** Nav
**Website:** https://museumsandgalleries.leeds.gov.uk/pQKYcJ/leeds-industrial-museum/home
Leeds Industrial Museum started life as a woollen mill, and you'll certainly find some impressive machinery related to spinning wool here, but the collections now its a museum go much further than that, covering engineering, railways, a steam engine to power the mill and cinema history (don't believe what anyone else says - it was invented in Leeds!)
**Submission ID:** 18
**File:** `content/daytrip/eu/gb/leeds-industrial-museum.md`

New: Leeds Industrial Museum

---

content/daytrip/eu/gb/woolwich-foot-tunnel.md

**Venue:** Woolwich foot tunnel
**Location:** Glass Yard, Woolwich, London
**Website:** https://www.royalgreenwich.gov.uk/parking-transport-and-streets/travel-foot-bike-or-public-transport/check-status-foot-tunnels-and
Opened in 1912, the Woolwich Foot Tunnel remains the longest pedestrian tunnel under the River Thames at slightly over half a kilometre end to end.  Access is near the Woolwich Ferry piers on the north and south banks of the river.
**Submission ID:** 20
**File:** `content/daytrip/eu/gb/woolwich-foot-tunnel.md`

New: Woolwich foot tunnel

---

content/daytrip/eu/gb/anthorn-radio-station.md

**Venue:** Anthorn Radio Station
**Location:** Bowness Common, Bowness, Anthorn, Cumberland, England, CA7 5AN
**Website:** https://www.npl.co.uk/msf-signal
Anthorn is where the UK's atomic clock radio signal is broadcast from.
**Submission ID:** 28
**File:** `content/daytrip/eu/gb/anthorn-radio-station.md`

New: Anthorn Radio Station

---

content/daytrip/eu/nl/home-computer-museum.md

**Venue:** Home computer museum
**Location:** Noord Koninginnewal 28, Helmond, NL
**Submitted by:** GolezTrol
**Website:** https://www.homecomputermuseum.nl/
Interactive museum of home computers from the 1970's, 80's and 90's. Many exotic models, many in working condition, and a lot that you can actually try out and use to program some lines of BASIC, or play games from Pacman to Unreal Tournament.
**Submission ID:** 24
**File:** `content/daytrip/eu/nl/home-computer-museum.md`

New: Home computer museum

---

content/daytrip/eu/gb/carnglaze-caverns.md

**Venue:** Carnglaze Caverns
**Location:** Carnglaze Caverns, St Neot, Liskeard, Cornwall, PL14 6HQ
**Website:** https://www.carnglaze.com
A pair of artificial caves, made by mining slate. The upper cavern is used for events (concerts, weddings). The lower cavern has a lake (which is actually a flooded third cavern).
**Submission ID:** 37
**File:** `content/daytrip/eu/gb/carnglaze-caverns.md`

New: Carnglaze Caverns

---

content/daytrip/eu/gb/woodhorn-museum.md

**Venue:** Woodhorn Museum
**Location:** Woodhorn Museum, Queen Elizabeth II Country Park, Ashington, Northumberland NE63 9YF
**Submitted by:** Sarah Dal
**Website:** https://museumsnorthumberland.org.uk/woodhorn-museum/
A mining museum at a former colliery, one of the last deep pits to operate in the UK. As well as the industrial history of the region, the site also has an excellent programme of arts and events, hosts the County Archives, and nearby Woodhorn Colliery Railway through the Country Park is currently in restoration (as of May 2025)
**Submission ID:** 41
**File:** `content/daytrip/eu/gb/woodhorn-museum.md`

New: Woodhorn Museum

---

content/daytrip/eu/gb/imber-village.md

**Venue:** Imber Village
**Location:** Imber, Wiltshire, United Kingdom
**Website:** https://www.imbervillage.co.uk
Placed right in the middle of Salisbury Plain, Imber was turned into a training centre for American troops in 1943. All of the inhabitants of the village were ejected with only a few weeks notice, and the village has remained uninhabited ever since. It is still used as a training ground for the British armed forces.
Once or twice a year, the village is opened to the public, and tours are available.
**Submission ID:** 46
**File:** `content/daytrip/eu/gb/imber-village.md`

New: Imber Village

---

content/daytrip/eu/gb/old-sarum.md

**Venue:** Old Sarum
**Location:** Castle Road, Salisbury, Wiltshire, SP1 3SD
**Website:** https://www.english-heritage.org.uk/visit/places/old-sarum/
Old Sarum is the remains of a major town, in use from 400 BCE to 1220 CE. In the 13th century, the town migrated down the hill to the new location of Salisbury, which had a new cathedral, and by 1220, Old Sarum was abandoned. The site has the remains of the Norman castle, the church, and the town walls.
**Submission ID:** 45
**File:** `content/daytrip/eu/gb/old-sarum.md`

New: Old Sarum

---

content/daytrip/eu/gb/bolton-steam-museum.md

**Venue:** Bolton Steam Museum
**Location:** Mornington Road, Off Chorley Old Road, Bolton, BL1 4EU
**Website:** https://www.nmes.org/index.html
A large collection of steam engines -- from giant three-storey machines, down to small barring engines (used to start the big ones). Open Wednesdays and Sundays, running the machines on electricity. Actually steaming three or four times a summer.
**Submission ID:** 47
**File:** `content/daytrip/eu/gb/bolton-steam-museum.md`

New: Bolton Steam Museum

---

content/daytrip/eu/gb/centre-for-computing-history.md

**Venue:** Centre for Computing History
**Location:** Rene Court Coldhams Road Cambridge CB1 3EW
**Submitted by:** Footleg
**Website:** https://www.computinghistory.org.uk
Museum of history of personal computers. An educational charity to tell the story of the Information Age through exploring in a highly interactive way the historical, social and cultural impact of developments in personal computing. It maintains a long-term collection of objects to tell this story and exploits them through learning and events programmes.
**Submission ID:** 51
**File:** `content/daytrip/eu/gb/centre-for-computing-history.md`

New: Centre for Computing History

---

content/daytrip/eu/gb/west-kennet-long-barrow.md

**Venue:** West Kennet Long Barrow
**Location:** Avebury, United Kingdom
**Website:** https://www.english-heritage.org.uk/visit/places/west-kennet-long-barrow/
An early Neolithic chambered long barrow. The barrow is open, and you can walk inside to see the individual chambers.
**Submission ID:** 53
**File:** `content/daytrip/eu/gb/west-kennet-long-barrow.md`

New: West Kennet Long Barrow

---

content/daytrip/eu/gb/solway-aviation-museum-.md

**Venue:** Solway Aviation museum 
**Location:** Solway Aviation Museum, Aviation House, Carlisle Airport, Crosby-on-Eden, Cumbria, CA6 4NW
**Submitted by:** g7kse
**Website:** https://www.solway-aviation-museum.co.uk/
It's got a Vulcan and the last remaining Beverley is in restoration. Not as big as some of the others but the Beverley is a treat.
**Submission ID:** 59
**File:** `content/daytrip/eu/gb/solway-aviation-museum-.md`

New: Solway Aviation museum 

---

content/daytrip/eu/gb/canadian-warplane-heritage-museum.md

**Venue:** Canadian Warplane Heritage Museum
**Location:** 9280 Airport Road, Mount Hope, Ontario
**Website:** https://www.warplane.com/
An aviation museum specializing in Canadian-flown military aircraft. As well as display craft, 10 are in flying condition and can be booked in advance by passengers looking to fly in them for 20 minutes to 1 hour.
**Submission ID:** 62
**File:** `content/daytrip/eu/gb/canadian-warplane-heritage-museum.md`

New: Canadian Warplane Heritage Museum

---

content/daytrip/eu/gb/crossness-pumping-station.md

**Venue:** Crossness Pumping Station
**Location:** The Old Works, Thames Water S.T.W., Bazalgette Way, London SE2 9AQ
**Website:** https://crossness.org.uk
Part of Bazalgette's plan for improving London's sewers after the Great Stink of 1858, the Crossness Pumping Station is a beautiful Victorian building housing a working beam engine and pumps.
**Submission ID:** 70
**File:** `content/daytrip/eu/gb/crossness-pumping-station.md`

New: Crossness Pumping Station

---

content/daytrip/eu/gb/herstmonceux-observatory.md

**Venue:** Herstmonceux Observatory
**Location:** Herstmonceux, Hailsham N27 1RN
**Website:** https://www.the-observatory.org
When London got too bright in the 1950s, the Royal Observatory was moved from Greenwich to Herstmonceux in East Sussex. While no longer used for scientific observation (Eastbourne and Hailsham are now too bright), it still contains working telescopes, and a small hands-on science centre.
There is Herstmonceux Castle nearby on the same site, for those interested in the historical buildings and gardens.
**Submission ID:** 81
**File:** `content/daytrip/eu/gb/herstmonceux-observatory.md`

New: Herstmonceux Observatory

---

content/daytrip/eu/au/wien-river-retention-basins.md

**Venue:** Wien river retention basins 
**Location:** Near Vienna S-Bahn station "Wolf in der Au" 
**Submitted by:** same
**Website:** https://de.wikipedia.org/wiki/R%C3%BCckhaltebecken_Auhof
The Wien is usually a ridiculously tiny river. But due to surrounding geology, heavy rain can sometimes make it grow to 2000 times its size. These massive basins can hold the water for a few hours to protect the city.
Since the basins are only rarely filled, a lot of plant and animal life develops in them, and the huge walls are a beautiful contrast to that. You are not supposed to walk on the walls, but you can. The spot that I put the pin in is nice for picnics. 
**Submission ID:** 80
**File:** `content/daytrip/eu/au/wien-river-retention-basins.md`
Please review this venue submission and edit the …

New: Wien river retention basins 

---

content/daytrip/eu/gb/oxford-museum-of-the-history-of-science.md

**Venue:** Oxford Museum of the History of Science
**Location:** History of Science Museum, Broad Street, Oxford OX1 3AZ 
**Website:** https://hsm.ox.ac.uk
Opposite Blackwells, and tucked in next to the Sheldonian, the Oxford Museum of Science is an eclectic collection of scientific objects, including a blackboard used by Einstein (with his writing still on it), and Lewis Carroll's photography kit.
**Submission ID:** 75
**File:** `content/daytrip/eu/gb/oxford-museum-of-the-history-of-science.md`

New: Oxford Museum of the History of Science

---

content/daytrip/eu/gb/greenham-common-control-tower-and-missile-silos-bunkers.md

**Venue:** Greenham Common control tower and missile silos / bunkers
**Location:** Greenham Control Tower and Cafe, Burys Bank Rd, Newbury, RG19 8BZ
**Submitted by:** Neil
**Website:** https://www.greenhamtower.org.uk
The former control tower (now a cafe and small museum) for the Greenham Common airbase. Across the common (and behind fences) are missile silos / bunkers.
**Submission ID:** 64
**File:** `content/daytrip/eu/gb/greenham-common-control-tower-and-missile-silos-bunkers.md`

New: Greenham Common control tower and missile silos / bunkers

---

content/daytrip/eu/gb/whipple-museum-of-the-history-of-science.md

**Venue:** Whipple Museum of the History of Science
**Location:** Whipple Museum of the History of Science, Free School Lane, Cambridge CB2 3RH
**Website:** https://www.whipplemuseum.cam.ac.uk
A small but well-formed science museum. Has one of Herschel's telescopes, a section on the (mostly female) instrument-makers of the 18th and 19th centuries, a room of globes, and a huge collection of calculators.
**Submission ID:** 65
**File:** `content/daytrip/eu/gb/whipple-museum-of-the-history-of-science.md`

New: Whipple Museum of the History of Science

---

content/daytrip/na/ca/hamilton-museum-of-steam-technology.md

**Venue:** Hamilton Museum of Steam & Technology
**Location:** 900 Woodward Ave, Hamilton, Ontario, Canada
**Website:** https://www.hamilton.ca/things-do/hamilton-civic-museums/hamilton-museum-steam-technology-national-historic-site
The former waterworks for the city of Hamilton, this museum preserves two massive steam engines which were used to pump drinking water during the latter half of the 19th century.
**Submission ID:** 67
**File:** `content/daytrip/na/ca/hamilton-museum-of-steam-technology.md`

New: Hamilton Museum of Steam & Technology

---

content/daytrip/eu/de/heinz-nixdorf-museumsforum.md

**Venue:** Heinz Nixdorf MuseumsForum
**Location:** Fürstenallee 7, 33102 Paderborn, Germany
**Website:** https://hnf.de
The world's largest computer museum. The exhibition ranges from the first human writings and calculations to calculating machines, typewrites, iconic early computers to modern day robots. 
**Submission ID:** 69
**File:** `content/daytrip/eu/de/heinz-nixdorf-museumsforum.md`

New: Heinz Nixdorf MuseumsForum

---

content/daytrip/eu/gb/manchester-science-and-industry-museum.md

**Venue:** Manchester Science and Industry Museum
**Location:** Science and Industry Museum Liverpool Road Manchester M3 4FP
**Website:** https://www.scienceandindustrymuseum.org.uk
Everything technological about Manchester, from cotton and steam to a replica of Baby, the computer built in Manchester in 1948.
**Submission ID:** 60
**File:** `content/daytrip/eu/gb/manchester-science-and-industry-museum.md`

New: Manchester Science and Industry Museum

---

content/daytrip/eu/gb/aardman-animation-studio-tour.md

**Venue:** Aardman Animation studio tour
**Location:** Aardman Animation, 129 Gas Ferry Road, Bristol, BS1 6UN
**Website:** https://www.aardman.com/attractions-live-experiences/art-of-aardman/
Best known for Morph, Wallace and Gromit, and the Chicken Run films, Aardman animation is a long-standing and well respected "claymation" stop frame animation studio.
**Submission ID:** 96
**File:** `content/daytrip/eu/gb/aardman-animation-studio-tour.md`

New: Aardman Animation studio tour

---

content/daytrip/eu/gb/the-national-archives.md

**Venue:** The National Archives
**Location:** The National Archives, Kew, Richmond, TW9 4DU
**Submitted by:** betandr
**Website:** https://www.nationalarchives.gov.uk/
The National Archives in Kew is pretty much the UK's ultimate data backup with over 1,000 years of history stored in one place. From medieval manuscripts to Cold War secrets, it’s like a real-life time machine for information geeks. Think government-grade lore library meets digital archive. Browse declassified spy files, old maps, or even the Domesday Book.
**Submission ID:** 99
**File:** `content/daytrip/eu/gb/the-national-archives.md`

New: The National Archives

---

content/daytrip/eu/gb/the-broad-street-pump.md

**Venue:** The Broad Street Pump
**Location:** 39 Broadwick St, Carnaby, London W1F 9QJ, United Kingdom
**Website:** https://en.wikipedia.org/wiki/1854_Broad_Street_cholera_outbreak
The father of modern epidemiology, doctor John Snow, tracked down the cause of the 1859 cholera epidemic in London to this pump's contaminated water.
**Submission ID:** 115
**File:** `content/daytrip/eu/gb/the-broad-street-pump.md`

New: The Broad Street Pump

---

content/daytrip/eu/gb/legoland-billund.md

**Venue:** Legoland Billund
**Location:** Nordmarksvej 9, 7190 Billund, Denmark
**Website:** https://www.legoland.dk/
What can I say? It's Legoland! A large open air exhibition of Lego models of European cities and famous locations around the world. Plus a Lego themed amusement park.
**Submission ID:** 112
**File:** `content/daytrip/eu/gb/legoland-billund.md`

New: Legoland Billund

---

content/daytrip/eu/gb/depot-5.md

**Venue:** Depot 5
**Location:** Möhlstraße 31, 68165 Mannheim
**Submitted by:** wLana
**Website:** https://depotfuenf.de/
A small, volunteer-run local transport museum in the Rhine-Neckar region.
Volunteers lead tours through the history of the local transport system once a week. Size: three rooms. Opening hours should be checked online in advance, and registration is recommended.
**Submission ID:** 86
**File:** `content/daytrip/eu/gb/depot-5.md`

New: Depot 5 from wLana

---

content/daytrip/eu/fr/grande-arche-de-la-dfense.md

**Venue:** Grande Arche de la Défense
**Location:** La Défense, Paris
**Website:** https://www.grandearche.com/grande-arche-monument-majeur-de-defense-de-paris/
A monumental building, designed to complement the Arc de Triomphe, and to cap the end of the Avenue des Champs-Élysées from the Louvre to La Défense. The building is skewed off the line of the avenue by a few degrees, to match the angle of the Arc de Triomphe.
There is a rooftop terrace and restaurant, from which you can see spectacular views of Paris, and the ruler-straight route back down to the pyramid at the entrance to the Louvre.
**Submission ID:** 93
**File:** `content/daytrip/eu/fr/grande-arche-de-la-dfense.md`

New: Grande Arche de la Défense from Hugo

---

content/daytrip/eu/nl/sonnenborgh-observatory.md

**Venue:** Sonnenborgh Observatory
**Location:** Zonnenburg 2, 3512 NL, Utrecht
**Website:** https://www.sonnenborgh.nl/english
19th century solar observatory, currently a museum with a host of exhibits, multiple working telescopes and as it is built in a 16th-century fortification, also contains exhibits dedicated to archaeological finds and local history
**Submission ID:** 116
**File:** `content/daytrip/eu/nl/sonnenborgh-observatory.md`

New: Sonnenborgh Observatory from TimoMicro

---

content/daytrip/as/jp/scmaglev-and-railway-park.md

**Venue:** SCMAGLEV and railway park
**Location:** 3 Chome-2-2 Kinjofuto, Minato Ward, Nagoya, Aichi 455-0848
**Website:** https://museum.jr-central.co.jp/en/
Everything you might want to know about shinkansen (bullet trains) and the new maglev train. They have everything from the test model of the maglev to early rolling stock built in the UK. There is also a chance to try a driving simulator, however places are allocated through a lottery system using your entrance ticket. 
Access is via the Aonami Line from Nagoya JR station. 
**Submission ID:** 119
**File:** `content/daytrip/as/jp/scmaglev-and-railway-park.md`

New: SCMAGLEV and railway park from Shiawase

---

content/daytrip/eu/nl/natuurhistorisch-museum-rotterdam.md

**Venue:** Natuurhistorisch Museum Rotterdam
**Location:** Westzeedijk 345, 3015 AA, Rotterdam
**Website:** https://www.hetnatuurhistorisch.nl/en/exhibitions/permanent/dead-animal-tales/
Museum of Natural History and notably the location of the annual Dead Duck Day on June 5th. Dead Duck Day is a commemoration for the mallard famous for earning Kees Moeliker the IgNobel Prize in Biology in 2003 for his paper "The first case of homosexual necrophilia in the mallard Anas platyrhynchos (Aves: Anatidae)". The museum has a quirky collection.
**Submission ID:** 122
**File:** `content/daytrip/eu/nl/natuurhistorisch-museum-rotterdam.md`

New: Natuurhistorisch Museum Rotterdam from TimoMicro

---

content/daytrip/eu/de/wolfsburg-planetarium.md

**Venue:** Wolfsburg Planetarium
**Location:** Uhlandweg 2, 38440 Wolfsburg, Germany
**Website:** https://planetarium-wolfsburg.de/
Planetarium with regular astronomical shows as well as special music programs and movies for younger visitors.
**Submission ID:** 124
**File:** `content/daytrip/eu/de/wolfsburg-planetarium.md`

New: Wolfsburg Planetarium from MarcN

---

content/daytrip/oc/nz/hobbiton-movie-set-lord-of-the-rings-the-hobbit.md

**Venue:** Hobbiton Movie Set - Lord of the Rings - The Hobbit
**Location:** 501 Buckland Road, Matamata, New Zealand
**Website:** https://www.hobbitontours.com/
Guided tours of (recreations of) famous sets of Lord of the Rings and the Hobbit film trilogies. Visit the Shire, marvel at Hobbit holes, and have a drink at the Green Dragon Inn.
**Submission ID:** 125
**File:** `content/daytrip/oc/nz/hobbiton-movie-set-lord-of-the-rings-the-hobbit.md`

New: Hobbiton Movie Set - Lord of the Rings - The Hobbit from TimoMicro

---

content/daytrip/eu/gb/museum-of-water-and-steam.md

**Venue:** Museum of Water and Steam
**Location:** Green Dragon Lane, TW8 0EN
**Submitted by:** Bruno Girin
**Website:** https://waterandsteam.org.uk/
Former water pumping station. They now host humongous steam engines and a miniature steam railway. Great day out for kids of all ages.
**Submission ID:** 126
**File:** `content/daytrip/eu/gb/museum-of-water-and-steam.md`

New: Museum of Water and Steam from Bruno Girin

---

content/daytrip/as/jp/nagoya-city-science-museum.md

**Venue:** Nagoya City Science Museum
**Location:** 17-1, Sakae 2-chome, Naka-ku, Nagoya, 460-0008 Japan
**Website:** https://www.ncsm.city.nagoya.jp/en/
A science museum and planetarium. The exhibits are very hands on and aimed at schoolchildren. Unfortunately, unlike a lot of Japanese museums there are very few english explanations or captions. I found the old Zeiss planetarium projector quite interesting as well as an artificial vortex spanning a number of floors. 
Outside there is a Japanese space rocket, which you can examine even without entering the museum.
Not an exhibit but the hydraulic pistons for earthquake damping are interesting too
**Submission ID:** 128
**File:** `content/daytrip/as/jp/nagoya-city-science-museum.md`
Please review this venue …

New: Nagoya City Science Museum from Shiawase

---

content/daytrip/eu/de/seehundstation-friedrichskoog.md

**Venue:** Seehundstation Friedrichskoog
**Location:** An der Seeschleuse 4, 25718 Friedrichskoog, Germany
**Website:** https://www.seehundstation-friedrichskoog.de/
Seal Centre which allows visitors to observe the seals on land and through the large viewing windows underwater.
**Submission ID:** 129
**File:** `content/daytrip/eu/de/seehundstation-friedrichskoog.md`

New: Seehundstation Friedrichskoog from MarcN

---

content/daytrip/eu/de/klimahaus-bremerhaven.md

**Venue:** Klimahaus Bremerhaven
**Location:** Am Längengrad 8, 27568 Bremerhaven, Germany
**Website:** https://www.klimahaus-bremerhaven.de/
A journey through all climate zones of Earth along the eighth degree of longitude. 
**Submission ID:** 131
**File:** `content/daytrip/eu/de/klimahaus-bremerhaven.md`

New: Klimahaus Bremerhaven from MarcN

---

content/daytrip/as/jp/meiji-mura.md

**Venue:** Meiji Mura
**Location:** 〒484-0000 Aichi-ken, Inuyama-shi, Uchiyama 1
**Website:** https://www.meijimura.com/
An open air architectural park North East of Nagoya comprised of buildings relocated from all over Japan. The Meiji period is roughly comparable to Victorian and was the era when Japan opened to the West. 
Notable buildings are Lafcadio Hearne's house and Natsume Soseki's house. There is also an early wooden Japanese prison. Most famous is the Lobby and Entrance of Frank Lloyd Wright's Tokyo Imperial Hotel. 
The park can be access by bus from Inuyama, itself a short train ride from Nagoya. 
**Submission ID:** 134
**File:** `content/daytrip/as/jp/meiji-mura.md`

New: Meiji Mura from Shiawase

---

content/daytrip/eu/de/deutsches-erdlmuseum-wietze.md

**Venue:** Deutsches Erdölmuseum Wietze
**Location:** Schwarzer Weg 7-9, 29323 Wietze, Germany
**Website:** https://www.erdoelmuseum.de/
Exhibition on oil production in general and on production at the museum site, where oil has been extracted since the 17th century. 
**Submission ID:** 137
**File:** `content/daytrip/eu/de/deutsches-erdlmuseum-wietze.md`

New: Deutsches Erdölmuseum Wietze from MarcN

---

content/daytrip/eu/gb/cragend-farm.md

**Venue:** Cragend Farm
**Location:** Cragend Farm Rothbury Morpeth Northumberland NE65 7XN
**Submitted by:** Chris
**Website:** https://cragendfarm.co.uk/tours/
Celtic Camp and Ducal Border Reiver settlement, remodelled by Victorian Lord Armstrong of Cragside as his show case for hydraulic machinery. 
**Submission ID:** 138
**File:** `content/daytrip/eu/gb/cragend-farm.md`

New: Cragend Farm from Chris

---

content/daytrip/as/jp/mikasa-memorial-ship.md

**Venue:** Mikasa Memorial Ship
**Location:** 82-19 Inaokacho, Yokosuka, Kanagawa 238-0003, Japan
**Website:** https://www.kinenkan-mikasa.or.jp/index.html
The restored pre dreadnaught ship used as Admiral Togo's flagship at the battle of Tsushima when Japan defeated the Russian fleet in 1905. 
Sadly encased in concrete and stripped of many fittings at the insistence of the occupying powers post ww2, you'd wonder how much of Ship of Theseus is going on. Nevertheless it is an important historical ship and now unique. 
Situated in Yokosuka. Where the US Navy has a huge base and you can also see JSDF vessels in the bay. 
**Submission ID:** 140
**File:** `content/daytrip/as/jp/mikasa-memorial-ship.md`
Please review this venue submission and edit the content as …

New: Mikasa Memorial Ship from Shiawase

---

content/daytrip/eu/gb/hp-lovecrafts-grave.md

**Venue:** H.P. Lovecraft's Grave
**Location:** Hemlock Avenue, Swan Point Cemetary, Providence, Rhode Island, United States
**Website:** https://www.findagrave.com/memorial/1188/hp-lovecraft
The final resting place of weird fiction writer H.P. Lovecraft. Find the large obelisk devoted to the Philips family and right next to it is the small marker for his grave, inscribed "I AM PROVIDENCE".
**Submission ID:** 142
**File:** `content/daytrip/eu/gb/hp-lovecrafts-grave.md`

New: H.P. Lovecraft's Grave from Paul Drye

---

content/daytrip/na/ca/the-beguiling.md

**Venue:** The Beguiling
**Location:** 319 College St, Toronto, Ontario, Canada
**Website:** https://beguilingbooks.com/about-us
If you're into alternative comics, quite possibly the best comic store in Canada if not the world. Next door is Little Island Comics, an associated store devoted to young readers.
**Submission ID:** 143
**File:** `content/daytrip/na/ca/the-beguiling.md`

New: The Beguiling from Paul Drye

---

content/daytrip/eu/nl/torture-museum.md

**Venue:** Torture Museum
**Location:** Singel 449, 1012 WP Amsterdam, Netherlands
**Website:** https://torturemuseum.org/
Exhibition on over 40 instruments of punishment from different parts of Europe, from the inquisition chair to the guillotine.
**Submission ID:** 145
**File:** `content/daytrip/eu/nl/torture-museum.md`

New: Torture Museum from MarcN

---

content/daytrip/eu/de/audubon-aquarium-of-the-americas.md

**Venue:** Audubon Aquarium of the Americas
**Location:** 1 Canal St New Orleans, LA 70130, Germany
**Website:** https://audubonnatureinstitute.org/aquarium
Exhibition on the aquatic life of the Americas with more than 10000 animals.
**Submission ID:** 146
**File:** `content/daytrip/eu/de/audubon-aquarium-of-the-americas.md`

New: Audubon Aquarium of the Americas from MarcN

---

content/daytrip/eu/gb/forge-mill-needle-museum.md

**Venue:** Forge Mill Needle Museum
**Location:** Forge Mill Needle Museum & Bordesley Abbey Visitor Centre, Needle Mill Lane, Riverside, Redditch, B98 8HY
**Submitted by:** Matthew Somerville
**Website:** https://www.forgemill.org.uk/
Redditch once produced 90% of the world’s needles. This museum contains both the world's largest and smallest needles, was very interesting when we went there last weekend, and is also next to the ruins of Bordesley Abbey.
**Submission ID:** 149
**File:** `content/daytrip/eu/gb/forge-mill-needle-museum.md`

New: Forge Mill Needle Museum from Matthew Somerville

---

content/daytrip/eu/gb/wizards-of-the-toast.md

**Venue:** Wizards of the Toast
**Location:** R. Conselheiro Lopo Vaz Lote C Loja D, 1800-142 Lisboa, Portugal
**Website:** https://www.instagram.com/wizardsofthetoastpt/
Cafe/Bar focusing on board games and table top gaming.
**Submission ID:** 157
**File:** `content/daytrip/eu/gb/wizards-of-the-toast.md`

New: Wizards of the Toast from TimoMicro

---

content/daytrip/eu/gb/huntarian-museum.md

**Venue:** Huntarian Museum
**Location:** University Ave, Glasgow G12 8QQ, United Kingdom
**Website:** https://www.gla.ac.uk/hunterian/
"The oldest public museum in Scotland, with collections spanning arts, sciences and humanities, The Hunterian is at the forefront of university museums around the world."
**Submission ID:** 159
**File:** `content/daytrip/eu/gb/huntarian-museum.md`

New: Huntarian Museum from TimoMicro

---

content/daytrip/eu/gb/wigtown.md

**Venue:** Wigtown
**Location:** Wigtown, Dumfries and Galloway, Scotland
**Website:** https://www.wigtown-booktown.co.uk
Lots of books, mostly second-hand.
Not as big as Hay on Wye, but still very much worth a visit.
"At the Sign of the Green Dragon" is a specialist SF&F shop with a large stock on the outskirts of the town.
**Submission ID:** 163
**File:** `content/daytrip/eu/gb/wigtown.md`

New: Wigtown from Hugo

---

content/daytrip/eu/dk/museum-for-papirkunst.md

**Venue:** Museum for Papirkunst
**Location:** Ilsigvej 2, DK-9492 Blokhus, Danmark
**Website:** https://www.museumforpapirkunst.dk
A museum of paper art
**Submission ID:** 165
**File:** `content/daytrip/eu/dk/museum-for-papirkunst.md`

New: Museum for Papirkunst from Hugo

---

content/daytrip/eu/gb/high-down-rocket-test-site.md

**Venue:** High Down Rocket Test Site
**Location:** Needles PO39 0JH, United Kingdom
**Website:** https://en.wikipedia.org/wiki/High_Down_Rocket_Test_Site
Most come here for the Needles, two rock spires off the coast, but next door to the viewpoint are what’s left of High Down Rocket Test Site.
In the 50s and 60s the UK tried to be a third contestant in the Space Race and here they tested their rockets. The Black Arrow that sent Britain's launched the UK’s one-and-only indigenous orbital mission was among them.
Only walkways and the foundations of the test stands remain, but a two-room museum is at the Needles New Battery a short walk away.
**Submission ID:** 166
**File:** `content/daytrip/eu/gb/high-down-rocket-test-site.md`
Please review this venue submission …

New: High Down Rocket Test Site from Paul Drye

---

content/daytrip/eu/gb/the-bells-of-st-clements.md

**Venue:** The Bells of St Clement’s
**Location:** St Clement’s Church
**Submitted by:** Catriona
**Website:** https://bells-of-stclements.scy.org.uk/index.php
As far as I know this is the only place in the country offering daily public demonstrations of the art of bellringing. The half-hour experience includes an introduction to the history of ringing, how the patterns of ‘changes’ are constructed, and the opportunity to have a go at chiming a bell, full-circle ringing, and change ringing on handbells.
Open from 2-3pm every weekday afternoon, £8 each. Can be booked in advance or walk-in on the day. 
**Submission ID:** 167
**File:** `content/daytrip/eu/gb/the-bells-of-st-clements.md`

New: The Bells of St Clement’s from Catriona

---

content/daytrip/na/us/big-mine-run-geyser.md

**Venue:** Big Mine Run Geyser
**Location:** 2-528 Big Mine Run Road, Ashland, Pennsylvania, United States
**Website:** https://uncoveringpa.com/big-mine-run-geyser-in-pennsylvania
The only geyser in the state of Pennsylvania, one with an unusual back story.
The abandoned town of Centralia is nearby and the heat of the long-term underground coal seam fire there affected the flooded tunnels of the former Bast Colliery. That drives the colliery's water up, where it gushes as much as 15 feet in the air during periods of heavy rain.
The geyser is on private land but can be seen about 5-10 meters away from the side of Big Run Mine Road.
**Submission ID:** 172
**File:** `content/daytrip/na/us/big-mine-run-geyser.md`
Please review this venue submission and edit the …

New: Big Mine Run Geyser from Paul Drye

---

content/daytrip/eu/gb/jodrell-bank-observatory.md

**Venue:** Jodrell Bank Observatory
**Location:**   Bomish Lane, Nr. Macclesfield, Cheshire SK11 9DW
**Submitted by:** losttourist
**Website:** https://www.jodrellbank.net/
This is the site of one of the world's first radio telescopes -- and it's still working and still in regular use by cosmologists and astronomers. It has a fantastic visitor centre and is a great day out for geeky kids and geeky adults alike!
**Submission ID:** 175
**File:** `content/daytrip/eu/gb/jodrell-bank-observatory.md`

New: Jodrell Bank Observatory from losttourist

---

content/daytrip/eu/gb/warrington-transporter-bridge.md

**Venue:** Warrington Transporter Bridge
**Location:** Access from Quay Fold, next to Pink Eye Building
**Submitted by:** losttourist
**Website:** http://www.warringtontransporterbridge.co.uk/
There were never many transporter bridges built in the UK and there are very few of them left. Warrington's is unique in that it was built to carry rail rather than road traffic.
The only easy access route is via a permissive path through the old Unilever factory ... although that's a little bit of a nerdy adventure in its own right!
**Submission ID:** 176
**File:** `content/daytrip/eu/gb/warrington-transporter-bridge.md`

New: Warrington Transporter Bridge from losttourist

---

content/daytrip/eu/gb/bekonscot-model-village.md

**Venue:** Bekonscot Model Village
**Location:**  Warwick Road, Beaconsfield, HP9 2PL
**Submitted by:** h2g2bob
**Website:** https://www.bekonscot.co.uk/
Everything you expect from a charming model village: houses, churches, cricket pitch, harbour, colliery, etc.
Plus model trains. Lots of model trains, running all the time by nerds who'll happily chat about block signalling.
**Submission ID:** 179
**File:** `content/daytrip/eu/gb/bekonscot-model-village.md`

New: Bekonscot Model Village from h2g2bob

---

content/daytrip/na/us/high-scores-arcade.md

**Venue:** High Scores Arcade
**Location:** 1414 Park Street, Alameda, CA 94507
**Submitted by:** Don Marti
**Website:** https://www.highscoresarcade.com/
Play vintage 1980s arcade games on the original hardware. Try Centipede, Joust, Defender, and more. (Hourly or daily admission, all games on free play)
**Submission ID:** 180
**File:** `content/daytrip/na/us/high-scores-arcade.md`

New: High Scores Arcade from Don Marti

---

content/daytrip/na/us/uss-hornet-museum.md

**Venue:** USS Hornet Museum
**Location:** 707 W Hornet Ave, Alameda, California, USA
**Submitted by:** OldSchoolDad510
**Website:** https://uss-hornet.org/
Explore the ship that recovered the Apollo 11 astronauts. In service from World War II until the 1970s, the USS Hornet is now a museum featuring historic aircraft, other US Navy history displays, a ham radio shack, and more. Sign up for a guided tour even if you have toured that part of the ship already -- each volunteer brings their own unique knowledge and/or sea stories to the tour.
**Submission ID:** 181
**File:** `content/daytrip/na/us/uss-hornet-museum.md`

New: USS Hornet Museum from OldSchoolDad510

---

content/daytrip/eu/gb/epsom-downs-view-point-carpark.md

**Venue:** Epsom Downs View Point Carpark
**Location:** Grandstand Rd, Epsom KT18 5LQ
**Submitted by:** Anon
**Website:** https://www.visitsurrey.com/listing/epsom-downs/124516101/
Just a car park, but it has a fantastic view of Central London where you can see the London Eye and the Shard. You can also see Wembley stadium and to some extent Heathrow Airport.
**Submission ID:** 182
**File:** `content/daytrip/eu/gb/epsom-downs-view-point-carpark.md`

New: Epsom Downs View Point Carpark from Anon

---

content/daytrip/eu/gb/portable-airship-hangar.md

**Venue:** Portable Airship Hangar
**Location:** Portable Airship Hangar, Fowler Avenue, Farnborough Business Park, Farnborough, Rushmoor, Hampshire, England, GU14 7JF, United Kingdom
**Website:** https://historicengland.org.uk/listing/the-list/list-entry/1393074
Portable airship shed built in 1912; the frame was reassembled in this location in 2004. It's now in a commercial office park on the edge of Farnborough Airport.
The construction forms a quiet space, often popular with photographers, especially at sunset.
**Submission ID:** 184
**File:** `content/daytrip/eu/gb/portable-airship-hangar.md`

New: Portable Airship Hangar from popey

---

content/daytrip/eu/gb/retrodome.md

**Venue:** Retrodome
**Location:** Retrodome, Thomas Street, Worsbrough Common, Kingstone, Barnsley, South Yorkshire, England, S70 1LH, United Kingdom
**Submitted by:** Retrodome
**Website:** https://retrodome.co.uk
The Retrodome is heaven for fans of old arcade games. Tickets are valid for the day, you can come and go as you please and play over 200 classic arcade games, all free-to-play. There's also mini golf, a bar, and they serve food as well.
**Submission ID:** 185
**File:** `content/daytrip/eu/gb/retrodome.md`

New: Retrodome from Retrodome

---

content/daytrip/eu/gb/alice-holt-forest-caf.md

**Venue:** Alice Holt Forest Café
**Location:** Alice Holt Forest Café, Hardings Road, Bucks Horn Oak, Binsted, East Hampshire, Hampshire, England, GU10 4LF, United Kingdom
**Website:** https://www.forestryengland.uk/alice-holt-forest
Alice Holt is a large wood with a children's play area, a cafe, bike hire, "Go Ape" for children and adults to get up in the trees. There's space for picnicking or just taking a nice long stroll.
**Submission ID:** 186
**File:** `content/daytrip/eu/gb/alice-holt-forest-caf.md`

New: Alice Holt Forest Café from popey

---

edit.sh

This is a shell script that should help with doing manual editing of entries. Set up a list of files to edit, run the script (see the usage comment at the top of the script).
It will:
* Open the web pages for
* The NDT entry
* The location in OSM
* A web search for the title of the entry
* Show the entry markdown
* Give you a menu where you can fill in various details or edit manually or move to the next or previous entries
I've used this script for the last tranche of edits, and it makes things a lot easier.

Interactive editing script

---

content/daytrip/eu/gb/ulster-transport-museum.md

**Venue:** Ulster Transport Museum
**Location:** Ulster Transport Museum, 153, Bangor Road, Holywood, County Down, Northern Ireland, BT18 0EU, United Kingdom
**Submitted by:** Nerd
**Website:** http://www.nmni.com/uftm
Lots of interesting rail, bus and aviation exhibits. The perfect place for transport nerds.
**Submission ID:** 188
**File:** `content/daytrip/eu/gb/ulster-transport-museum.md`

New: Ulster Transport Museum from Nerd

---

content/daytrip/eu/gb/sutton-hoo.md

**Venue:** Sutton Hoo
**Location:** Tranmer House, Sutton Hoo, Woodbridge, Suffolk, IP12 3DJ. 
**Submitted by:** Starmouse
**Website:** https://www.nationaltrust.org.uk/visit/suffolk/sutton-hoo
Awe-inspiring Anglo-Saxon royal burial site
**Submission ID:** 190
**File:** `content/daytrip/eu/gb/sutton-hoo.md`

New: Sutton Hoo from Starmouse

---

content/daytrip/eu/gb/saint-michaels-abbey.md

**Venue:** Saint Michael's Abbey
**Location:** Saint Michael's Abbey, 280 Farnborough Rd Farnborough, Hampshire GU14 7NQ
**Website:** https://farnboroughabbey.org/
A working Benedictine abbey. Place of burial of Empress Eugenie, wife of Napoléon III.
Every Saturday at 3 pm, there is a guided tour of the Abbey Church and the Imperial Crypt. There is no need to book in advance. The Abbey gates open automatically at 2.45 pm. The tour lasts about an hour and ends in the monastery shop.
**Submission ID:** 206
**File:** `content/daytrip/eu/gb/saint-michaels-abbey.md`

New: Saint Michael's Abbey from popey

---

content/daytrip/eu/gb/potteries-museum-and-art-gallery.md

**Venue:** Potteries Museum and Art Gallery
**Location:** Potteries Museum and Art Gallery, Bethesda Street, Joiner's Square, Hanley, Stoke-on-Trent, England, ST1 3DW, United Kingdom
**Submitted by:** Robin
**Website:** https://www.stokemuseums.org.uk/pmag/
Interesting museum and art gallery. Museum has a large ceramics collection, a Spitfire, and the Staffordshire Hoard.
**Submission ID:** 210
**File:** `content/daytrip/eu/gb/potteries-museum-and-art-gallery.md`

New: Potteries Museum and Art Gallery from Robin

---

content/daytrip/eu/gb/the-tank-museum.md

**Venue:** The Tank Museum
**Location:** The Tank Museum, King George V Road, Wool, Wareham, Dorset, England, BH20 6JG, United Kingdom
**Submitted by:** Robin
**Website:** https://tankmuseum.org/
Large tank museum, fascinating for anyone interested in modern military history.
**Submission ID:** 211
**File:** `content/daytrip/eu/gb/the-tank-museum.md`

New: The Tank Museum from Robin

---

content/daytrip/eu/de/st-pauli-elbtunnel.md

**Venue:** St. Pauli-Elbtunnel
**Location:** St. Pauli-Elbtunnel, Bei den St. Pauli-Landungsbrücken, St. Pauli, Hamburg-Mitte, Hamburg, 20359, Deutschland
**Website:** https://en.m.wikipedia.org/wiki/Elbe_Tunnel_(1911)
The old Elbe Tunnel is an impressive structure which can be used free of charge to cross below the river Elbe. Riding the huge elevators which were used for vehicles until a few years ago is a small adventure. Alternatively it is possible to use the stairs. 
**Submission ID:** 212
**File:** `content/daytrip/eu/de/st-pauli-elbtunnel.md`

New: St. Pauli-Elbtunnel from MarcN

---

content/daytrip/eu/gb/heath-robinson-museum.md

**Venue:** Heath Robinson Museum
**Location:** Heath Robinson Museum, Pinner, Memorial Park, West End Lane, Pinner HA5 1AE.
**Website:** https://www.heathrobinsonmuseum.org
A surprisingly well-built and not at all held together with string museum, celebrating the life and art of William Heath Robinson.
**Submission ID:** 216
**File:** `content/daytrip/eu/gb/heath-robinson-museum.md`

New: Heath Robinson Museum from Hugo

---

content/daytrip/eu/de/deutsches-panzermuseum.md

**Venue:** Deutsches Panzermuseum
**Location:** Deutsches Panzermuseum, 33, Hans-Krüger-Straße, Munster, Heidekreis, Niedersachsen, 29633, Deutschland
**Website:** https://daspanzermuseum.de/
The museum shows the history of German tanks from its beginnings in the 19th century until today. It claims neither to glorify violence nor to be an anti-war exhibition, but to take a differentiated view of the subject area. 
**Submission ID:** 217
**File:** `content/daytrip/eu/de/deutsches-panzermuseum.md`

New: Deutsches Panzermuseum from MarcN

---

content/daytrip/eu/de/forschungsflughafen-braunschweig-wolfsburg.md

**Venue:** Forschungsflughafen Braunschweig-Wolfsburg
**Location:** Forschungsflughafen Braunschweig-Wolfsburg, Pumpenweg, Waggum, Wabe-Schunter-Beberbach, Braunschweig, Niedersachsen, 38110, Deutschland
**Website:** https://www.fhbwe.de/
Research flights and, on a small scale, commercial aviation can be observed on the visitor terrace. At the weekend, it is mainly amateur pilots who take off and land here. There is also some catering available for non-aviation enthusiasts.
**Submission ID:** 221
**File:** `content/daytrip/eu/de/forschungsflughafen-braunschweig-wolfsburg.md`

New: Forschungsflughafen Braunschweig-Wolfsburg from MarcN

---

content/daytrip/eu/de/jagdmuseum-wulff.md

**Venue:** Jagdmuseum Wulff
**Location:** Jagdmuseum Wulff, Hässelmühler Straße, Oerrel, Dedelstorf, Samtgemeinde Hankensbüttel, Gifhorn, Niedersachsen, 29386, Deutschland
**Website:** https://www.jagdmuseum-wulff.de/
A museum about hunting in Europe is quite a niche. 
**Submission ID:** 222
**File:** `content/daytrip/eu/de/jagdmuseum-wulff.md`

New: Jagdmuseum Wulff from MarcN

---

content/daytrip/eu/de/zeithaus.md

**Venue:** ZeitHaus
**Location:** ZeitHaus, Stadtbrücke, Stadtmitte, Wolfsburg, Niedersachsen, 38440, Deutschland
**Website:** https://www.autostadt.de/erkunden/zeithaus
A car exhibition about the history of automobility with a focus on Volkswagen and other Group brands. However, classic cars from other manufacturers are also on display. The museum is only accessible to visitors to the Autostadt. 
**Submission ID:** 223
**File:** `content/daytrip/eu/de/zeithaus.md`

New: ZeitHaus from MarcN

---

content/daytrip/eu/de/lokpark-braunschweig.md

**Venue:** Lokpark Braunschweig
**Location:** Lokpark Braunschweig, 3, Schwartzkopffstraße, Bebelhof, Mitte, Braunschweig, Niedersachsen, 38126, Deutschland
**Website:** https://www.lokpark.de/
An old railway site that is used as an event venue, but also by an association that restores old steam locomotives. The site is only open to the public on certain days. Information can be found on the website. 
**Submission ID:** 226
**File:** `content/daytrip/eu/de/lokpark-braunschweig.md`

New: Lokpark Braunschweig from MarcN

---

content/daytrip/eu/de/braunschweiger-dom.md

**Venue:** Braunschweiger Dom
**Location:** Braunschweiger Dom, Burgplatz, Mitte, Braunschweig, Niedersachsen, 38100, Deutschland
**Website:** https://www.braunschweigerdom.de/krypta
Under the altar area of the cathedral is the crypt, which contains the remains of several dukes as well as Henry the Lion and his wife Mathilde. The crypt is accessible for a small fee. 
**Submission ID:** 230
**File:** `content/daytrip/eu/de/braunschweiger-dom.md`

New: Braunschweiger Dom from MarcN

---

content/daytrip/eu/gb/farnborough-air-science-trust-museum.md

**Venue:** Farnborough Air Science Trust Museum
**Location:** Farnborough Air Science Trust Museum, Farnborough Road, Farnborough, Rushmoor, Hampshire, England, GU14 6TL, United Kingdom
**Website:** https://airsciences.org.uk/about-fast/
FAST (Farnborough Air Sciences Trust) is a volunteer-run charity museum that's been showcasing Farnborough's aviation heritage since 1993. 
Housed in a 1908 building that once served as headquarters for the Royal Engineers Balloon School, overlooking Farnborough Airfield where you can watch modern aircraft while exploring historic gems like Sir Frank Whittle's early jet engines and Concorde research models. 
They have half a million artefacts in their collection and displays rotating, it's a proper treasure trove of British …

New: Farnborough Air Science Trust Museum from popey

---

content/daytrip/eu/gb/novelty-automation.md

**Venue:** Novelty Automation
**Location:** Novelty Automation, 1a, Princeton Street, Gray's Inn, Holborn, London Borough of Camden, London, Greater London, England, WC1R 4AX, United Kingdom
**Submitted by:** andypiper
**Website:** https://www.novelty-automation.com/
A very fun collection of satirical automata and handcrafted arcade gaming installations.
**Submission ID:** 237
**File:** `content/daytrip/eu/gb/novelty-automation.md`

New: Novelty Automation from andypiper

---

content/daytrip/na/us/united-states-mint.md

**Venue:** United States Mint
**Location:** United States Mint, 151, North Independence Mall East, Center City, Chinatown, Philadelphia, Philadelphia County, Pennsylvania, 19106, United States
**Website:** https://www.usmint.gov/
Most U.S. coins are made here.  There is a small museum about money and how it is made, but the good part is watching the coin-pressing floor from the overhead gallery.
**Submission ID:** 239
**File:** `content/daytrip/na/us/united-states-mint.md`

New: United States Mint from Mark Dominus

---

content/daytrip/na/us/mtter-museum.md

**Venue:** Mütter Museum
**Location:** Mütter Museum, 19, South 22nd Street, Center City, Rittenhouse Square, Philadelphia, Philadelphia County, Pennsylvania, 19103, United States
**Website:** https://muttermuseum.org/
19th-cenruty style museum of medical oddities and curiosities.  Includes: a life cast of Chang and Eng Bunker, the original Siamese Twins; a collection of objects retrieved from patients' throats by Chevalier Jackson, called "The father of endoscopy"; the cancerous tumor secretly removed from Grover Cleveland's mouth; the "Soap Lady", a corpse that was transmuted into soap; collections of antique surgical equipment, and many other equally bizarre items; collections 
**Submission ID:** 240
**File:** `content/daytrip/na/us/mtter-museum.md` …

New: Mütter Museum from Mark Dominus

---

content/daytrip/eu/ie/mummies-in-the-crypt.md

It's hard to tell -- the official website of the church mentions the crypts, but says "go look on Google Maps for information", and is about as helpful as a leaflet from the Scarfolk Tourist Office. There's a couple of newspaper articles, including one from March 2025, which say that it's closed until further notice.

eu/hr and eu/ie: Adding a URL and a note that the place may be closed

---

content/daytrip/na/ca/eramosa-karst.md

**Venue:** Eramosa Karst
**Location:** Orange Trail, Trinity, Hamilton, Golden Horseshoe, Ontario, L8J 0K5, Canada
**Website:** https://conservationhamilton.ca/conservation-areas/eramosa-karst/
Walking trails through a large area of karst terrain -- which is to say, limestone that's been eroded away by into a large number of sinkholes, shallow amphitheatres, small caves, and underground streams. There are several trails here which collectively cover most of the interesting ones.
**Submission ID:** 242
**File:** `content/daytrip/na/ca/eramosa-karst.md`

New: Eramosa Karst from Paul Drye

---

content/daytrip/na/us/american-helicopter-museum-education-center.md

**Venue:** American Helicopter Museum & Education Center
**Location:** American Helicopter Museum & Education Center, 1220, American Boulevard, West Goshen Township, Chester County, Pennsylvania, 19380, United States
**Website:** https://www.helicoptermuseum.org/
More helicopters than you can shake a stick at.
Some memorable ones include human-powered designs and helicopters made from commercially-sold built-it-yourself helicopter kits for hobbyists.
**Submission ID:** 250
**File:** `content/daytrip/na/us/american-helicopter-museum-education-center.md`

New: American Helicopter Museum & Education Center from Mark Dominus

---

content/daytrip/as/kr/paju-book-city-letterpress-museum.md

**Venue:** Paju Book City Letterpress Museum
**Location:** 145 Hoedong-gil, Munbal-dong, Paju-si, Gyeonggi-do, South Korea
**Website:** http://www.letterpressmuseum.co.kr/
Museum of Korean printing technology and history.  Includes:
* Collection of Korean, Japanese, and Chinese-language typewriters
* History of Korean samizdat practices during the Japanese occupation
* Large collection of Korean and Chinese moveable type
* History of Korean printing
* Demonstrations
* Gift shop
**Submission ID:** 248
**File:** `content/daytrip/as/kr/paju-book-city-letterpress-museum.md`

New: Paju Book City Letterpress Museum from Mark Dominus

---

content/daytrip/na/ca/zed80.md

**Venue:** Zed*80
**Location:** 185 Danforth Avenue, Toronto, Ontario, Canada
**Website:** https://www.zedeighty.com/
Pay once to enter and then free-play on 40 retro arcade and pinball machines. Food menu and drinks are available on site too. Adults-only after 8:00 PM but otherwise open to all.
**Submission ID:** 258
**File:** `content/daytrip/na/ca/zed80.md`

New: Zed*80 from Paul Drye

---

content/daytrip/na/us/cross-sound-ferry.md

**Venue:** Cross Sound Ferry
**Location:** Cross Sound Ferry, Ferry Street, Downtown New London Historic District, Downtown New London, New London, Southeastern Connecticut Planning Region, Connecticut, 06320, United States
**Website:** https://www.dhs.gov/science-and-technology/plum-island-animal-disease-center
This ferry from New London, CT or Orient Point on Long Island is just a ferry.
The nerdy draw is that it passes by Plum Island, home of the Plum Island Animal Disease Center, also called "Anthrax Island".  It was featured in the movie "Silence of the Lambs" as the place where they might keep Hannibal Lecter if they were to ever let him out of his prison cell.
The island itself is off-limits to the public.
**Submission ID:** 252
**File:** …

New: Cross Sound Ferry from Mark Dominus

---

content/daytrip/na/us/emperor-nortons-grave.md

**Venue:** Emperor Norton's grave
**Location:** Woodlawn Memorial Park, 1000, El Camino Real, Colma, San Mateo County, California, 94014, United States
**Website:** https://en.wikipedia.org/wiki/Emperor_Norton
Final resting place of Norton I, Emperor of the United States.
**Submission ID:** 253
**File:** `content/daytrip/na/us/emperor-nortons-grave.md`

New: Emperor Norton's grave from Mark Dominus

---

content/daytrip/na/us/four-seasons-total-landscaping.md

**Venue:** Four Seasons Total Landscaping
**Location:** Four Seasons Total Landscaping, 7347, State Road, Northeast Philadelphia, Philadelphia, Philadelphia County, Pennsylvania, 19136, United States
**Website:** https://www.npr.org/2020/11/11/933635970/from-obscure-to-sold-out-the-story-of-four-seasons-total-landscaping-in-just-4-d
During the 2020 Presidential election, the Trump campaign told Rudy Giuliani to book a press conference at the Four Seasons Hotel.  A mistake was made and the conference was instead held in the back parking lot of this Northeast Philadelphia garden and landscaping service.
When you're done, it's a five-minute walk to Sweet Lucy's Smokehouse for lunch.
**Submission ID:** 262
**File:** …

New: Four Seasons Total Landscaping from Mark Dominus

---

content/daytrip/na/us/national-canal-museum-dl-headquarters.md

**Venue:** National Canal Museum / D&L Headquarters
**Location:** National Canal Museum / D&L Headquarters, D&L Trail - National Canal Museum Spur, Easton, Northampton County, Pennsylvania, 18042, United States
**Website:** https://canals.org/
Hands-on collection of canal-related artifacts. Mule-drawn canal boat rides.
**Submission ID:** 264
**File:** `content/daytrip/na/us/national-canal-museum-dl-headquarters.md`

New: National Canal Museum / D&L Headquarters from Mark Dominus

---

content/daytrip/eu/gb/maharajahs-well.md

**Venue:** Maharajah's Well
**Location:** Main Street, Stoke Row, RG9 5QJ
**Website:** http://www.maharajahswell.org.uk
In 1850, the Maharajah of Benares had a conversation with a son of the squire of Ipsden in Oxfordshire. He learned about the village of Stoke Row, which had no nearby source of fresh water.
Some years later, the Maharajah was reminded of this story, and sent a foreign aid package in the form of funds to dig a well in Stoke Row. The well was completed in 1864, and now stands in its own grounds with a magnificent canopy over it.
**Submission ID:** 265
**File:** `content/daytrip/eu/gb/maharajahs-well.md`

New: Maharajah's Well from Hugo

---

content/daytrip/eu/mt/saint-johns-co-cathedral.md

**Venue:** Saint John's Co-Cathedral
**Location:** Saint John's Co-Cathedral, Triq San Ġwann, Strada Rjali, Valletta, South Eastern Region, VLT 1113, Malta
**Submitted by:** Stuart Langridge
**Website:** https://www.stjohnscocathedral.com/
Imposing but not too remarkable on the outside. Catastrophically over-ornamented on the inside. St John’s really needs to be seen or you won’t believe it. Really. It’s extremely ornate, filled with gilt ornamentation, statues, a floor made entirely of marble tombstones throughout, and two original Caravaggio paintings. See if you can find the stone of Mattia Preti, who did a good chunk of the interior artwork (tip: in the entrance to the sacristy.) 
Advice: get there early. You can buy tickets online to skip the queue, but if you arrive at 9.30 then the …

New: Saint John's Co-Cathedral from Stuart Langridge

---

themes/ndt2/assets/css/main.css

The header broke on mobile, when shrunk width-wise, it crunches up the header.
This PR attempts to fix that.

fix header compression on mobile

---

content/daytrip/eu/gb/grave-of-jethro-tull.md

**Venue:** Grave of Jethro Tull
**Location:** St Bartholomew's Church, Lower Basildon, Berkshire
**Website:** https://en.wikipedia.org/wiki/Jethro_Tull_(agriculturist)
Not the prog rock band, but the original Jethro Tull -- the 18th century agronomist who invented the seed drill, and ushered in the British (aka the second) agricultural revolution.
**Submission ID:** 270
**File:** `content/daytrip/eu/gb/grave-of-jethro-tull.md`

New: Grave of Jethro Tull from Hugo

---

content/daytrip/eu/gb/rcp-garden-of-medicinal-plants.md

**Venue:** RCP Garden of Medicinal Plants
**Location:** 11 St Andrews Place, London, United Kingdom
**Website:** https://www.rcp.ac.uk/about-us/rcp-garden-of-medicinal-plants/
Part of the larger Royal College of Physicians Museum, the garden is devoted to plants that were believed to have medicinal value in ancient and medieval times. Open every weekday from 9:00 to 5:00 if you want to explore on your own, while a physician-guided tour is available on the first Wednesday of each month at 2 PM.
**Submission ID:** 273
**File:** `content/daytrip/eu/gb/rcp-garden-of-medicinal-plants.md`

New: RCP Garden of Medicinal Plants from Paul Drye

---

content/daytrip/eu/gb/the-coffin-works.md

**Venue:** The Coffin Works
**Location:** 13-15 Fleet St, Birmingham B3 1JP
**Submitted by:** MegaSlippers
**Website:** https://www.coffinworks.org/
The preserved Newman Brothers coffin furniture factory.  
The building is full of the equipment and stock that was used to stamp handles and sew burialware. The guides are very knowledgable and passionate the once booming industry.
**Submission ID:** 274
**File:** `content/daytrip/eu/gb/the-coffin-works.md`

New: The Coffin Works from MegaSlippers

---

content/daytrip/as/kr/national-hangeul-museum.md

**Venue:** National Hangeul Museum
**Location:** National Hangeul Museum, 139, Seobinggo-ro, Yongsan-dong 6-ga, Seobinggo-dong, Yongsan-gu, Seoul, 04428, South Korea
**Website:** https://www.hangeul.go.kr/en
One of Korea's proudest cultural achievements is Hangeul, the 24-letter alphabet used to write the Korean language.  Prior to its invention in 1443, there simply was no Korean written language.
This museum is devoted to Hangeul and its invention.  Most notable in the collection is a rare surviving copy of Hunmin Jeongeum, the original user's guide for Hangeul.
**Submission ID:** 276
**File:** `content/daytrip/as/kr/national-hangeul-museum.md`

New: National Hangeul Museum from Mark Dominus

---

content/daytrip/eu/nl/ir-df-woudagemaal.md

**Venue:** Ir. D.F. Woudagemaal
**Location:** Gemaalweg 1, 8531 PS Lemmer, The Netherlands
**Website:** https://www.woudagemaal.com/
Water pumping station powered by steam. The Woudagemaal was built in 1920 and was used to pump water from the canals in Friesland in order to regulate the water level. Although nowadays it has been replaced by a newer pumping station it is still used a few times a year when the water is very high.
**Submission ID:** 277
**File:** `content/daytrip/eu/nl/ir-df-woudagemaal.md`

New: Ir. D.F. Woudagemaal from Frederik Dekker

---

content/daytrip/eu/nl/bunker-museum-terschelling.md

**Venue:** Bunker Museum Terschelling
**Location:** Tigerpad 5, 8881 GB, West-Terschelling, The Netherlands
**Website:** https://www.bunkermuseumterschelling.nl/
In the second world war a German radar station and control center was located on the (occupied) island of Terschelling. In the control center the radar signals were processed and fighters were directed to intercept bombers bound for Germany. 
In the bunker museum the control station has been rebuild and radar techniques from that time are explained.
**Submission ID:** 278
**File:** `content/daytrip/eu/nl/bunker-museum-terschelling.md`

New: Bunker Museum Terschelling from Frederik Dekker

---

content/daytrip/eu/nl/dwigeloo-radiotelescope.md

**Venue:** Dwigeloo Radiotelescope
**Location:** Oude Hoogeveensedijk 4, 7991 PD, Dwingeloo, The Netherlands
**Website:** https://www.camras.nl/en/
Radio telescope from 1956. At that time the largest radio telescope in the world. It was used until 1998 and has now been taken over by volunteers who still use and maintain it.
**Submission ID:** 279
**File:** `content/daytrip/eu/nl/dwigeloo-radiotelescope.md`

New: Dwigeloo Radiotelescope from Frederik Dekker

---

content/daytrip/eu/de/teufelsberg-.md

**Venue:** Teufelsberg 
**Location:** 10, Teufelsseechaussee, Grunewald, Charlottenburg-Wilmersdorf, Berlijn, 14193, Duitsland
**Submitted by:** Ayor
**Website:** https://www.teufelsberg-berlin.de/
Old cold war allied listening station. The station was used to monitor Soviet and Eastern Bloc communications and gather important information on the activities of Warsaw Pact countries. After being decommissioned in 1992, the site lays empty for years. It is now a gallery for street art, and the buildings have been granted monumental status.
**Submission ID:** 280
**File:** `content/daytrip/eu/de/teufelsberg-.md`

New: Teufelsberg  from Ayor

---

content/daytrip/eu/nl/drukkerijmuseum.md

**Venue:** Drukkerijmuseum
**Location:** Drukkerijmuseum, Leeuwerik, Baai, Etten-Leur, Noord-Brabant, Nederland, 4872 PH, Nederland
**Submitted by:** Redmer
**Website:** https://www.nederlandsdrukkerijmuseum.eu
A lovely printing press museum, with enthusiastic volunteers and changing expositions. All printing presses are functional and might be demonstrated by a volunteer.
**Submission ID:** 281
**File:** `content/daytrip/eu/nl/drukkerijmuseum.md`

New: Drukkerijmuseum from Redmer

---

content/daytrip/eu/be/plantin-moretus-museum.md

**Venue:** Plantin-Moretus Museum
**Location:** Vrijdagmarkt 22, Antwerpen, 2000, België
**Submitted by:** Redmer
**Website:** https://museumplantinmoretus.be
The printer Plantin moved to this building in 1576, and the museum houses the world’s oldest printing presses and a complete Renaissance printing workshop. Great place if you're interested in the technological foundations of modern knowledge dissemination.
**Submission ID:** 282
**File:** `content/daytrip/eu/be/plantin-moretus-museum.md`

New: Plantin-Moretus Museum from Redmer

---

content/daytrip/eu/de/ziegeleipark-mildenberg.md

**Venue:** Ziegeleipark Mildenberg
**Location:** Ziegeleipark, Ziegelei, Mildenberg, Zehdenick, Oberhavel, Brandenburg, 16792, Deutschland
**Website:** https://www.ziegeleipark.de/
The Mildenberg Brick Work Park has exhibitions on the local brick industry. It has working brickworks, ring kilns, narrow-gauge field railways and a stationary steam engine. 
**Submission ID:** 286
**File:** `content/daytrip/eu/de/ziegeleipark-mildenberg.md`

New: Ziegeleipark Mildenberg from MarcN

---

content/daytrip/eu/gb/ordnance-survey-grid-reference-ov0000.md

**Venue:** Ordnance Survey Grid Reference OV0000
**Location:** Beast Cliff, North Yorkshire, UK
**Website:** https://en.wikipedia.org/wiki/Beast_Cliff
The only part of the 100km square Ordnance Survey "OV" square with land in it (at low tide). Access to the beach is hazardous, so it's very difficult to reach the beach (and the OS grid location) itself.
**Submission ID:** 289
**File:** `content/daytrip/eu/gb/ordnance-survey-grid-reference-ov0000.md`

New: Ordnance Survey Grid Reference OV0000 from Hugo

---

content/daytrip/eu/nl/historische-scheepswerf-wolthuis.md

**Venue:** Historische Scheepswerf Wolthuis
**Location:** 308, Noorderstraat, Kleinemeer, Sappemeer, Midden-Groningen, Groningen, Nederland, 9611 AT, Nederland
**Submitted by:** MartenK
**Website:** https://www.historischescheepswerf.nl/
This historic shipyard is now a very complete museum showing and demonstrating various (historic) techniques used to build ships, including wood working, smithing, hole punching, riveting, lifting, etc. The yard is still in function for restoration of (historic) ships, making it an active site.
**Submission ID:** 291
**File:** `content/daytrip/eu/nl/historische-scheepswerf-wolthuis.md`

New: Historische Scheepswerf Wolthuis from MartenK

---

content/daytrip/eu/nl/museum-schokland.md

**Venue:** Museum Schokland
**Location:** Middelbuurt 3, 8319 AB Schokland, The Netherlands
**Website:** https://www.museumschokland.nl/en/
Visitor Centre of Schokland, an island in the Zuiderzee that was inhabited until 1859. Because of coastal erosion the island became smaller and smaller and eventually had to be evacuated. When the Noordoostpolder was reclaimed in the 1940's the (former) island became surrounded by land.
**Submission ID:** 293
**File:** `content/daytrip/eu/nl/museum-schokland.md`

New: Museum Schokland from Frederik Dekker

---

content/daytrip/eu/nl/historische-scheepswerf-wolthuis-historic-shipyard-wolthuis.md

**Venue:** Historische Scheepswerf Wolthuis (Historic Shipyard Wolthuis)
**Location:** Noorderstraat 308, 9611 AT Sappemeer, The Netherlands
**Website:** https://www.historischescheepswerf.nl/
Historic Shipyard in the province of Groningen. Groningen has a longstanding history of shipbuilding. Most shipyards were located along canals, making it necessarry to launch ships sideways. In 1983 the canal along which shipyard Wolthuis (one of the oldest in Groningen) was located was closed and the shipyard was turned into a museum.
**Submission ID:** 294
**File:** `content/daytrip/eu/nl/historische-scheepswerf-wolthuis-historic-shipyard-wolthuis.md`

New: Historische Scheepswerf Wolthuis (Historic Shipyard Wolthuis) from Frederik Dekker

---

content/daytrip/eu/nl/melkwegpad-milky-way-path.md

**Venue:** Melkwegpad (Milky Way Path)
**Location:** Oosthalen 8, 9414 TG, Hooghalen, The Netherlands
**Website:** https://www.opensciencedrenthe.nl/hubs/het-melkwegpad
Walking route where the distance between planets are scaled. For each planet there is a puzzle (not sure if the puzzle is available in English). The route ends at the radio telescopes of Astron.
**Submission ID:** 295
**File:** `content/daytrip/eu/nl/melkwegpad-milky-way-path.md`

New: Melkwegpad (Milky Way Path) from Frederik Dekker

---

content/daytrip/eu/nl/waterloopbos.md

**Venue:** Waterloopbos
**Location:** Voorsterweg 34, 8316 PT, Marknesse, The Netherlands
**Website:** https://www.natuurmonumenten.nl/natuurgebieden/waterloopbos
The national monument Waterloopbos is an area where the Dutch have learned to work with water, waves and current. It used to be a laboratory where research was conducted in order to construct civil works to protect The Netherlands (and other countries) from the sea and to engage in land reclamation. When computers took over this research the area was reclaimed by nature, but the ruins of the test sites can still be found.
**Submission ID:** 298
**File:** `content/daytrip/eu/nl/waterloopbos.md`

New: Waterloopbos from Frederik Dekker

---

content/daytrip/eu/nl/omroepzendermuseum.md

**Venue:** Omroepzendermuseum
**Location:** Biezendijk 3, 3412 KB, Lopikerkapel, The Netherlands 
**Website:** https://www.omroepzendermuseum.nl/index.php/over-het-museum
Museum about the electro-technical techniques of broadcasting radio and TV signals
**Submission ID:** 300
**File:** `content/daytrip/eu/nl/omroepzendermuseum.md`

New: Omroepzendermuseum from Frederik Dekker

---

content/daytrip/eu/nl/world-soil-museum.md

**Venue:** World Soil Museum
**Location:** Droevendaalsesteeg 3, 6708 PB, Wageningen, The Netherlands
**Website:** https://wsm.isric.org/
Museum about soil types and profiles around the world.
**Submission ID:** 305
**File:** `content/daytrip/eu/nl/world-soil-museum.md`

New: World Soil Museum from Frederik Dekker

---

content/daytrip/eu/nl/museum-speelklok.md

**Venue:** Museum Speelklok
**Location:** Steenweg 6, 3511 JP, Utrecht, The Netherlands
**Website:** https://www.museumspeelklok.nl/en/
Museum about music making machines, from music boxes to organs.
**Submission ID:** 306
**File:** `content/daytrip/eu/nl/museum-speelklok.md`

New: Museum Speelklok from Frederik Dekker

---

content/daytrip/eu/gb/roche-abbey.md

**Venue:** Roche Abbey
**Location:** Maltby, Rotherham, South Yorkshire, S66 8NW
**Submitted by:** Robin
**Website:** https://www.english-heritage.org.uk/visit/places/roche-abbey/
Mostly-ruined Cistercian abbey
**Submission ID:** 308
**File:** `content/daytrip/eu/gb/roche-abbey.md`

New: Roche Abbey from Robin

---

content/daytrip/eu/nl/cruquius-museum.md

**Venue:** Cruquius Museum
**Location:** Cruquiusdijk 27, 2142 ER Cruquius, The Netherlands
**Website:** https://cruquius-museum.nl/en
19th century steam powered water pumping station. The pumping stationed was used to pump dry the Haarlemmermeer polder. 
**Submission ID:** 312
**File:** `content/daytrip/eu/nl/cruquius-museum.md`

New: Cruquius Museum from Frederik Dekker

---

content/daytrip/eu/nl/nemo-science-museum.md

**Venue:** NEMO science museum
**Location:** Oosterdok 2, 1011 VX, Amsterdam, The Netherlands
**Website:** https://www.nemosciencemuseum.nl/en/
Hands on museum on science and technology. Also a nice rooftop terrace.
**Submission ID:** 313
**File:** `content/daytrip/eu/nl/nemo-science-museum.md`

New: NEMO science museum from Frederik Dekker

---

content/daytrip/eu/nl/esher-in-het-paleis.md

**Venue:** Esher in het paleis
**Location:** Lange Voorhout 74, 2514 EH, Den Haag, The Netherlands
**Website:** https://escherinhetpaleis.nl/en
Museum exhibiting the works of M.C. Escher, a Dutch artist famous for his use of repeating patterns and optical and spatial illusions.
**Submission ID:** 315
**File:** `content/daytrip/eu/nl/esher-in-het-paleis.md`

New: Esher in het paleis from Frederik Dekker

---

content/daytrip/eu/nl/national-maritime-museum.md

**Venue:** National Maritime Museum
**Location:** Kattenburgerplein 1, 1018 KK, Amsterdam, The Netherlands
**Website:** https://www.hetscheepvaartmuseum.com/
Located in a former naval storehouse, the national maritime museum shows 500 years of Dutch maritime history. This includes a life sized replica of a Dutch East Indiaman. 
**Submission ID:** 321
**File:** `content/daytrip/eu/nl/national-maritime-museum.md`

New: National Maritime Museum from Frederik Dekker

---

content/daytrip/eu/nl/fortress-bourtange.md

**Venue:** Fortress Bourtange
**Location:** Willem Lodewijkstraat 33, 9545 PA, Bourtange, The Netherlands
**Website:** https://www.bourtange.nl/
Museum village in the fortress of Bourtange. The fortress was built during the Dutch revolt against Spain. When the fortress lost its military purpose it became neglected, but has since then been completely restored to how it looked in 1742.
**Submission ID:** 325
**File:** `content/daytrip/eu/nl/fortress-bourtange.md`

New: Fortress Bourtange from Frederik Dekker

---

content/daytrip/eu/nl/veluwsche-stoomtrein-maatschappij.md

**Venue:** Veluwsche Stoomtrein Maatschappij
**Location:** Dorpstraat 140, 7361 AZ, Beekbergen, The Netherlands
**Website:** https://stoomtrein.org/en/
Steam train with historic station emplacement at Beekbergen. The steam train runs between Apeldoorn and Dieren. 
The station has workshops, a turn table, offices and water and coal facilities.
**Submission ID:** 328
**File:** `content/daytrip/eu/nl/veluwsche-stoomtrein-maatschappij.md`

New: Veluwsche Stoomtrein Maatschappij from Frederik Dekker

---

content/daytrip/eu/gb/national-emergency-services-museum.md

**Venue:** National Emergency Services Museum
**Location:** National Emergency Services Museum The Old Police/Fire Station West Bar Sheffield S3 8PT
**Submitted by:** GlennF
**Website:** https://www.visitnesm.org.uk
The National Emergency Services Museum in Sheffield is this really cool spot housed in a gorgeous old Victorian building that used to be an actual police, fire, and ambulance station. They've got about 30 vintage emergency vehicles spread across three floors, plus loads of old medical kit, firefighting gear, and even a massive 47-foot lifeboat - and the best part is it's all hands-on and interactive rather than just stuff behind glass. It's open Wednesday through Sunday and honestly way more interesting than you'd expect, whether you're into the history side of things or just …

New: National Emergency Services Museum from GlennF

---

content/daytrip/eu/nl/space-expo-noordwijk.md

**Venue:** Space Expo Noordwijk
**Location:** Keplerlaan 3, 2201 AZ, Noordwijk, The Netherlands
**Website:** https://www.space-expo.nl/en
Space museum. The museum is located next to the European Space Agency's ESTEC space and technology centre. 
Mainly about space exploration from a European perspective.
**Submission ID:** 332
**File:** `content/daytrip/eu/nl/space-expo-noordwijk.md`

New: Space Expo Noordwijk from Frederik Dekker

---

content/daytrip/eu/se/brsarp.md

**Venue:** Brösarp
**Location:** Brösarp, 3, Brösarps stationsväg, Brösarp, Simrishamns kommun, Skåne län, 273 55, Sverige
**Submitted by:** magnus
**Website:** https://angtaget.se/
Since 1971, steam trains have been chugging along Sweden's most beautiful railway between Brösarp and S:t Olof on Österlen. We take you around Brösarp's hills, along the clear blue waters of Hanöbukten, the ripe fields, and through the deep beech forests. The Museum Association Skånska Järnvägar preserves and develops the museum railway on Österlen and showcases a time period when people traveled on wooden benches, the station master was the king of the community, and the locomotive driver was every child's idol.
The Museum Association Skånska Järnvägar was formed in the autumn of 1969, moved to Brösarp in the …

New: Brösarp from magnus

---

content/daytrip/na/us/misselhorn-art-gallery.md

**Venue:** Misselhorn Art Gallery
**Location:** West 2nd Street, Sparta, Illinois, United States
**Website:** https://www.greatriverroad.com/sparta
A small art gallery named for a local artist, it is of Nerdy Interest for its display of items related to the 1967 Academy Award-winning movie In the Heat of the Night. It was filmed here in Sparta, Illinois and the museum's building (a former railway stop) was even one of the filming sites.
**Submission ID:** 337
**File:** `content/daytrip/na/us/misselhorn-art-gallery.md`

New: Misselhorn Art Gallery from Paul Drye

---

content/daytrip/eu/nl/zuiderzee-museum.md

**Venue:** Zuiderzee Museum
**Location:** Noorderwierdijk, 1601 LV, Enkhuizen, The Netherlands
**Website:** https://www.zuiderzeemuseum.nl/
Museum about life at the shores of the Zuiderzee. In 1932 the great IJsselmeer barrier dam was constructed and the Zuiderzee was seperated form the Waddenzee. While the Zuiderzee was in open connection with the (salt) sea before, now it became a fresh water lake. The museum is about life before 1932 in the historic village, but also focusses on the current situation and future.
Can be combined with the steam tram from Hoorn to Medemblik by taking the historic ferry "Friesland", which sails between Medemblik and Enkhuizen.
**Submission ID:** 338
**File:** `content/daytrip/eu/nl/zuiderzee-museum.md`
Please review this …

New: Zuiderzee Museum from Frederik Dekker

---

content/daytrip/eu/gb/chance-counters.md

**Venue:** Chance & Counters
**Location:** Chance & Counters, Gibb Street, Rea Valley, Digbeth, Highgate, Birmingham, West Midlands, England, B9 4BG, United Kingdom
**Submitted by:** Stuart Langridge
**Website:** https://www.chanceandcounters.com/birmingham/
Board game cafe with a whole wall's selection of games to play.
**Submission ID:** 339
**File:** `content/daytrip/eu/gb/chance-counters.md`

New: Chance & Counters from Stuart Langridge

---

content/daytrip/eu/nl/aflsuitdijk-wadden-center.md

**Venue:** Aflsuitdijk Wadden Center
**Location:** Afsluitdijk 1c, 8752 TP, Kornwerderzand, The Netherlands
**Website:** https://afsluitdijkwaddencenter.nl/
Visitor center for the Wadden sea, the IJsselmeer, fish migration river (passing under the dike) and the Afsluitdijk. Explains both the civil enginieering side of the Afsluitdijk and the ecological aspects of the Wadden sea and IJsselmeer.
**Submission ID:** 343
**File:** `content/daytrip/eu/nl/aflsuitdijk-wadden-center.md`

New: Aflsuitdijk Wadden Center from Frederik Dekker

---

content/daytrip/eu/nl/kazemattenmuseum-kornwerderzand.md

**Venue:** Kazemattenmuseum Kornwerderzand
**Location:** Afsluitdijk 1c, 8752 TP, Kornwerderzand, The Netherlands
**Website:** https://www.kazemattenmuseum.nl/en/
When the Afsluitdijk was built in 1932 it was not only a dam, but also an extra route invaders could take to reach Holland and Amsterdam. So they also built fortifications. In may 1940 when the Germans invaded these fortifications held out until the Netherlands were forced to surrender.
**Submission ID:** 344
**File:** `content/daytrip/eu/nl/kazemattenmuseum-kornwerderzand.md`

New: Kazemattenmuseum Kornwerderzand from Frederik Dekker

---

content/daytrip/eu/nl/delta-park-neeltje-jans.md

**Venue:** Delta Park Neeltje Jans
**Location:** Faelweg 5, 4354 RB, Vrouwenpolder, The Netherlands
**Website:** https://www.neeltjejans.nl/en/
Located on an artificial island that served as a construction base during the construction of the Oosterschelde barrier, Neeltje Jans is now a visitor center and theme park centered on the Delta Works that protect the Netherlands form the sea. The construction of the Delta works started after the flooding of Zeeland in 1953. Besides exhibitions the park also has a playground, storm simulator and marine wildlife.
**Submission ID:** 345
**File:** `content/daytrip/eu/nl/delta-park-neeltje-jans.md`

New: Delta Park Neeltje Jans from Frederik Dekker

---

content/daytrip/na/us/wagner-free-institute-of-science.md

**Venue:** Wagner Free Institute of Science
**Location:** Wagner Free Institute of Science, 1700, West Montgomery Avenue, Sharswood, North Philadelphia, Philadelphia, Philadelphia County, Pennsylvania, 19121, United States
**Submitted by:** Mike Cramer
**Website:** https://www.wagnerfreeinstitute.org/
A well preserved 19th century science museum filled with fossils, taxidermy, gems and bones. Free to visit. Occasional lectures and events. 
**Submission ID:** 346
**File:** `content/daytrip/na/us/wagner-free-institute-of-science.md`

New: Wagner Free Institute of Science from Mike Cramer

---

content/daytrip/eu/gb/the-castletown-d-day-centre.md

**Venue:** The Castletown D-day centre
**Location:** Admiralty Buildings, Castletown, Portland, Dorset, UK, DT5 1BD
**Submitted by:** SimonB
**Website:** https://ddaycentre.com/
An impressive collection of world war II artifacts, vehicles, weapons, etc that can be handled, and explored. Interaction is encouraged. Suitable for wet or dry weather and all ages.
**Submission ID:** 348
**File:** `content/daytrip/eu/gb/the-castletown-d-day-centre.md`

New: The Castletown D-day centre from SimonB

---

content/daytrip/eu/gb/de-havilland-monument.md

**Venue:** De Havilland Monument
**Location:** A34, Whitchurch RG28 7QA
**Submitted by:** Simon Reap
**Website:** https://www.hants.gov.uk/thingstodo/countryside/finder/dehavilland
This is a small stone monument to the place that Geoffrey De Havilland (of Gipsy Moth and Mosquito fame) took his first flight in 1910. It's on the edge of a field, about 50 metres from the A34. To get there, drive North on the A34 (North of the A303 and of Whitchurch), stay on it past the turning for Litchfield and Dunley, then stop in the first parking layby about 1.5 miles further on. There's a small sign at the southern end of the layby to the monument. I drove past this hundreds of times before I decided to stop - well worth the few minutes it took!
**Submission ID:** 349
**File:** …

New: De Havilland Monument from Simon Reap

---

content/daytrip/as/jp/nintendo-museum.md

**Venue:** Nintendo Museum
**Location:** Nintendo Museum, ujiogura station line, Oguracho, Uji, Kyoto Prefecture, 611-0042, Japan
**Website:** https://museum.nintendo.com/en/index.html
Step into a real-life Mario universe at the Nintendo Museum in Japan. This interactive playground lets you spend digital coins to play classic games on giant controllers and retro consoles like the Nintendo 64. 
Explore Nintendo's history through behind-the-scenes exhibits, get creative in a Japanese playing card workshop, and snap photos with iconic in-game items like the green Warp Pipe and Super Mushroom. 
**Submission ID:** 352
**File:** `content/daytrip/as/jp/nintendo-museum.md`

New: Nintendo Museum from popey

---

content/daytrip/eu/fr/chteau-de-vaux-le-vicomte.md

**Venue:** Château de Vaux-le-Vicomte
**Location:** 77950 MAINCY
**Submitted by:** NAB
**Website:** https://vaux-le-vicomte.com/
A 17th century masterpiece, Vaux-le-Vicomte was the backdrop to many major historical events and witnessed the tragic eviction of its creator, Nicolas Fouquet, following an extraordinary trial.
**Submission ID:** 354
**File:** `content/daytrip/eu/fr/chteau-de-vaux-le-vicomte.md`

New: Château de Vaux-le-Vicomte from NAB

---

content/daytrip/eu/nl/museumspoorlijn-star.md

**Venue:** Museumspoorlijn STAR
**Location:** Stationsstraat 3, 9503 AD, Stadskanaal, The Netherlands 
**Website:** https://www.stadskanaalrail.nl/
Historic railway between Stadskanaal and Ter Apel-Rijksgrens. Nowadays running between Veendam and Nieuw-Buinen. Has both steam and diesel locomotives. In Stadskanaal there is also a museum and workshops that can be visited. In Veendam you can change over to the regular Dutch railway system.
Note: there are plans to extend the line to Emmen and make it part of the regular Dutch railway network again, the so called Nedersaksenlijn.
**Submission ID:** 366
**File:** `content/daytrip/eu/nl/museumspoorlijn-star.md`

New: Museumspoorlijn STAR from Frederik Dekker

---

content/daytrip/eu/ie/the-computer-and-communications-museum-of-ireland.md

**Venue:** The Computer and Communications Museum of Ireland
**Location:** 1st Floor, Insight Centre for Data Analytics, The DERI Building, IDA Business Park, Lower Dangan, Galway.
**Submitted by:** PilloxMatters
**Website:** https://ccmireland.com/about/
Founded in 2010, the Computer and Communications Museum of Ireland tells the fascinating story of key moments in the history of computing and communications. We explore technology by preserving the past, demonstrating the present and educating for the future.
Visits by appointment except during public events, no admission fee, donations accepted.
**Submission ID:** 371
**File:** `content/daytrip/eu/ie/the-computer-and-communications-museum-of-ireland.md`

New: The Computer and Communications Museum of Ireland from PilloxMatters

---

content/daytrip/eu/de/funkerberg-museum.md

**Venue:** Funkerberg Museum
**Location:** funkerberg 20, 15711 Königs Wusterhausen, Germany
**Website:** https://museum.funkerberg.de/
The first German public radio broadcast was transmitted from this site. Exhibitions include radio transmitters and a collection of vacuum tubes (valves). The museum is currently (2025) closed for renovation but parts of it may be open for special events (see website).
**Submission ID:** 384
**File:** `content/daytrip/eu/de/funkerberg-museum.md`

New: Funkerberg Museum from debb1046

---

content/daytrip/eu/de/ofen-und-keramikmuseen-velten.md

**Venue:** Ofen- und Keramikmuseen Velten
**Location:** Wilhelmstraße 32, 16727 Velten, Germany
**Website:** https://okmhb.de/
Museum situated in a historic stove factory. Exhibition of stoves, tiles, ceramics. Another part of the museum is dedicated to the life and works of designer and artist Hedwig Bollhagen.
**Submission ID:** 387
**File:** `content/daytrip/eu/de/ofen-und-keramikmuseen-velten.md`

New: Ofen- und Keramikmuseen Velten from debb1046

---

content/daytrip/eu/es/aeroteca-flight-sim-store.md

**Venue:** Aeroteca Flight Sim Store
**Location:** Travessera de Gràcia, 209, Gràcia, 08012 Barcelona
**Submitted by:** Sam D
**Website:** https://www.aeroteca.com/en/
Flight sim store that has been open for over 40 years. They have a basic simulator, motion simulator and a Boeing 737 Simulator all available to use in store if you book a slot in advance. They also sell various sim gear, model planes, books and other airplane paraphernalia.
**Submission ID:** 373
**File:** `content/daytrip/eu/es/aeroteca-flight-sim-store.md`

New: Aeroteca Flight Sim Store from Sam D

---

content/daytrip/eu/gb/kelvingrove-art-gallery-and-museum.md

**Venue:** Kelvingrove Art Gallery and Museum
**Location:** Kelvingrove Art Gallery and Museum, Argyle Street, Stobcross, Kelvinhaugh, Glasgow, Glasgow City, Scotland, G3 8AG, United Kingdom
**Submitted by:** Keota
**Website:** https://www.glasgowlife.org.uk/museums/venues/kelvingrove-art-gallery-and-museum
A vast museum that includes many famous pieces of art and artifacts of various cultures and regions.
**Submission ID:** 394
**File:** `content/daytrip/eu/gb/kelvingrove-art-gallery-and-museum.md`

New: Kelvingrove Art Gallery and Museum from Keota

---

content/daytrip/eu/nl/museum-t-kromhout.md

**Venue:** Museum 't Kromhout
**Location:** Hoogte Kadijk 147, 1018 BJ, Amsterdam, The Netherlands
**Website:** https://www.kromhoutmuseum.nl/en/
Former shipyard where also engines were built. Now a museum dedicated to those Kromhout engines.
**Submission ID:** 400
**File:** `content/daytrip/eu/nl/museum-t-kromhout.md`

New: Museum 't Kromhout from Frederik Dekker

---

content/daytrip/na/us/hotel-del-coronado.md

**Venue:** Hotel Del Coronado
**Location:** Hotel Del Coronado, 1500, Orange Avenue, Coronado, San Diego County, California, United States
**Website:** https://en.wikipedia.org/wiki/Hotel_del_Coronado
The Del is an actively run hotel, but visitors can wander the grounds.  At Christmastime there's a gigantic tree decorated in the lobby.
To the East is the Coronado Bridge, just to the North there's a fun dog beach, and South along the Silver Strand is a pedestrian trail with a unique Solstice Clock.
From Wikipedia:
The Hotel del Coronado, also known as The Del and Hotel Del, is a historic beachfront hotel in Coronado, California, just across San Diego Bay from San Diego. A rare surviving example of an American architectural genre—the wooden Victorian beach …

New: Hotel Del Coronado from Bill Sanders

---

content/daytrip/na/us/san-diego-model-railroad-museum.md

**Venue:** San Diego Model Railroad Museum
**Location:** 1649, El Prado, Banker's Hill, San Diego, San Diego County, California, 92101, United States
**Website:** https://www.sdmrm.org/
Spanning over 27,000 square feet of trains, trestles, and tracks, we are in the heart of natural beauty framed by the majestic backdrop of Balboa Park. The San Diego Model Railroad Museum (SDMRM) is a space where imagination is beautifully engineered. SDMRM features both indoor and outdoor exhibits and programming for all ages.
Our mission is to research, collect, preserve, and present the heritage of American railroading using educational programs, displays, toy trains, and scale models of California railroads. At every twist, turn, and tunnel we spark curiosity with …

New: San Diego Model Railroad Museum from Bill Sanders

---

content/daytrip/eu/gb/herschel-museum-of-astronomy.md

**Venue:** Herschel Museum of Astronomy
**Location:** 19 New King Street, Bath, BA1 2BL, England, UK
**Website:** https://herschelmuseum.org.uk
This museum is the house that William Herschel lived in, and from where Uranus was discovered. It commemorates the astronomical and musical accomplishments of William, and his sister Caroline -- a well-known astronomer in her own right.
**Submission ID:** 406
**File:** `content/daytrip/eu/gb/herschel-museum-of-astronomy.md`

New: Herschel Museum of Astronomy from Hugo

---

content/daytrip/eu/gb/the-devils-porridge-museum.md

**Venue:** The Devil's Porridge Museum
**Location:** Stanfield, Annan Road, Eastriggs, Dumfries and Galloway DG12 6TF, Alba/Scotland, UK
**Website:** https://www.devilsporridge.org.uk
The Devil's Porridge: Cordite, an explosive and propellant used heavily in the First World War.
This location near Gretna, on the south coast of Scotland, was a major factory for cordite in the 20th century, and the museum tells the story of the factory, and of the history of the area in both world wars and the cold war.
**Submission ID:** 407
**File:** `content/daytrip/eu/gb/the-devils-porridge-museum.md`

New: The Devil's Porridge Museum from Hugo

---

content/daytrip/eu/gb/john-taylor-bellfoundry-museum.md

**Venue:** John Taylor Bellfoundry Museum
**Location:** John Taylor Bellfoundry Museum, Freehold Street, Loughborough  LE11 1AR, United Kingdom
**Submitted by:** Roger Light
**Website:** https://loughboroughbellfoundry.org/
The last working bell foundry in Britain. They do tours during the summer months, which need booking in advance. The tours cover all aspects of bell making and associated wood work. There are hundreds of bells of all sorts of sizes sitting around. They do rare casting tours as well, where you can see a casting of a bell or iron fitting.
The start and end of the tour is up stairs.
**Submission ID:** 409
**File:** `content/daytrip/eu/gb/john-taylor-bellfoundry-museum.md`

New: John Taylor Bellfoundry Museum from Roger Light

---

content/daytrip/eu/at/retro-gaming-museum.md

**Venue:** Retro Gaming Museum
**Location:** Retro Gaming Museum, 1, Fritz-Grünbaum-Platz, Vienna, 1060, Austria
**Submitted by:** EJ
**Website:** https://www.gamingmuseum.at/#wien
A retro gaming museum housed in a former flak tower.
**Submission ID:** 411
**File:** `content/daytrip/eu/at/retro-gaming-museum.md`

New: Retro Gaming Museum from EJ

---

content/daytrip/eu/gb/east-midlands-aeropark.md

**Venue:** East Midlands Aeropark
**Location:** East Midlands Aeropark, Castle Donington, Leicestershire, DE74 2PR, United Kingdom
**Submitted by:** Roger Light
**Website:** http://www.eastmidlandsaeropark.org/
A collection of aircraft, aircraft sections, and museum, run by volunteers. Notable aircraft include a Vulcan, a Nimrod with restored interior (including chunky laptops), a Lightning, and a front loading Argosy.
**Submission ID:** 412
**File:** `content/daytrip/eu/gb/east-midlands-aeropark.md`

New: East Midlands Aeropark from Roger Light

---

content/daytrip/na/us/age-of-steam-roundhouse-museum.md

**Venue:** Age of Steam Roundhouse Museum
**Location:** 213 Smokey Lane Road Southwest, Sugarcreek, Tuscarawas County, Ohio, 44681, United States
**Submitted by:** MRPockets
**Website:** https://ageofsteamroundhouse.org
A large, private collection of mostly steam but also some diesel-electric locomotives and rolling stock. The museum offers tours and (at a few events) rides. They are actively working to restore their collection.
**Submission ID:** 414
**File:** `content/daytrip/na/us/age-of-steam-roundhouse-museum.md`

New: Age of Steam Roundhouse Museum from MRPockets

---

content/daytrip/eu/gb/hatchlands-park.md

**Venue:** Hatchlands Park
**Location:** Hatchlands Park, A246, West Horsley, Guildford, Surrey, England, KT24 6EA, United Kingdom
**Submitted by:** LewJ
**Website:** https://www.nationaltrust.org.uk/visit/surrey/hatchlands-park
Historical House, great views.
**Submission ID:** 415
**File:** `content/daytrip/eu/gb/hatchlands-park.md`

New: Hatchlands Park from LewJ

---

content/daytrip/eu/de/berliner-u-bahn-museum.md

**Venue:** Berliner U-Bahn-Museum
**Location:** Berliner U-Bahn-Museum, Rossitter Platz, Westend, Charlottenburg-Wilmersdorf, Berlin, 14052, Germany
**Website:** https://www.museumsportal-berlin.de/en/museums/berliner-u-bahn-museum/
A collection of artifacts connected to the Berlin subway (U-Bahn). The museum is located in the former Olympia stadium signal box dating back to 1931.
**Submission ID:** 416
**File:** `content/daytrip/eu/de/berliner-u-bahn-museum.md`

New: Berliner U-Bahn-Museum from debb1046

---

content/daytrip/na/us/poway-midland-railroad.md

**Venue:** Poway Midland Railroad
**Location:** 14134 Midland Rd, Poway, California, United States
**Website:** https://powaymidlandrr.org/
The Poway-Midland Railroad is a full-size, narrow-gauge railroad in Old Poway Park which carries passengers aboard vintage and antique railroad equipment. The railroad is owned by the City of Poway, and operated by the Poway Midland Railroad Volunteers, is a 501 (c) 3 Corporation that exists on passenger ticket fares and donations.
Through the restoration, preservation, and operation of vintage railroad equipment, the Volunteers are able to offer the community and visitors alike with a vintage train ride around the park, and through interpretation, provide educational programs (such as Operation Lifesaver) as well. …

New: Poway Midland Railroad from Bill Sanders

---

content/daytrip/na/us/pacific-southwest-railway-museum-campo-depot.md

**Venue:** Pacific Southwest Railway Museum Campo Depot
**Location:** 750 Depot Street, Campo, California, United States
**Website:** https://www.psrm.org/
Aside from the outdoor and indoor walk through museum, this railway still offers rides on vintage locomotives.  Up until semi-recent damage to a tunnel, there were even rides across the border to Tecate brewery.
The Pacific Southwest Railway Museum Association is a non-profit educational organization dedicated to the preservation and interpretation of railroads as they existed in the Pacific Southwest. With over 120 pieces of equipment and artifacts on display between our two facilities in Campo, CA and La Mesa, CA, the Pacific Southwest Railway Museum Association provides a unique learning experience for …

New: Pacific Southwest Railway Museum Campo Depot from Bill Sanders

---

content/daytrip/na/us/tuna-harbor-dockside-market.md

**Venue:** Tuna Harbor Dockside Market
**Location:** 598 Harbor Lane  San Diego, California, United States
**Website:** https://www.thdocksidemarket.com/
An open-air locally-caught seafood market run by independent fishers, open Saturdays only.  In addition to finding local species unlikely to be encountered at the grocery store, this market also has a a cutting booth where you can have whole fish processed as well as a seafood stand with unique San Diego-inspired dishes.
**Submission ID:** 419
**File:** `content/daytrip/na/us/tuna-harbor-dockside-market.md`

New: Tuna Harbor Dockside Market from Bill Sanders

---

content/daytrip/eu/gb/museum-of-timekeeping.md

**Venue:** Museum of Timekeeping
**Location:** Museum of Timekeeping, Main Street, Upton , Nottinghamshire, NG23 5TE, United Kingdom
**Submitted by:** The Doctor
**Website:** https://www.museumoftimekeeping.org.uk/
A museum all about clocks and timekeeping.
**Submission ID:** 421
**File:** `content/daytrip/eu/gb/museum-of-timekeeping.md`

New: Museum of Timekeeping from The Doctor

---

content/daytrip/eu/gb/wollaton-hall.md

**Venue:** Wollaton Hall
**Location:** Wollaton Hall, Nottingham, NG8 2AE, United Kingdom
**Submitted by:** Pound Shop David Attenborough
**Website:** https://wollatonhall.org.uk/hall-and-museum/natural-history-museum/
A natural history museum full of interesting and unusual exhibits.
**Submission ID:** 427
**File:** `content/daytrip/eu/gb/wollaton-hall.md`

New: Wollaton Hall from Pound Shop David Attenborough

---

content/daytrip/as/jp/aichi-expo-memorial-museum.md

**Venue:** Aichi Expo Memorial Museum
**Location:** 〒480-1342 愛知県長久手市 茨ケ廻間乙1533-1
**Website:** https://www.aichi-koen.com/moricoro/shisetsu/kinenkan/
Part of the legacy of the 2005 Expo. The small free museum houses a collection of artifacts donated by the exhibiting countries, and displays about the expo itself. There are also some robot/animatronics that were used. It is housed in what used to be the suites for visiting dignitaries. 
Oddly for something from 2005 it has a very 60s futurist feel to the design. 
You can get to the park on the Linimo maglev, another legacy of the Expo. 
The Ghibli museum is also hosted in the park and there are many Ghibli items to discover in the public areas. 
**Submission ID:** 428
**File:** …

New: Aichi Expo Memorial Museum from Shiawase

---

content/daytrip/eu/gb/bell-pettigrew-museum.md

**Venue:** Bell Pettigrew Museum
**Location:** Bell Pettigrew Museum, North Street, St Andrews, Fife, Scotland, KY16 9AJ, United Kingdom
**Submitted by:** Pound Shop David Attenborough
**Website:** https://www.visitscotland.com/info/see-do/bell-pettigrew-museum-of-natural-history-p2216261
A small and unusual natural history museum hidden in the back streets of St Andrews.
**Submission ID:** 429
**File:** `content/daytrip/eu/gb/bell-pettigrew-museum.md`

New: Bell Pettigrew Museum from Pound Shop David Attenborough

---

content/daytrip/eu/gb/andrew-carnegie-birthplace-museum.md

**Venue:** Andrew Carnegie Birthplace Museum
**Location:** Andrew Carnegie Birthplace Museum, Moodie Street, Dunfermline, Fife, KY12 7PL, United Kingdom
**Submitted by:** George Lauder
**Website:** https://www.carnegiebirthplace.com/
Understand the not quite rags to riches story of Andrew Carnegie, one of the world's biggest steel tycoons.
**Submission ID:** 430
**File:** `content/daytrip/eu/gb/andrew-carnegie-birthplace-museum.md`

New: Andrew Carnegie Birthplace Museum from George Lauder

---

content/daytrip/na/us/asmbly-makerspace.md

**Venue:** Asmbly Makerspace
**Location:** 9701, Dessau Road, Cameron Industrial, Austin, Travis County, Texas, 78754, United States
**Submitted by:** Jim Kelley
**Website:** https://asmbly.org/
Asmbly is Austin’s largest nonprofit community makerspace. They have shops for woodworking, metal work, laser cutting, electronics, 3D-printing, ceramics, and textiles.
**Submission ID:** 433
**File:** `content/daytrip/na/us/asmbly-makerspace.md`

New: Asmbly Makerspace from Jim Kelley

---

content/daytrip/eu/de/museumspark-rdersdorf.md

**Venue:** Museumspark Rüdersdorf
**Location:** Museumspark Rüdersdorf, 41, Bergbrück, Rüdersdorf, Rüdersdorf bei Berlin, Märkisch-Oderland, Brandenburg, 15562, Germany
**Website:** https://www.museumspark.de/
Industrial heritage site where lime used to be made in several big coal fired lime kilns. Some of the buildings and kilns and other infrastructure have been preserved and can be visited with a guided tour. There is a also a tour and exhibition about geology and fossils found in the lime stone. An open pit limestone mine which is still used is next to the museum area.  
**Submission ID:** 434
**File:** `content/daytrip/eu/de/museumspark-rdersdorf.md`

New: Museumspark Rüdersdorf from debb1046

---

content/daytrip/eu/de/dampflokfreunde-berlin.md

**Venue:** Dampflokfreunde Berlin
**Location:** Dampflokfreunde Berlin, 9, Wagner-Régeny-Allee,  Berlin, 12487, Germany
**Website:** https://www.berlin-macht-dampf.com/
Railway yard with a roundhouse locomotive shed and turn table. The shed houses steam locomotives and old diesels. Only accessible during special events.  
**Submission ID:** 435
**File:** `content/daytrip/eu/de/dampflokfreunde-berlin.md`

New: Dampflokfreunde Berlin from debb1046

---

content/daytrip/eu/de/schifffahrtsmuseum-rostock.md

**Venue:** Schifffahrtsmuseum Rostock
**Location:** Schmarl Dorf 40, Rostock, Mecklenburg-Vorpommern, 18106, Germany
**Website:** https://schifffahrtsmuseum-rostock.de/
Diesel powered cargo ship from the GDR era that has been converted to a museum of maritime history. The engine room is open to visitors.  
**Submission ID:** 436
**File:** `content/daytrip/eu/de/schifffahrtsmuseum-rostock.md`

New: Schifffahrtsmuseum Rostock from debb1046

---

content/daytrip/eu/gb/retrodome.md

---
name: Bug Fix
about: Create a report to help us improve
title: "[BUG]"
labels: bug
assignees: ''
---
**Describe the bug**
When I created the entry for Retrodome, I didn't include my name, but the name of the location, because I'm a numpty.
**To Reproduce**
Steps to reproduce the behavior:
1. Go to 'Retrodome'
2. view detailed information
3. See the "Poster" as "Retrodome" rather that "David Cooper"
**Expected behavior**
The poster information should show David Cooper.
**Desktop (please complete the following information):**
- OS: Zorin
- Browser: Firefox
- Version: 139
**Additional context**
Turns out I can do this in the browser, but had gone down this new PR rabbit hole
**Testing**
**Fixes Issue**

Updated Poster information for Retrodome Barnsley

---

content/daytrip/na/us/the-rock-house.md

**Venue:** The Rock House
**Location:** Rockhouse State Memorial, 3663 Country Club Rd, Sparta, TN 38583
**Submitted by:** Resin
**Website:** https://www.tn.gov/historicalcommission/state-programs/state-historic-sites/sparta-rock-house.html
The small, stone Rock House, originally built to collect tolls on a private road, was built between 1835 and 1839 by Barlow Fiske, who operated a stage coach inn and stables nearby.
It played an important role in the early development of Tennessee's transportation system. Andrew Jackson often stopped here on trips from Nashville to Washington. Other notable visitors included James K. Polk, Sam Houston, and Frank Clement, all once governors of the Volunteer State.
-Credit to the Tennessee State Government website-
**Submission ID:** 441
**File:** …

New: The Rock House from Resin

---

content/daytrip/eu/gb/heathrow-aircraft-viewing-area.md

**Venue:** Heathrow Aircraft Viewing Area
**Location:** Aircraft Viewing Area, Newall Road, London Borough of Hillingdon, London, Greater London, England, TW6 2FN, United Kingdom
**Website:** https://www.heathrow.com/at-the-airport/airport-maps/spectator-areas
Hidden away on an industrial estate, a viewing platform to watch aeroplanes arriving and departing Heathrow Airport.
**Submission ID:** 446
**File:** `content/daytrip/eu/gb/heathrow-aircraft-viewing-area.md`

New: Heathrow Aircraft Viewing Area from AndiBing

---

content/daytrip/eu/gb/mardale.md

**Venue:** Mardale
**Location:** Mardale, England, United Kingdom
**Website:** https://en.wikipedia.org/wiki/Mardale
Mardale was flooded along with the rest of the valley, destroying several villages, creating Haweswater Reservoir. The dam was built in the 1930s. At times of drought, you can see the remains of the walls from the old buildings.
**Submission ID:** 447
**File:** `content/daytrip/eu/gb/mardale.md`

New: Mardale from AndiBing

---

content/daytrip/eu/se/shipwreck-of-the-swiks-in-trollskogen.md

**Venue:** Shipwreck of the Swiks in Trollskogen
**Location:** Vraket Swiks, Murgrönestigen, Borgholms kommun, Kalmar County, Sweden
**Submitted by:** jfml
**Website:** https://en.wikipedia.org/wiki/Trollskogen
Shipwreck of three-masted schooner „Swiks“ that was wrecked here in 1926. Near the parking space are small forest / themed huts and in the very fairy-tale like forest lots of cairns and stone circles.
https://www.atlasobscura.com/places/trollskogen-troll-forest
**Submission ID:** 455
**File:** `content/daytrip/eu/se/shipwreck-of-the-swiks-in-trollskogen.md`

New: Shipwreck of the Swiks in Trollskogen from jfml

---

content/daytrip/eu/gb/cramond-island.md

**Venue:** Cramond Island
**Location:** Cramond Island, City of Edinburgh, Scotland, EH4 6HZ, United Kingdom
**Submitted by:** jfml
**Website:** https://en.wikipedia.org/wiki/Cramond_Island
Cramond island is only accessible at low tide (so check the tides!) but has a very nice walk way to the island as well as bunkers and ruins.
**Submission ID:** 456
**File:** `content/daytrip/eu/gb/cramond-island.md`

New: Cramond Island from jfml

---

content/daytrip/eu/fr/muse-des-moulages.md

**Venue:** Musée des Moulages
**Location:** Rue Bichat, Quartier de l'Hôpital Saint-Louis, Paris 10e Arrondissement, Paris, 75010, France
**Website:** https://hopital-saintlouis.aphp.fr/le-musee-des-moulages-de-lhopital-de-saint-louis/
A collection, unique in the world, that bears witness to the history of medicine and dermatology. It contains apprinately 5000 wax castings of parts of the body affected by dermatological lesions like skin diseases and syphilis. 
**Submission ID:** 457
**File:** `content/daytrip/eu/fr/muse-des-moulages.md`

New: Musée des Moulages from MarcN

---

content/daytrip/eu/gb/great-barr-hall.md

**Venue:** Great Barr Hall
**Location:** Great Barr Hall, Walsall, England B43 7BL
**Website:** https://en.wikipedia.org/wiki/Great_Barr_Hall
18th-century mansion in Strawberry Hill style. Has associations with the Lunar Society and is Grade II listed. In a very poor state of repair and on the Buildings at Risk Register.
Featured in an episode of Dalziel and Pascoe, in which James Bolam guest starred.
**Submission ID:** 461
**File:** `content/daytrip/eu/gb/great-barr-hall.md`

New: Great Barr Hall from Andy Mabbett

---

content/daytrip/eu/gb/perry-bridge.md

**Venue:** Perry Bridge
**Location:** Perry Bridge, Perry Barr, Birmingham, West Midlands, England, B42 2HB, United Kingdom
**Website:** https://en.wikipedia.org/wiki/Perry_Bridge
Bridge built in 1711; Grade II listed building.
**Submission ID:** 460
**File:** `content/daytrip/eu/gb/perry-bridge.md`

New: Perry Bridge from Andy Mabbett

---

content/daytrip/eu/gb/joseph-chamberlain-memorial-clock-tower.md

**Venue:** Joseph Chamberlain Memorial Clock Tower
**Location:** University Square, Birmingham, England B15 2TT
**Website:** https://en.wikipedia.org/wiki/Joseph_Chamberlain_Memorial_Clock_Tower
World's tallest free-standing clock tower.
**Submission ID:** 459
**File:** `content/daytrip/eu/gb/joseph-chamberlain-memorial-clock-tower.md`

New: Joseph Chamberlain Memorial Clock Tower from Andy Mabbett

---

content/daytrip/eu/gb/saint-pauls-church.md

**Venue:** Saint Paul's Church
**Location:** Saint Paul's Church, Saint Paul's Square, Jewellery Quarter, Birmingham, West Midlands, England, B3 1RB, United Kingdom
**Website:** http://www.saintpaulbrum.org/
Church used by James Watt and Matthew Boulton; East window by Francis Eginton.
**Submission ID:** 458
**File:** `content/daytrip/eu/gb/saint-pauls-church.md`

New: Saint Paul's Church from Andy Mabbett

---

content/daytrip/eu/gb/cragside.md

**Venue:** Cragside
**Location:** Cragside, Carriage Drive, Rothbury, Northumberland, North East, England, NE65 7PU, United Kingdom
**Submitted by:** alwAudio
**Website:** https://www.nationaltrust.org.uk/visit/north-east/cragside
Victorian Tudor Revival house, nestled in acres of wooded landscape. Arguably the first 'smart' home, with dams and lakes generating hydroelectric power, a water-driven sawmill, laundry, early dishwasher, dumb waiter, hydraulic lift and a hydroelectric rotisserie.
**Submission ID:** 464
**File:** `content/daytrip/eu/gb/cragside.md`

New: Cragside from alwAudio

---

content/daytrip/eu/be/train-world.md

**Venue:** Train World
**Location:** Train World, Prinses Elisabethplein, Monplaisir, Schaarbeek, Brussels-Capital, 1030, Belgium
**Submitted by:** robvdw2
**Website:** https://www.trainworld.be
Large indoor train museum at the Schaarbeek railway station focusing on the history of the Belgian railways. Spanning over 8000 square meters, the museum showcases more than 20 locomotives
**Submission ID:** 468
**File:** `content/daytrip/eu/be/train-world.md`

New: Train World from robvdw2

---

content/daytrip/eu/gb/hawker-hunter-wt723.md

**Venue:** Hawker Hunter WT723
**Location:** Hawker Hunter WT723, Warwick Road, Greet, Birmingham, England B11 3RF
**Website:** https://www.thunder-and-lightnings.co.uk/hunter/survivor.php?id=338
Preserved Hawker Hunter aircraft.
**Submission ID:** 470
**File:** `content/daytrip/eu/gb/hawker-hunter-wt723.md`

New: Hawker Hunter WT723 from Andy Mabbett

---

content/daytrip/eu/ch/swiss-museum-of-transport.md

**Venue:** Swiss Museum of Transport
**Location:** Swiss Museum of Transport, 5, Lidostrasse, Schlössli, Lucerne, 6006, Switzerland
**Submitted by:** Renaldo
**Website:** https://www.verkehrshaus.ch/en/home.html
Anyone interested in the technical details of transportaion (rail, automotive, marine, aviation, space) will have a good time
**Submission ID:** 474
**File:** `content/daytrip/eu/ch/swiss-museum-of-transport.md`

New: Swiss Museum of Transport from Renaldo

---

content/daytrip/eu/ch/gameorama.md

**Venue:** Gameorama
**Location:** Gameorama, 49, Hirschengraben, Kleinstadt, Lucerne, 6000, Switzerland
**Submitted by:** Renaldo
**Website:** https://www.gameorama.ch/en
Games from different eras and with different technologies can be tried out. Reservations are recommended
**Submission ID:** 476
**File:** `content/daytrip/eu/ch/gameorama.md`

New: Gameorama from Renaldo

---

content/daytrip/eu/gb/west-berkshire-museum.md

**Venue:** West Berkshire Museum
**Location:** West Berkshire Museum, Wharf Street, Newbury Wharf, Newbury, West Berkshire, England, RG14 5AS, United Kingdom
**Submitted by:** Neil
**Website:** https://www.westberkshireheritage.org/west-berkshire-museum
A small, free (but donations welcomed) museum. The downstairs section sets out the history of Newbury and wider west Berkshire, with trails for children available for free from the reception desk. The upstairs section houses temporarily exhibitions, and a small reference library.
**Submission ID:** 483
**File:** `content/daytrip/eu/gb/west-berkshire-museum.md`

New: West Berkshire Museum from Neil

---

content/daytrip/eu/se/hgbo-bruk.md

**Venue:** Högbo Bruk
**Location:** Hans Hiertas väg, Sandviken, Sweden
**Submitted by:** NerdyCec
**Website:** https://www.hogbobruk.se
The story of Högbo Bruk began with Bergslagen's good iron ore, skilled miners and a rare suitable watercourse. With the rich forests, there were all the conditions for a flourishing ironworks. In the 17th century, Högbo Bruk became a center for iron production, a place where development took place and wealth was created.
Högbo Bruk is best known as the place where Consul Göransson forged the first Bessemer steel in 1858 and revolutionized steel production. Göransson's steel became a worldwide success and he started a completely new industrial company from the ironworks in Högbo. Thus, a 200-year-long era ended and another began. New owners took over and …

New: Högbo Bruk from NerdyCec

---

content/daytrip/eu/gb/operation-chariot-memorial.md

**Venue:** Operation Chariot Memorial
**Location:** Prince of Wales Pier, Falmouth, Cornwall, England, TR11 3DF, United Kingdom
**Website:** https://www.operation-chariot.org/
Memorial to Operation Chariot. The St. Nazaire Raid. Known as "The Greatest Raid of All".
OPERATION CHARIOT
FROM THIS HARBOUR 622 SAILORS
AND COMMANDOS SET SAIL FOR
THE SUCCESSFUL RAID ON ST.NAZAIRE
28TH MARCH 1942 168 WERE KILLED
5 VICTORIA CROSSES WERE AWARDED
----- o -----
DEDICATED TO THE MEMORY OF
THEIR COMRADES BY
THE ST.NAZAIRE SOCIETY
**Submission ID:** 479
**File:** `content/daytrip/eu/gb/operation-chariot-memorial.md`

New: Operation Chariot Memorial from AndiBing

---

content/daytrip/eu/at/seebhne-bregenz.md

**Venue:** Seebühne Bregenz
**Location:** Seebühne Bregenz, Bregenz,Vorarlberg, 6900, Austria
**Website:** https://bregenzerfestspiele.com/en
Floating theatre. Made famous(er) by the film Quantum of Solace (2008).
**Submission ID:** 481
**File:** `content/daytrip/eu/at/seebhne-bregenz.md`

New: Seebühne Bregenz from AndiBing

---

content/daytrip/na/us/world-chess-hall-of-fame.md

**Venue:** World Chess Hall of Fame & Galleries
**Location:** St. Louis, MO
**Submitted by:** ifTaylor
**Website:** https://worldchesshof.org/
Honoring the masters of chess, the World Chess Hall of Fame & Galleries (WCHOF) is a premier destination for chess enthusiasts, dedicated to preserving and celebrating the rich history of the game. Located in Saint Louis, Missouri, United States, the WCHOF is a hub for education, exhibitions, and events that showcase the cultural significance and impact of chess.
Submission: 768
File: content/daytrip/na/us/world-chess-hall-of-fame.md

daytrip: world chess hall of fame

---

content/daytrip/eu/gb/morpeth-chantry-bagpipe-museum.md

**Venue:** Morpeth Chantry Bagpipe Museum
**Location:** Morpeth Chantry Bagpipe Museum, Chantry Place, High Stanners, Morpeth, Northumberland, NE61 1PD
**Submitted by:** Sarah Dal
**Website:** https://museumsnorthumberland.org.uk/morpeth-chantry-bagpipe-museum/
Small museum dedicated to the Northumbrian small pipes and other examples of bagpipe instruments from across the world
**Submission ID:** 493
**File:** `content/daytrip/eu/gb/morpeth-chantry-bagpipe-museum.md`

New: Morpeth Chantry Bagpipe Museum from Sarah Dal

---

content/daytrip/eu/de/tagebau-hambach.md

**Venue:** Tagebau Hambach
**Location:** Aussichtspunkt "Haus am See" Tagebau Hambach, Bürgeweg, Niederzier, Kreis Düren, 52382, Deutschland
**Submitted by:** clonejo
**Website:** https://www.rwe.com/der-konzern/laender-und-standorte/tagebau-hambach/
Check out Europe's biggest hole and see Bagger 288's first workplace for yourself!
It's outside, only makes sense with good weather and no fog. Bring binoculars or your telephoto camera.
Not wheelchair accessible, but there is another viewpoint at the opposite side without steps (i think).
A bit to the south you will find an abandoned piece of motorway.
**Submission ID:** 491
**File:** `content/daytrip/eu/de/tagebau-hambach.md`

New: Tagebau Hambach from clonejo

---

content/daytrip/na/us/pasto-agricultural-museum.md

**Venue:** Pasto Agricultural Museum
**Location:** 2710 West Pine Grove Road, Ferguson Twp, Pennsylvania, 16865, United States
**Submitted by:** JamesEndresHowell
**Website:** https://agsci.psu.edu/pasto/plan-your-visit
Visits by appointment. Check for special events.
**Submission ID:** 502
**File:** `content/daytrip/na/us/pasto-agricultural-museum.md`

New: Pasto Agricultural Museum from JamesEndresHowell

---

content/daytrip/eu/gb/tyneham-village.md

**Venue:** Tyneham Village
**Location:** Tyneham, Tyneham Range Walks, Steeple with Tyneham, Dorset, England, BH20 5QF, United Kingdom
**Submitted by:** Filbert
**Website:** https://www.visit-dorset.com/listing/tyneham-village/13633301/
The village where time stopped in 1943. The Village was evacuated in December 1943 during WWII and has been deserted ever since.
An interesting place to spend an hour wandering round, then enjoy the views across the ranges (if the roads are open!) afterwards. 
**Submission ID:** 509
**File:** `content/daytrip/eu/gb/tyneham-village.md`

New: Tyneham Village from Filbert

---

content/daytrip/as/jp/toto-toilet-museum.md

**Venue:** TOTO Toilet Museum
**Location:** TOTO Museum, Nakashima 2-chome, Kokura-Kita Ward, Kitakyushu, Fukuoka Prefecture, 803-0814, Japan
**Submitted by:** Adam
**Website:** https://jp.toto.com/en/knowledge/visit/museum/
Learn all about the history and products of the company that made Japanese toilets famous, and see exhibitions from the early days making tableware, to the various toilet models through the ages. Of course, you can use the latest model while you're there.
**Submission ID:** 510
**File:** `content/daytrip/as/jp/toto-toilet-museum.md`

New: TOTO Toilet Museum from Adam

---

content/daytrip/eu/nl/mechanisch-erfgoed-centrum.md

**Venue:** Mechanisch Erfgoed Centrum
**Location:** Dronterweg 29, 8251 PA, Dronten, The Netherlands
**Website:** https://www.mecmuseum.nl/
Museum with a large collection of machines and steam engines. Housed in a former bus garage from Nijmegen.
**Submission ID:** 515
**File:** `content/daytrip/eu/nl/mechanisch-erfgoed-centrum.md`

New: Mechanisch Erfgoed Centrum from Frederik Dekker

---

content/daytrip/eu/de/energiebunker-in-wilhelmsburg.md

**Venue:** Energiebunker in Wilhelmsburg
**Location:**  Neuhöfer Straße 7,  21107 Hamburg  
**Submitted by:** hh
**Website:** https://unternehmen.hamburger-energiewerke.de/energiewende/energiebunker
This large flack tower bunker was converted to a district hearing storage and source. Tours detail the history and technology.
**Submission ID:** 516
**File:** `content/daytrip/eu/de/energiebunker-in-wilhelmsburg.md`

New: Energiebunker in Wilhelmsburg from hh

---

content/daytrip/eu/im/magnetic-hill.md

**Venue:** Magnetic Hill
**Location:** On the A27 Ronague Road between Colby and Round Table
**Submitted by:** IsleOfManDan
**Website:** https://en.wikipedia.org/wiki/List_of_gravity_hills
A hill where gravity works the wrong way. Bring a football and watch it roll uphill. Or put a vehicle in neutral with the brakes off and be amazed as you roll up the hill!
(There is a stone marking the spot, but the engraving has all but weathered away and it's often lost in the undergrowth.)
**Submission ID:** 518
**File:** `content/daytrip/eu/im/magnetic-hill.md`

New: Magnetic Hill from IsleOfManDan

---

content/daytrip/eu/gb/doesliverpool.md

Venue: DoES Liverpool
Location: 1st Floor, The Tapestry, 68-76 Kempston St, Liverpool L3 8HL
Submitted by: TacticalTechyTaky
Website: https://doesliverpool.com
Maker Space which hosts Maker Night events for free frequently, home for the Liverpool LUG meetings.Perfect place to do ad-hoc projects using available equipment(Laser Cutter,3D printer, solder station, etc).

New: Does Liverpool

---

content/daytrip/eu/de/ccc-berlin.md

**Venue:** CCC Berlin
**Location:** Marienstr. 11, 10117 Berlin
**Website:** https://berlin.ccc.de/
Chaos Computer Club Berlin. Hackspace open to the public on Thursday evenings.
**Submission ID:** 521
**File:** `content/daytrip/eu/de/ccc-berlin.md`

New: CCC Berlin from debb1046

---

content/daytrip/eu/gb/chepstow-castle.md
content/daytrip/eu/gb/goodrich-castle.md
content/daytrip/eu/gb/hamsterley-forest.md
content/daytrip/eu/gb/ludlow-castle.md

Some venues had erroneously got `.md` on the end of their slugs.

Fix erroneous slugs including .md extensions

---

content/daytrip/eu/de/schiffshebewerk-niederfinow.md

**Venue:** Schiffshebewerk Niederfinow
**Location:** Hebewerkstr. 70a, 16248 Niederfinow
**Website:** https://schiffshebewerk-niederfinow.com/en/
Old boat lift dating back to 1934 next to a new one from 2022.
**Submission ID:** 527
**File:** `content/daytrip/eu/de/schiffshebewerk-niederfinow.md`

New: Schiffshebewerk Niederfinow from debb1046

---

content/daytrip/eu/de/gottlieb-daimler-gedenksttte.md

**Venue:** Gottlieb-Daimler-Gedenkstätte
**Location:** Taubenheimstraße 13, 70372 Stuttgart, Germany
**Website:** https://www.stuttgart-tourist.de/en/a-daimler-memorial-sight
Garden shed where Daimler and Maybach developed one of the first gasoline engines used in a vehicle.
**Submission ID:** 529
**File:** `content/daytrip/eu/de/gottlieb-daimler-gedenksttte.md`

New: Gottlieb-Daimler-Gedenkstätte from debb1046

---

content/daytrip/na/ca/canada-centre-for-inland-waters.md

**Venue:** Canada Centre for Inland Waters
**Location:**  867 Lakeshore Road, Burlington, Ontario, Canada
**Website:** https://profils-profiles.science.gc.ca/en/research-centre/canada-centre-inland-waters
Only open to the public a few days each year, but if you can catch one of them and you're interested in ecological sciences you can't beat it. Supporting the Canadian federal government's Ministry of the Environment and Climate Change they engage in research about human impacts on lakes, watersheds, and coastal waters.
**Submission ID:** 144
**File:** `content/daytrip/na/ca/canada-centre-for-inland-waters.md`

New: Canada Centre for Inland Waters from Paul Drye

---

content/daytrip/eu/gb/the-bentwaters-cold-war-museum.md

**Venue:** The Bentwaters Cold War Museum
**Location:** Building 134, Bentwaters Park, Woodbridge IP12 2TW
**Submitted by:** Matthew
**Website:** https://bcwm.org.uk/
The Bentwaters Cold War Museum is housed in a former USAF hardened command post building, the only one of its kind open to the public in Europe. This isn't just some converted hangar - it's the actual bunker where they would have coordinated nuclear deterrence operations during the Cold War.
What makes it properly nerdy is that volunteers spent three years restoring the main War Operations Room and Battle Cabin to their original condition, complete with decontamination showers and airlocks meant to keep personnel safe in the event of nuclear war. You're literally walking through a facility designed to function during World …

New: The Bentwaters Cold War Museum from Matthew

---

content/daytrip/eu/gb/alan-turing-statue.md

**Venue:** Alan Turing statue
**Location:** Sackville Gardens, Sackville Street, Manchester
**Submitted by:** Mark
**Website:** https://www.manchester.gov.uk/directory_record/439818/sackville_gardens/category/301/all_parks_playgrounds_and_open_spaces
A memorial to computing pioneer Alan Turing, featuring a statue of Turing sitting on a bench, and a board detailing his life.
**Submission ID:** 539
**File:** `content/daytrip/eu/gb/alan-turing-statue.md`

New: Alan Turing statue from Mark

---

content/daytrip/eu/gb/east-grinstead-museum.md

**Venue:** East Grinstead Museum
**Location:** East Grinstead Museum, Cantelupe Road, Sunnyside, East Grinstead, Mid Sussex, West Sussex, England, RH19 3BJ, United Kingdom
**Submitted by:** alwAudio
**Website:** https://www.eastgrinsteadmuseum.org.uk/
History of East Grinstead plus the Rebuilding Bodies and Souls’ flagship exhibition, opened in 2016 in the 75th anniversary year of the foundation of the Guinea Pig Club
This exhibition tells the story of the birth of reconstructive and plastic surgery in East Grinstead during the Second World War. It focuses on the story through the eyes of the patients and the medical professionals involved. Moreover, this had been the wish of those involved for nearly 70 years:
“One day someone will tell the complete story of Ward III in the way it should …

New: East Grinstead Museum from alwAudio

---

content/daytrip/na/us/ss-city-of-milwaukee.md

**Venue:** SS City of Milwaukee
**Location:** SS City of Milwaukee, Joslin Cove Drive, Manistee, Manistee County, Michigan, 49626, United States
**Submitted by:** Shastao
**Website:** https://www.carferry.com/
Railroad car ferry built in 1930 on display as a museum with tours, as well as a WWII era Coast Guard buoy tender (Acacia)
**Submission ID:** 541
**File:** `content/daytrip/na/us/ss-city-of-milwaukee.md`

New: SS City of Milwaukee from Shastao

---

content/daytrip/eu/gb/tullie-house-museum-art-gallery.md

**Venue:** Tullie House Museum & Art Gallery
**Location:** Tullie House, Abbey Street, Caldewgate, Carlisle, Cumberland, England, CA3 8UH, United Kingdom
**Website:** https://tullie.org.uk/
Tullie House has been part of the fabric of life in Carlisle since 1893, having been referred to as “Carlisle’s first learning centre”, long before the city gained a university.
**Submission ID:** 543
**File:** `content/daytrip/eu/gb/tullie-house-museum-art-gallery.md`

New: Tullie House Museum & Art Gallery from hiraethmarkb

---

content/daytrip/eu/gb/sweetheart-abbey.md

**Venue:** Sweetheart Abbey
**Location:** Sweetheart Abbey, Dumfries, New Abbey, Dumfries and Galloway, Scotland, DG2 8BU, United Kingdom
**Website:** https://en.wikipedia.org/wiki/Sweetheart_Abbey
Originally named Dulce Cor by the Cistercian monks who inhabited the abbey. It's more commonly known as Sweetheart Abbey, having been founded by Lady Dervorguilla of Galloway in tribute to her beloved husband, John de Balliol.
**Submission ID:** 546
**File:** `content/daytrip/eu/gb/sweetheart-abbey.md`

New: Sweetheart Abbey from hiraethmarkb

---

content/daytrip/eu/gb/arcade-archive.md

**Venue:** Arcade Archive
**Location:** Arcade Archive, Chalford, Stroud, Gloucestershire, England, GL6 8PR, United Kingdom
**Website:** https://www.retrocollective.co.uk/arcade-archive.php
A marvel for retro arcade fans. Part of the Retro Collective.
**Submission ID:** 549
**File:** `content/daytrip/eu/gb/arcade-archive.md`

New: Arcade Archive from hiraethmarkb

---

content/daytrip/eu/gb/dumfries-and-galloway-aviation-museum.md

**Venue:** Dumfries and Galloway Aviation Museum
**Location:** Dumfries and Galloway Aviation Museum, Tinwald Downs Road, Heathhall, Dumfries, Scotland, DG1 3SS
**Website:** https://www.dumfriesaviationmuseum.com/
Situated on the site of the wartime RAF Dumfries airfield, the collection of aircraft includes the Loch Doon Spitfire, and a collection of Airborne Forces exhibits.
**Submission ID:** 551
**File:** `content/daytrip/eu/gb/dumfries-and-galloway-aviation-museum.md`

New: Dumfries and Galloway Aviation Museum from hiraethmarkb

---

content/daytrip/eu/gb/national-museum-of-flight.md

**Venue:** National Museum of Flight
**Location:** National Museum of Flight, B1377, East Fortune, East Lothian, Scotland, EH39 5BT, United Kingdom
**Submitted by:** Isaac
**Website:** https://www.nms.ac.uk/national-museum-of-flight
Got one of the only public Concordes in the world, plus massive collections of civilian and military aviation, a de Havilland Comet and an Avro Vulcan
**Submission ID:** 552
**File:** `content/daytrip/eu/gb/national-museum-of-flight.md`

New: National Museum of Flight from Isaac

---

content/daytrip/eu/gb/shepherd-neame-visitor-centre.md

**Venue:** Shepherd Neame Visitor Centre
**Location:** Shepherd Neame Visitor Centre, Partridge Lane, The Brents, Faversham, Ospringe, Borough of Swale, Kent, England, ME13 7AN, United Kingdom
**Submitted by:** Valentin
**Website:** https://www.shepherdneame.co.uk/
Britain's oldest brewer. Brewery tours. 
**Submission ID:** 554
**File:** `content/daytrip/eu/gb/shepherd-neame-visitor-centre.md`

New: Shepherd Neame Visitor Centre from Valentin

---

content/daytrip/eu/gb/yorkshire-sculpture-park.md

**Venue:** Yorkshire Sculpture Park
**Location:** Yorkshire Sculpture Park, Huddersfield Road, West Bretton, Wakefield, WF4 4UG, England
**Submitted by:** Phil Clifford
**Website:** https://ysp.org.uk/
Beautiful parkland walks, a fabulous collection of sculpture, exhibitions, galleries and learning centre.  
**Submission ID:** 555
**File:** `content/daytrip/eu/gb/yorkshire-sculpture-park.md`

New: Yorkshire Sculpture Park from Phil Clifford

---

content/daytrip/eu/gb/watermouth-castle-family-theme-park.md

**Venue:** Watermouth Castle & Family Theme Park
**Location:** A399 between Combe Martin and Illfracombe
**Submitted by:** WeeBitShifty
**Website:** https://www.watermouthcastle.com
The Theme Park is your typical, boring Kid's Play stuff but the 'house' is a treasure trove of nerdy 'old timey' curios. Hilariously odd. 
- Google Maps link: [Search on Google Maps](https://www.google.com/maps/search/?api=1&query=A399%20between%20Combe%20Martin%20and%20Illfracombe)
- OpenStreetMap link: [Search on OpenStreetMap](https://www.openstreetmap.org/search?query=A399%20between%20Combe%20Martin%20and%20Illfracombe)
**Submission ID:** 563
**File:** `content/daytrip/eu/gb/watermouth-castle-family-theme-park.md`

New: Watermouth Castle & Family Theme Park from WeeBitShifty

---

content/daytrip/na/us/lake-superior-railroad-museum.md

**Venue:** Lake Superior Railroad Museum
**Location:** Lake Superior Railroad Museum, 506 West Michigan Street, Duluth, Minnesota, 55802, United States
**Submitted by:** nothingneko
**Website:** https://lsrm.org/
This museum features a giant room full of rows and rows of full size trains, many you can climb onboard and walk through. The museum is very well interpreted and features interpretation around Hobos (train hitchhikers) and life around trains.
During off hours, the museum is relatively sensory friendly, but it can be very hot and stagnant, and clearances onboard trains can be tight.
Tickets are $14 for adults, $7 for children under 13. There is a $1 discount for active duty military and veterans, and some staff members will give a $4 discount to students with ID.
- Google Maps …

New: Lake Superior Railroad Museum from nothingneko

---

content/daytrip/eu/de/volkssternwarte-mnchen-public-observatory.md

**Venue:** Volkssternwarte München. Public Observatory
**Location:** Zugang Volkssternwarte München, Ludwig-Jung-Straße, Echarding, Berg am Laim, Munich, Bavaria, 81671, Germany
**Submitted by:** Iαη 🍺
**Website:** https://sternwarte-muenchen.de/en/
You can see space from Munich! Book a tour of the observatory
- Google Maps link: [Search on Google Maps](https://www.google.com/maps/search/?api=1&query=Zugang%20Volkssternwarte%20M%C3%BCnchen%2C%20Ludwig-Jung-Stra%C3%9Fe%2C%20Echarding%2C%20Berg%20am%20Laim%2C%20Munich%2C%20Bavaria%2C%2081671%2C%20Germany)
- OpenStreetMap link: [Search on OpenStreetMap](https://www.openstreetmap.org/search?query=Zugang%20Volkssternwarte%20M%C3%BCnchen%2C%20Ludwig-Jung-Stra%C3%9Fe%2C%20Echarding%2C%20Berg%20am%20Laim%2C%20Munich%2C%20Bavaria%2C%2081671%2C%20Ge …

New: Volkssternwarte München. Public Observatory from Iαη 🍺

---

content/daytrip/as/in/venkatappa-art-gallery.md

**Venue:** Venkatappa Art Gallery
**Location:** Venkatappa Art Gallery, Kasturba Road, Bengaluru, Karnataka, 560001, India
**Submitted by:** Pfft
**Website:** https://archaeology.karnataka.gov.in/page/Government+Museums/Venkatappa+Art+Gallery+Bengaluru/en
Venkatappa Art Gallery came into being with the foundation stone being laid by the then Chief Minister S.Nijalingappa on 24 November 1967. It took a long time to complete. Artists who were frustrated with the delays went on an innovative protest on the footpath in front of Bible Society demanding the gallery space be finished in 1971. Artists included G.S Shenoy, Bhaskar Rao, Ramesh Rao, Acharya and Punam Chattaya. The building was finally completed in 1975
- Google Maps link: [Search on Google …

New: Venkatappa Art Gallery from Pfft

---

content/daytrip/as/in/karnataka-chitrakala-parishath.md

**Venue:** Karnataka Chitrakala Parishath
**Location:** Karnataka Chitrakala Parishath, Kumara Krupa Road, Srikantan Layout, Vasanth Nagar, Bengaluru, Bangalore North, Bengaluru Urban, Karnataka, 560001, India
**Submitted by:** Pfft
**Website:** https://chitrakalaparishath.org/
Karnataka Chitrakala Parishath (Kannada: ಕರ್ನಾಟಕ ಚಿತ್ರಕಲಾ ಪರಿಷತ್) is a visual art complex located in Bangalore. The complex has 18 galleries. 13 of these galleries carry a permanent collection of paintings, sculptures and folk art. The other galleries are rented out for exhibitions of works by artists of repute. The folk art collection showcases Mysore paintings and leather puppets. The Parishat runs the College of Fine Arts, a visual arts college. Each January, the Parishath organizes Chitra Santhe, a cultural …

New: Karnataka Chitrakala Parishath from Pfft

---

content/daytrip/eu/gb/sycamore-gap.md

**Venue:** Sycamore Gap
**Location:** Sycamore Gap, Northumberland, England, NE47 7AL, United Kingdom
**Website:** https://en.wikipedia.org/wiki/Sycamore_Gap_tree
The most famous and photographed tree in the World.
- Google Maps link: [Search on Google Maps](https://www.google.com/maps/search/?api=1&query=Sycamore%20Gap%2C%20Northumberland%2C%20England%2C%20NE47%207AL%2C%20United%20Kingdom)
- OpenStreetMap link: [Search on OpenStreetMap](https://www.openstreetmap.org/search?query=Sycamore%20Gap%2C%20Northumberland%2C%20England%2C%20NE47%207AL%2C%20United%20Kingdom)
**Submission ID:** 580
**File:** `content/daytrip/eu/gb/sycamore-gap.md`

New: Sycamore Gap from AndiBing

---

themes/ndt2/layouts/_default/single.html
themes/ndt2/layouts/partials/repository-link.html

An attempt to fix #827 
Every venue page now has a share button at the top. Press it, and the url (should/will) be copied to your clipboard.
I'm not adding text like "I went to this venue" or "I added this venue" because I always delete that stuff. Just the url, and people can post it anywhere.

[Feature] add a share button to each venue page

---

content/daytrip/eu/gb/fleet-air-arm-museum.md

**Venue:** Fleet Air Arm Museum
**Location:** Fleet Air Arm Museum, RNAS Yeovilton, Somerset, England, BA22 8HT, United Kingdom
**Website:** https://www.nmrn.org.uk/visit-us/fleet-air-arm-museum
Europe's largest naval aviation museum, showing the evolution of the Fleet Air Arm from inception to modern day.
- Google Maps link: [Search on Google Maps](https://www.google.com/maps/search/?api=1&query=Fleet%20Air%20Arm%20Museum%2C%20RNAS%20Yeovilton%2C%20Somerset%2C%20England%2C%20BA22%208HT%2C%20United%20Kingdom)
- OpenStreetMap link: [Search on OpenStreetMap](https://www.openstreetmap.org/search?query=Fleet%20Air%20Arm%20Museum%2C%20RNAS%20Yeovilton%2C%20Somerset%2C%20England%2C%20BA22%208HT%2C%20United%20Kingdom)
**Submission ID:** 583
**File:** …

New: Fleet Air Arm Museum from AndiBing

---

content/daytrip/eu/gb/orkney-wireless-museum.md

**Venue:** Orkney Wireless Museum
**Location:** Orkney Wireless Museum, 1, Junction Road, Kirkwall, Orkney Islands, Scotland, KW15 1LB, UK
**Submitted by:** JohnH
**Website:** https://www.visitscotland.com/info/see-do/orkney-wireless-museum-p251621
spot your first radio set ...
- Google Maps link: [Search on Google Maps](https://www.google.com/maps/search/?api=1&query=Orkney%20Wireless%20Museum%2C%201%2C%20Junction%20Road%2C%20Kirkwall%2C%20Orkney%20Islands%2C%20Scotland%2C%20KW15%201LB%2C%20UK)
- OpenStreetMap link: [Search on OpenStreetMap](https://www.openstreetmap.org/search?query=Orkney%20Wireless%20Museum%2C%201%2C%20Junction%20Road%2C%20Kirkwall%2C%20Orkney%20Islands%2C%20Scotland%2C%20KW15%201LB%2C%20UK)
**Submission ID:** 591
**File:** …

New: Orkney Wireless Museum from JohnH

---

content/daytrip/eu/ie/broom-bridge.md

**Venue:** Broom Bridge
**Location:** Broombridge Road, Dublin, Republic of Ireland
**Website:** https://www.buildingsofireland.ie/buildings-search/building/50060126/broome-bridge-royal-canal-broombridge-road-ballyboggan-south-dublin-7-dublin-city
In 1843, the mathematician Alexander Hamilton was working on extending complex numbers from two to four dimensions. Going on a walk along the Royal Canal to clear his head, he had the core inspiration of how to make them work.
Not having any paper to hand, he scratched the equations onto the side of Broom Bridge.
The original equations are gone, but there remains a plaque on the bridge to commemorate Hamilton's inscription.
- Google Maps link: [Search on Google Maps](https://www.google.com/maps/search/?api=1&query=Broombrid …

New: Broom Bridge from Hugo

---

content/daytrip/eu/gb/samuel-cody-statue.md

**Venue:** Samuel Cody Statue
**Location:** Samuel Cody Statue, RAE Road, Farnborough, Hampshire, England, GU14 6TF, United Kingdom
**Website:** https://www.bbc.co.uk/news/uk-england-hampshire-23591409
Statue to [Samuel Franklin Cody](https://en.wikipedia.org/wiki/Samuel_Franklin_Cody), who was the first person in the UK to pilot a powered, controlled and sustained flight. His flight was in October 1908 and lasted 30 seconds.
- Google Maps link: [Search on Google Maps](https://www.google.com/maps/search/?api=1&query=Samuel%20Cody%20Statue%2C%20RAE%20Road%2C%20Farnborough%2C%20Hampshire%2C%20England%2C%20GU14%206TF%2C%20United%20Kingdom)
- OpenStreetMap link: [Search on OpenStreetMap](https://www.openstreetmap.org/search?query=Samuel%20Cody%20Statue%2C%20RAE%20Roa …

New: Samuel Cody Statue from AndiBing

---

content/daytrip/eu/gb/the-dock-museum.md

**Venue:** The Dock Museum
**Location:** The Dock Museum, Barrow-in-Furness, Westmorland and Furness, England, LA14 2PW, United Kingdom
**Website:** https://dockmuseum.org.uk/
The museum contains galleries exploring the history of the people and industries of the Barrow-in-Furness area.
- Google Maps link: [Search on Google Maps](https://www.google.com/maps/search/?api=1&query=The%20Dock%20Museum%2C%20Barrow-in-Furness%2C%20Westmorland%20and%20Furness%2C%20England%2C%20LA14%202PW%2C%20United%20Kingdom)
- OpenStreetMap link: [Search on OpenStreetMap](https://www.openstreetmap.org/search?query=The%20Dock%20Museum%2C%20Barrow-in-Furness%2C%20Westmorland%20and%20Furness%2C%20England%2C%20LA14%202PW%2C%20United%20Kingdom)
**Submission ID:** 600
**File:** …

New: The Dock Museum from AndiBing

---

content/daytrip/eu/gb/didcot-railway-centre.md

**Venue:** Didcot Railway Centre
**Location:** Didcot Railway Centre,  Didcot, Oxfordshire, England, OX11 7GF, United Kingdom
**Website:** https://didcotrailwaycentre.org.uk/
Museum covering 200 years of railway history.
- Google Maps link: [Search on Google Maps](https://www.google.com/maps/search/?api=1&query=Didcot%20Railway%20Centre%2C%20%20Didcot%2C%20Oxfordshire%2C%20England%2C%20OX11%207GF%2C%20United%20Kingdom)
- OpenStreetMap link: [Search on OpenStreetMap](https://www.openstreetmap.org/search?query=Didcot%20Railway%20Centre%2C%20%20Didcot%2C%20Oxfordshire%2C%20England%2C%20OX11%207GF%2C%20United%20Kingdom)
**Submission ID:** 603
**File:** `content/daytrip/eu/gb/didcot-railway-centre.md`
Please review this venue submission and edit the content as needed …

New: Didcot Railway Centre from AndiBing

---

content/daytrip/eu/gb/reading-museum.md

**Venue:** Reading Museum
**Location:** Reading Museum, Valpy Street, Coley, Reading, England, RG1 1QH, United Kingdom
**Website:** https://www.readingmuseum.org.uk/digital60
Reading Museum is celebrating 60 years since Digital Equipment Corporation (DEC) established it's European headquarters in Reading. The Digital Revolution charts the role of Reading in the development of Technology.
- Google Maps link: [Search on Google Maps](https://www.google.com/maps/search/?api=1&query=Reading%20Museum%2C%20Valpy%20Street%2C%20Coley%2C%20Reading%2C%20England%2C%20RG1%201QH%2C%20United%20Kingdom)
- OpenStreetMap link: [Search on OpenStreetMap](https://www.openstreetmap.org/search?query=Reading%20Museum%2C%20Valpy%20Street%2C%20Coley%2C%20Reading%2C%20England%2C%20RG1%2 …

New: Reading Museum from Stuart Ward

---

content/daytrip/eu/gb/reading-hydro.md

**Venue:** Reading Hydro
**Location:** Caversham Weir, Reading
**Website:** https://readinghydro.org
Reading Hydro is a Archimedes Screw turbine, generating power from the Thames. It was built by the local community with crowdfunding and is now operated by volunteers. If you would like a tour please email visit@readinghydro.org
- Google Maps link: [Search on Google Maps](https://www.google.com/maps/search/?api=1&query=Caversham%20Weir%2C%20Reading)
- OpenStreetMap link: [Search on OpenStreetMap](https://www.openstreetmap.org/search?query=Caversham%20Weir%2C%20Reading)
**Submission ID:** 606
**File:** `content/daytrip/eu/gb/reading-hydro.md`

New: Reading Hydro from Stuart Ward

---

content/daytrip/eu/gb/green-park-wind-turbine.md

**Venue:** Green Park Wind Turbine
**Location:** South Oak Way, Green Park, Reading
**Website:** https://www.ecotricity.co.uk/our-green-energy/green-electricity
Visible to anyone passing through Reading on the M4, the town’s first windmill was built in 2005 under our Merchant Wind Power scheme to provide energy for the office buildings at Green Park. Bringing wind power into urban areas people can witness for themselves how clean, quiet and efficient it is.
- Google Maps link: [Search on Google Maps](https://www.google.com/maps/search/?api=1&query=South%20Oak%20Way%2C%20Green%20Park%2C%20Reading)
- OpenStreetMap link: [Search on OpenStreetMap](https://www.openstreetmap.org/search?query=South%20Oak%20Way%2C%20Green%20Park%2C%20Reading)
**Submission ID:** 607 …

New: Green Park Wind Turbine from Stuart Ward

---

content/daytrip/eu/gb/rlab-reading-hackspace.md

**Venue:** rLab - Reading Hackspace
**Location:** rLab - Reading Hackspace, Weldale Street, Coley, Reading, England, RG1 7PF, United Kingdom
**Website:** https://rlab.org.uk
For makers, menders, re-purposers, creators, sharers and teachers. Come join our group workshop with amazing equipment and members to match.
- Google Maps link: [Search on Google Maps](https://www.google.com/maps/search/?api=1&query=rLab%20-%20Reading%20Hackspace%2C%20Weldale%20Street%2C%20Coley%2C%20Reading%2C%20England%2C%20RG1%207PF%2C%20United%20Kingdom)
- OpenStreetMap link: [Search on OpenStreetMap](https://www.openstreetmap.org/search?query=rLab%20-%20Reading%20Hackspace%2C%20Weldale%20Street%2C%20Coley%2C%20Reading%2C%20England%2C%20RG1%207PF%2C%20United%20Kingdom)
**Submission …

New: rLab - Reading Hackspace from Stuart Ward

---

content/daytrip/eu/gb/region-6-war-room.md

**Venue:** Region 6 War Room
**Location:** Region 6 War Room, Earley Gate, Lower Earley, Earley, Borough of Wokingham, England, RG6 6BU, United Kingdom
**Website:** https://en.wikipedia.org/wiki/Region_6_War_Room
WW2 Era bunker. Now disused, but protected as a grade II listed building. It would have been used by the Regional Commissioner and staff in the event of nuclear attack. 
- Google Maps link: [Search on Google Maps](https://www.google.com/maps/search/?api=1&query=Region%206%20War%20Room%2C%20Earley%20Gate%2C%20Lower%20Earley%2C%20Earley%2C%20Borough%20of%20Wokingham%2C%20England%2C%20RG6%206BU%2C%20United%20Kingdom)
- OpenStreetMap link: [Search on OpenStreetMap](https://www.openstreetmap.org/search?query=Region%206%20War%20Room%2C%20Earley%20Gate%2C%20 …

New: Region 6 War Room from Stuart Ward

---

content/daytrip/na/us/early-television-museum.md

**Venue:** Early Television Museum
**Location:** Early Television Museum, Franklin Street, Hilliard, Franklin County, Ohio, 43026, United States
**Submitted by:** MikeP
**Website:** https://www.earlytelevision.org/
The Early Television Foundation is dedicated to the preservation of the technology from the early days of television. Our mission is to preserve and make available to the public the history of early television, from the mechanical systems of the 1920s through the introduction of color television in the 1950s.
- Google Maps link: [Search on Google Maps](https://www.google.com/maps/search/?api=1&query=Early%20Television%20Museum%2C%20Franklin%20Street%2C%20Hilliard%2C%20Franklin%20County%2C%20Ohio%2C%2043026%2C%20United%20States)
- OpenStreetMap link: [Search on …

New: Early Television Museum from MikeP

---

content/daytrip/oc/au/zigzag-steam-and-rail-motor-railway.md

**Venue:** ZigZag Steam and Rail Motor Railway
**Location:** Chifley Road, Clarence, Lithgow City Council, New South Wales, 2790, Australia
**Website:** https://zigzagrailway.com.au/
The Great Lithgow Zig Zag first opened in 1869 as part of the Western Railway line that linked Sydney with Western New South Wales. This railway line was used to transport people and produce from the western plains of NSW to and from Sydney.
In 1910, a ten tunnel deviation was completed and the Great Lithgow Zig Zag closed and the original formation was declared as a reserve by the Crown. 60 something years later, Zig Zag Railway was born.
Many will remember Zig Zag Railway from their childhood – riding the train in the 70s, 80s or 90s. Come and relive the magic of steam trains and …

New: ZigZag Steam and Rail Motor Railway from popey

---

themes/ndt2/layouts/index.html

This is designed to be the first half of https://github.com/NerdyDayTrips/website/issues/1025
Clicking on the Add link on the front page will put the map's current coordinates into the add.nerdydaytrips.com URL.
The second half is making add.ndt care about these parameters, but that's a different PR.

Append lat/lon/zoom params to the link to add.ndt on front page

---

themes/ndt2/layouts/partials/opengraph.html

The bluesky opengraph scraper appears to require absolute urls rather than relative ones.

Fix bluesky opengraph loading

---

themes/ndt2/layouts/index.html

I think this fixes the "show on map" that venue pages have.

Fix: jumptoslug broke - encoding issues

---

themes/ndt2/assets/css/main.css
themes/ndt2/layouts/_default/item.json.json
themes/ndt2/layouts/index.html

This PR:
* Auto-sizes poups to the content
* Removes the location (address) from the venue popup
* Adds first 200 chars of the venue description to the popup
* Makes the "you are here" location pin larger
* Makes the "You are here!" text in the popup larger
(I pressed the copilot review button by accident, but it's actually quite neat)

Improve venue and 'you are here' popups

---

content/daytrip/eu/de/carl-zeiss-planetarium.md
content/daytrip/eu/de/urwelt-hauff-museum.md
content/daytrip/eu/dk/naturbornholm.md
content/daytrip/eu/fi/suomenlinna.md
content/daytrip/eu/gb/dale-abbey.md
content/daytrip/eu/gb/kisimul-castle.md
content/daytrip/eu/gb/navan-centre-and-fort.md
content/daytrip/eu/ie/derrynane-house.md
content/daytrip/na/ca/st-lawrence-market.md
content/daytrip/na/mx/san-dionisio.md
content/daytrip/sa/co/villa-de-leyva.md

I found a bunch of entries where the `title` was also in the `location` field, which I think we decided is superfluous. So I cleaned them up.

Tidy up entries where title duplicated in location

---

content/daytrip/na/us/blunk-space.md
content/daytrip/na/us/exploreum-science-center.md
content/daytrip/na/us/goodsell-observatory.md
content/daytrip/na/us/juliette.md
content/daytrip/na/us/lettuce-lake-park.md
content/daytrip/na/us/merchant-square-antiques.md
content/daytrip/na/us/montgomery-county-historical-society.md
content/daytrip/na/us/pearson-air-museum.md
content/daytrip/na/us/purgatory-chasm.md
content/daytrip/na/us/ridgefield-wildlife-refuge-river-s-unit.md
content/daytrip/na/us/sedav-vaaki-museum.md
content/daytrip/na/us/smallest-park-in-the-world.md
content/daytrip/na/us/stans-african-halls-permanent-taxidermy-exhibit-at-museum-of-york-county.md
content/daytrip/na/us/the-west-virginia-state-capitol-building.md
content/daytrip/na/us/woodland-ferry.md
content/daytrip/sa/co/villa-de-leyva.md

We're now down to three entries that don't have a URL because I genuinely can't find a suitable web page(*), one mess that needs disentangling still (Libreria Acqua Alta, #400) and one outstanding (British Postal Museum Store) where I'm waiting for a reply from them about whether it's still open to the public (yes, I actually submitted query through their contact form).
(*) East Dundry Lane Viewpoint, Malahide Estuary Tidal Road, the Bear Cage at Pizzone.

Cleanup 3/3: Add missing URLs

---

content/daytrip/eu/gb/wimbledon-windmill.md

**Venue:** Wimbledon Windmill Museum
**Location:** Wimbledon Windmill Museum, Windmill Road, Wimbledon Common, London, SW19 5NR
**Submitted by:** jamesgreenblue 
**Website:** https://www.wimbledonwindmill.org.uk/
Wimbledon Windmill is a Grade II* listed windmill situated on Wimbledon Common preserved as a museum. The museum has exhibits for both young and old, covering windmills and milling as well as local history. A supply of grain is provided so that you can try your hand at the saddle stone, mortar and hand quern.
Access to the museum is free. Parking and tearooms are available nearby.
**File:** `content/daytrip/eu/gb/wimbledon-windmill.md`

New: Wimbledon Windmill Museum from jamesgreenblue
