NerdyDayTrips/website

themes/ndt2/layouts/_default/baseof.html

Adding fontawesome so we can have pretty icons/symbols in pages.

Adds fontawesome for icons

---

content/daytrip/eu/gb/the-watercress-line.md

Testing the auto-generation of pages.

Add the watercress line

---

extract-from-openstreetmap.py

Run `python3 extract-from-openstreetmap.py https://www.openstreetmap.org/node/187104810` to have it create a new entry for that OSM node. Only works for UK stuff at the moment (because I don't know how to find the region, such as "eu", that a country is in).

Add a script to extract a cool feature from openstreetmap

---

config.toml
themes/ndt2/assets/css/main.css
themes/ndt2/layouts/partials/header.html

Makes the menu narrower, so fits better on mobile devices.

Replaces text with icons in menu

---

i18n/en.yaml
themes/ndt2/layouts/blog/list.html
themes/ndt2/layouts/blog/single.html

Adds missing translated texts, and makes the css for blog consistent with about/contact.

Tweak blog css

---

themes/ndt2/layouts/partials/posts.html

Makes the side bar a bit more interesting, and highlights whatever blog posts are recent. Good for sharing announcements of new features or other important information.

add 3 blogs to sidebar

---

themes/ndt2/assets/css/main.css

Gets rid of underlines in the header. Still not perfect, but better.

Remove underline and add shadow

---

config.toml

Adds a link on the header to the add new places form.

add add button

---

content/contact.md

Adds discord link, and update details.

Update contact details

---

extract-from-openstreetmap.py

because big buildings are mapped as ways

Allow osm fetch script to fetch ways as well as nodes

---

extract-from-openstreetmap.py

Fix up OSM script so that it adds current timezone to created dates

Timezone in datestamps

---

content/daytrip/eu/gb/epsom-well-and-spa.md

**Venue:** Epsom Well and Spa
**Location:** Well Way, EPSOM, KT18 7LW
**Website:** https://eehe.org.uk/31208/epsomspa/
The original source of "Epsom Salts" (magnesium sulphate) extraction and spa treatment.
**Submission ID:** 8
**File:** `content/daytrip/eu/gb/epsom-well-and-spa.md`

New: Epsom Well and Spa

---

content/daytrip/eu/gb/computer-history-museum.md

**Venue:** Computer History Museum
**Location:** 1401 N Shoreline Blvd, Mountain View, CA 94043, United States
**Submitted by:** JohnD
**Website:** https://computerhistory.org/
A large and fascinating museum absolutely bursting with tech, right in the heart of Silicon Valley.
A must visit for all computer nerds!
**Submission ID:** 12
**File:** `content/daytrip/eu/gb/computer-history-museum.md`

New: Computer History Museum

---

content/daytrip/eu/gb/clifton-suspension-bridge.md

**Venue:** Clifton Suspension Bridge
**Location:** Bridge Road, Bristol
**Website:** https://cliftonbridge.org.uk
Suspension bridge designed by Isambard Kingdom Brunel, crossing the gorge of the river Avon. Tours of the bridge and of the underground works are available.
**Submission ID:** 25
**File:** `content/daytrip/eu/gb/clifton-suspension-bridge.md`

New: Clifton Suspension Bridge

---

content/daytrip/eu/gb/the-national-museum-of-computing.md

**Venue:** The National Museum of Computing
**Location:** The National Museum of Computing, Block H, Bletchley Park, Milton Keynes MK3 6DS
**Submitted by:** Zymurgic
**Website:** https://www.tnmoc.org/
Collection of computers, calculators and similar technology throughout the ages, including rebuilds of WWII era codebreaking machines.
**Submission ID:** 38
**File:** `content/daytrip/eu/gb/the-national-museum-of-computing.md`

New: The National Museum of Computing

---

content/daytrip/eu/gb/the-eden-project.md

**Venue:** The Eden Project
**Location:** Eden Project, Bodelva, Cornwall, PL24 2SG
**Website:** https://www.edenproject.com
Extensive gardens, in the bowl of an old quarry. A connected series of enclosed domes ("biomes") hold large collections of plants from other climates -- rainforest and the Mediterranean. There is also a permanent exhibit, "Invisible Worlds", about things that are outside the range of our own senses -- too big, too small, too fast, too far away.
**Submission ID:** 40
**File:** `content/daytrip/eu/gb/the-eden-project.md`

New: The Eden Project

---

content/daytrip/eu/fr/gudelon-castle.md

**Venue:** Guédelon Castle
**Location:** D 955 89520 Treigny
**Submitted by:** NAB
**Website:** https://www.guedelon.fr
Guédelon is a 13th-century castle being built from scratch in France using only medieval tools, techniques, and materials. It’s an experimental archaeology project where history, engineering and craftsmanship collide - there are no modern machines, just pure feudal tech.
**Submission ID:** 48
**File:** `content/daytrip/eu/fr/gudelon-castle.md`

New: Guédelon Castle

---

content/daytrip/na/us/infoage-science-center.md

**Venue:** InfoAge Science Center
**Location:** 2201 Marconi Road, Wall, NJ, 07719
**Submitted by:** Topaz
**Website:** https://www.infoage.org/
Multiple small museums about technology, computing, and New Jersey history, complete with a giant radio astronomy dish.
**Submission ID:** 54
**File:** `content/daytrip/na/us/infoage-science-center.md`

New: InfoAge Science Center

---

content/daytrip/eu/gb/hay-on-wye.md

**Venue:** Hay on Wye
**Location:** Hay on Wye, Powys, Wales
**Website:** https://www.hay-on-wye.co.uk
Books. So... many... books. If you don't walk away with a half dozen books on your nerd specialty, you should probably seek medical advice.
**Submission ID:** 56
**File:** `content/daytrip/eu/gb/hay-on-wye.md`

New: Hay on Wye

---

content/daytrip/eu/gb/quarry-bank-mill.md

**Venue:** Quarry Bank Mill
**Location:** Quarry Bank Mill, Styal, Wilmslow, Cheshire, SK9 4HP
**Website:** https://www.nationaltrust.org.uk/visit/cheshire-greater-manchester/quarry-bank
A cotton mill, with working machinery, powered by its original water wheel. There is also the apprentice house, where the children working at the mill were housed, and a museum with comprehensive displays on the history of the mill.
There are also extensive gardens, a Georgian house and a restaurant.
**Submission ID:** 58
**File:** `content/daytrip/eu/gb/quarry-bank-mill.md`

New: Quarry Bank Mill

---

content/daytrip/eu/at/technisches-museum-museum-of-science-and-technology.md

**Venue:** Technisches Museum / Museum of Science and Technology
**Location:** Mariahilfer Straße 212, 1140 Wien
**Submitted by:** same
**Website:** https://www.technischesmuseum.at/
There's a ton of permanent transport, industry and tech exhibits there, plus changing exhibitions, often about currently very relevant topics.
I personally love the collection of household devices, and I enjoy looking at the fridge-sized CPU. I usually stop by the trains, and visit the rescue helicopter on the top floor. 
**Submission ID:** 71
**File:** `content/daytrip/eu/at/technisches-museum-museum-of-science-and-technology.md`

New: Technisches Museum / Museum of Science and Technology

---

config.toml

- Replaces the search icon with a magnifying glass with location.
- Updates the add icon to a circle plus.
- Changes the about icon to a circle information.
- Updates the contact icon to an at symbol.

ui: update menu icons to improve visual clarity and consistency

---

content/daytrip/eu/de/oldenburger-computer-museum.md

**Venue:** Oldenburger Computer Museum
**Location:** Bahnhofsplatz 10, 26122 Oldenburg, Germany
**Website:** https://computermuseum-oldenburg.de/
A huge collection of home computers, gaming consoles, and arcade machines. All machines on display can be used. 
**Submission ID:** 68
**File:** `content/daytrip/eu/de/oldenburger-computer-museum.md`

New: Oldenburger Computer Museum

---

content/daytrip/eu/de/technoseum.md

**Venue:** TECHNOSEUM
**Location:** Museumsstraße 1, 68165 Mannheim
**Submitted by:** wLana
**Website:** https://www.technoseum.de
One of Germany's largest technology museums, with functional exhibits ranging from steam engines to looms, carriages, cars, airplanes, and trains. A journey through the last 200 years of technology of all kinds. Cameras, computer recording equipment, etc., with many interactive and hands-on elements.
**Submission ID:** 85
**File:** `content/daytrip/eu/de/technoseum.md`

New: TECHNOSEUM

---

content/daytrip/eu/at/technisches-museum-museum-of-science-and-technology.md
content/daytrip/eu/de/flugwerft-oberschleiheim.md
content/daytrip/eu/de/heinz-nixdorf-museumsforum.md
content/daytrip/eu/de/konrad-zuse-museum.md

Note to self, fix the add tool so this doesn't happen.

unicode-fixups

---

.envrc
.github/dependabot.yml
.github/workflows/flake-checker.yml
.github/workflows/lock-updater.yml
.gitignore
flake.lock
flake.nix

Introduces a Nix-based development environment for the project.
This includes:
- A `flake.nix` file to define the project's dependencies.
- A `flake.lock` file to lock down the dependency versions.
- A `.envrc` file to enable Nix integration with direnv.
- GitHub Actions workflows for flake checking and lock updating.
- Ignores `.direnv` folder.

feat: add nix development environment

---

content/daytrip/eu/gb/this-museum-is-not-obsolete.md

**Venue:** This Museum is (Not) Obsolete
**Location:** 5-7 Church Hill, Ramsgate CT11 8RA
**Submitted by:** Kevin Taylor
**Website:** https://this-museum-is-not-obsolete.com/
This Museum Is (Not) Obsolete was launched in 2020 by Sam Battle aka "Look Mum No Computer".
Sam is a Musician / Inventor and is the driving force behind the museums mission to keep the ‘obsolete’ alive and evolving for all to experience.
**Submission ID:** 102
**File:** `content/daytrip/eu/gb/this-museum-is-not-obsolete.md`

New: This Museum is (Not) Obsolete

---

content/daytrip/eu/at/mathausen-concentration-camp.md
content/daytrip/eu/be/royal-belgian-institute-of-natural-sciences.md
content/daytrip/eu/be/sint-annatunnel.md
content/daytrip/eu/ch/sattel-hochstuckli.md
content/daytrip/eu/de/aquazoo.md
content/daytrip/eu/de/augusta-treberorum-aka-trier.md
content/daytrip/eu/de/bmw-munich-plant-tour.md
content/daytrip/eu/de/german-pinball-machine-museum.md
content/daytrip/eu/de/meerrettich-museum-baiersdorf.md
content/daytrip/eu/de/meersburg-old-castle.md
content/daytrip/eu/de/phänomenta-flensburg.md
content/daytrip/eu/de/porsche-museum.md
content/daytrip/eu/de/zeche-zollverein.md

For Austria, Belgium, Switzerland, Germany

Charset fixes and URLs

---

content/daytrip/af/gh/elmina-slave-castle.md
content/daytrip/eu/dk/avedøre-airport.md
content/daytrip/eu/dk/fisheries-and-maritime-museum.md
content/daytrip/eu/dk/fjord-bælt.md
content/daytrip/eu/dk/geocenter-møns-klint.md
content/daytrip/eu/dk/hjallerup-mechanical-museum.md
content/daytrip/eu/dk/industrial-museum.md
content/daytrip/eu/dk/knuthenborg-safari-park.md
content/daytrip/eu/dk/museum-of-medical-history.md
content/daytrip/eu/dk/naturbornholm.md
content/daytrip/eu/dk/odense-zoo.md
content/daytrip/eu/dk/open-air-museum.md
content/daytrip/eu/dk/paper-museum-bikuben.md
content/daytrip/eu/dk/post-and-telegraph-museum.md
content/daytrip/eu/dk/skjoldnæsholm-tram-museum.md
content/daytrip/eu/dk/øresund-aquarium.md
content/daytrip/eu/es/burgos.md
content/daytrip/eu/es/laguna-de-gallocanta.md
content/daytrip/eu/es/mercat-de-la-boquerìa.md
content/daytrip/eu/es/military-history-museum.md

Convert \x.. and \u.... quoting to actual unicode (first tranche)

Unicode fixes (part 1)

---

content/daytrip/eu/hr/biograd-na-moru.md
content/daytrip/eu/ie/derrynane-house.md
content/daytrip/eu/ie/fitzgeralds-park.md
content/daytrip/eu/ie/flying-boat-museum.md
content/daytrip/eu/ie/guinness-brewery.md
content/daytrip/eu/ie/malahide-estuary-tidal-road.md
content/daytrip/eu/ie/mullingar.md
content/daytrip/eu/ie/mummies-in-the-crypt.md
content/daytrip/eu/ie/ring-of-kerry-iveragh-peninnsula.md
content/daytrip/eu/ie/sandymount-baths-remains.md
content/daytrip/eu/ie/shenick-island-martello-tower.md
content/daytrip/eu/ie/smugglers-cave.md
content/daytrip/eu/ie/sol-y-sombra-tapas-bar.md
content/daytrip/eu/ie/spike-island.md
content/daytrip/eu/it/elba-island.md
content/daytrip/eu/it/museo-nazionale-dellautomobile.md
content/daytrip/eu/no/52-hverdagsturer-52-nerdy-daily-trips.md
content/daytrip/eu/no/vilvite.md
content/daytrip/eu/pl/wisla-trip.md
content/daytrip/eu/pt/university-of-évora.md

Convert \x.. and \u.... quoting to actual unicode (third tranche)

Unicode fixes

---

content/daytrip/eu/no/norwegian-canning-museum.md

**Venue:** Norwegian Canning Museum
**Location:** Andasmauet 15, 4005 Stavanger, Norway
**Submitted by:** PJ Evans
**Website:** https://www.iddis.no/
Canning! Could it get any more exciting? You’d be surprised. Stavanger’s culture and history is deeply embedded in the fishing and producing of sardines. This museum tells the story of the Canning Factory and its development over the years. It’s in equal parts fascinating and horrifying when you realise the dangers and squalid conditions the worked had to endure. You also get to see the world’s largest sardine tin!!!
**Submission ID:** 89
**File:** `content/daytrip/eu/no/norwegian-canning-museum.md`

New: Norwegian Canning Museum from PJ Evans

---

content/daytrip/eu/gb/international-mill-museum-gifhorn.md

**Venue:** International Mill Museum Gifhorn
**Location:** Bromer Straße 2, 38518 Gifhorn, Germany
**Website:** https://www.muehlen-museum-gifhorn.de/
A collection of wind- and water-mills from different countries. In addition to originals and full size working reproductions, the museum also has a collection of models and additional historic buildings. 
**Submission ID:** 100
**File:** `content/daytrip/eu/gb/international-mill-museum-gifhorn.md`

New: International Mill Museum Gifhorn from MarcN

---

content/daytrip/eu/gb/phaeno.md

**Venue:** phaeno
**Location:** Willy-Brandt-Platz 1, 38440 Wolfsburg, Germany
**Website:** https://www.phaeno.de/
A hands-on science museum located in a very interesting building by famous architect Zaha Hadid. Fun for children and adults. 
**Submission ID:** 101
**File:** `content/daytrip/eu/gb/phaeno.md`

New: phaeno from MarcN

---

content/daytrip/eu/gb/national-film-and-sci-fi-museum.md

**Venue:** National Film and Sci-Fi Museum
**Location:** 34 Secklow Gate W, Milton Keynes MK9 3AT
**Submitted by:** Kevin Taylor
**Website:** https://nationalfilmandscifimuseum.com/
From the FAQ: "The National Film & Sci-Fi Museum is dedicated to the preservation, restoration and exhibition of the art, skills and dedication that goes into delivering some of the world’s most successful films and tv shows. It has a series of dedicated displays of genuine and replica props and memorabilia from across all genres of Film & Sci-Fi."
**Submission ID:** 103
**File:** `content/daytrip/eu/gb/national-film-and-sci-fi-museum.md`

New: National Film and Sci-Fi Museum from Kevin Taylor

---

content/daytrip/na/ca/flying-saucer-restaurant.md

**Venue:** Flying Saucer Restaurant
**Location:** 6768 Lundy's Lane, Niagara Falls, Ontario, Canada
**Website:** https://flyingsaucerrestaurant.com/
An American-style diner shaped like a UFO! Well, the roof is UFO shaped and the interior is similarly themed. Basic but decent food, and if you're nearby to see Niagara Falls anyway...
**Submission ID:** 109
**File:** `content/daytrip/na/ca/flying-saucer-restaurant.md`

New: Flying Saucer Restaurant from Paul Drye

---

content/daytrip/eu/es/submarine-safaris-lanzarote.md

**Venue:** Submarine Safaris Lanzarote
**Location:** Carr. Puerto Calero, n, 35571 Puerto Calero, Lanzarote, Spain
**Website:** https://www.submarinesafaris.com/
A one hour submarine ride in up to 30 meters depth. 
**Submission ID:** 110
**File:** `content/daytrip/eu/es/submarine-safaris-lanzarote.md`

New: Submarine Safaris Lanzarote from MarcN

---

content/daytrip/eu/nl/naturalis-museum-of-natural-history.md

**Venue:** Naturalis - Museum of Natural History
**Location:** Darwinweg 2, 2333 CR Leiden
**Website:** https://www.naturalis.nl/en/museum
Research institute and museum of natural history with an extensive collection, crowned by objects such as the third most complete Tyrannosaur Rex skeleton in the world (Trix), the world's first herd of Triceratops, a collection of meteorites and much more over the 9 floors of the museum. As this is an active research centre, there is also a floor dedicated to current research.
**Submission ID:** 120
**File:** `content/daytrip/eu/nl/naturalis-museum-of-natural-history.md`

New: Naturalis - Museum of Natural History from TimoMicro

---

content/daytrip/eu/de/gedenksttte-deutsche-teilung-marienborn.md

**Venue:** Gedenkstätte Deutsche Teilung Marienborn
**Location:** Autobahn 2, 39365 Harbke, Germany
**Website:** https://gedenkstaette-marienborn.sachsen-anhalt.de/
The Memorial of the Division of Germany is located on the grounds of one of the largest former border crossings between East and West Germany. It features exhebitions and guided tours which illustrate the great efforts made by the East German border authorities. 
**Submission ID:** 121
**File:** `content/daytrip/eu/de/gedenksttte-deutsche-teilung-marienborn.md`

New: Gedenkstätte Deutsche Teilung Marienborn from MarcN

---

content/daytrip/as/jp/toyota-commemorative-museum-of-industry-and-technology.md

**Venue:** Toyota Commemorative Museum of Industry and Technology
**Location:**  4 Chome-1-35 Noritakeshinmachi, Nishi Ward, Nagoya, Aichi 451-0051, Japan
**Website:** https://www.tcmit.org/english
A museum on the site where the Toyota company was founded. It goes from the company's beginnings as a loom and textile company through the the present day as a manufacturer of electric vehicles. 
Interesting highlights for me were: a jacquard loom; robot musicians; a humongous hydraulic press that you can 'operate' with the press of a button; a recreation of a robotic assembly line; Toyota's first truck and car. 
It is resonably close to JR Nagoya station. 
**Submission ID:** 123
**File:** `content/daytrip/as/jp/toyota-commemorative-museum-of-industry-and-technology.md …

New: Toyota Commemorative Museum of Industry and Technology from Shiawase

---

content/daytrip/eu/de/multimar-wattforum.md

**Venue:** Multimar Wattforum
**Location:** Dithmarscher Straße 6a, 25832 Tönning, Germany
**Website:** https://multimar-wattforum.de/
Exhibition about the wildlife of the Schleswig Holstein Wadden Sea National Park and the tides. 
**Submission ID:** 127
**File:** `content/daytrip/eu/de/multimar-wattforum.md`

New: Multimar Wattforum from MarcN

---

content/daytrip/eu/de/german-maritime-museum.md

**Venue:** German Maritime Museum
**Location:** Hans-Scharoun-Platz 1, 27568 Bremerhaven, Germany
**Website:** https://www.dsm.museum/
Maritime museum with the wreck of a 14th century medieval merchant ship as the center piece. The museum is located next to the museum harbor. 
**Submission ID:** 132
**File:** `content/daytrip/eu/de/german-maritime-museum.md`

New: German Maritime Museum from MarcN

---

content/daytrip/eu/gb/the-london-mithraeum.md

**Venue:** The London Mithraeum
**Location:** 12 Walbrook London, EC4N 8AA
**Submitted by:** GeorgeL
**Website:** https://www.londonmithraeum.com/
Fascinating Roman ruins underneath a modern office block. Surreal, very well presented, shrine of a 2000-year-old cult. Perfect nerd trip, I loved it.
**Submission ID:** 136
**File:** `content/daytrip/eu/gb/the-london-mithraeum.md`

New: The London Mithraeum from GeorgeL

---

content/daytrip/eu/gb/bletchley-park.md

**Venue:** Bletchley Park
**Location:** The Mansion, Bletchley Park, Sherwood Dr, Bletchley, Milton Keynes MK3 6EB
**Submitted by:** PJ Evans
**Website:** https://bletchleypark.org.uk
Home of the secret World War II codebreakers. Learn the stories of this operation that not only broke Enigma, but led to a technical revolution that gave us the computer revolution and also played a major role in defeating Hitler’s forces. As well as exhibitions telling the story, you can also visit the huts and blocks where they worked. An essential visit for any security geek and is next door to the amazing National Museum of Computing.
**Submission ID:** 88
**File:** `content/daytrip/eu/gb/bletchley-park.md`

New: Bletchley Park from PJ Evans

---

content/daytrip/eu/at/archeo-norico-castle-museum-deutschlandsberg.md

**Venue:** Archeo Norico – castle museum Deutschlandsberg
**Location:** Burgplatz 2, 8530 Deutschlandsberg
**Submitted by:** same
**Website:** https://www.archeonorico.at/index.php/de/das-museum
It's a largely archaeological museum in a castle. But what I enjoyed the most was the collection of glassware. 
**Submission ID:** 82
**File:** `content/daytrip/eu/at/archeo-norico-castle-museum-deutschlandsberg.md`

New: Archeo Norico – castle museum Deutschlandsberg from same

---

content/daytrip/eu/gb/seaton-tramway.md

**Venue:** Seaton Tramway
**Location:**  Seaton Tramway, Harbour Road, Seaton, Devon EX12 2NQ
**Submitted by:** Peter L
**Website:** https://www.tram.co.uk/
Trams - along the route of an old branch line.
You can even drive one. https://www.youtube.com/watch?v=zGMHDrf-WC0
They stop for people to go bird watching.
Colyton café serves remarkably good sandwiches.
As a nerd, this was a rather fine day out.
**Submission ID:** 141
**File:** `content/daytrip/eu/gb/seaton-tramway.md`

New: Seaton Tramway from Peter L

---

content/daytrip/eu/es/palmetum.md

**Venue:** palmetum
**Location:** Avda. de la Constitución,5  38005, Santa Cruz de Tenerife, Spain
**Website:** https://palmetumtenerife.es/
A 12-hectare botanical garden that specialises in palm trees.
**Submission ID:** 147
**File:** `content/daytrip/eu/es/palmetum.md`

New: palmetum from MarcN

---

themes/ndt2/assets/css/main.css
themes/ndt2/layouts/partials/posts.html

It says shrinky, but it's actually longer. More of the more recent things, smaller fonts etc.

Better formatting sidebar

---

content/daytrip/na/us/prehistoric-gardens.md

**Venue:** Prehistoric Gardens
**Location:** 37001-37005 Arizona Ranch Rd, Port Orgord, OR 97465
**Submitted by:** Dean Franklin
**Website:** http://www.prehistoricgardens.com
Roadside attraction with dinosaur models set in a coastal temperate rainforest.
**Submission ID:** 152
**File:** `content/daytrip/na/us/prehistoric-gardens.md`

New: Prehistoric Gardens from Dean Franklin

---

content/daytrip/na/us/the-nethercutt-collection-.md

**Venue:** The Nethercutt Collection 
**Location:** 15151 Bledsoe St Sylmar, CA 91342 United States
**Submitted by:** Charley Dunn
**Website:** https://nethercuttcollection.org/
An amazing collection of antique automobiles. Private tour includes antique furniture and operational automated mechanical musical instruments including orchestrions 
**Submission ID:** 153
**File:** `content/daytrip/na/us/the-nethercutt-collection-.md`

New: The Nethercutt Collection  from Charley Dunn

---

content/daytrip/eu/gb/science-museum.md

**Venue:** Science Museum
**Location:** Exhibition Road, South Kensington, London SW7 2DD
**Website:** https://www.sciencemuseum.org.uk/
Large museum of Science and Technology with galleries themed around engineering, steam power, space exploration, flight, medicine, video games, and information technology.
**Submission ID:** 160
**File:** `content/daytrip/eu/gb/science-museum.md`

New: Science Museum from TimoMicro

---

.gitignore

Add emacs backup files to .gitignore

---

content/daytrip/eu/at/mathausen-concentration-camp.md

Fix the name of the URL metadata element

---

content/daytrip/na/ca/stones-n-bones-museum.md

**Venue:** Stones 'N Bones Museum
**Location:** 223 Christina Street North, Sarnia, Ontario, Canada
**Website:** http://www.stonesnbones.ca/
A private natural history museum with minerals, texidermied animals, and dinosaur fossils. Small and doesn't look like much from outside, but jammed full of exhibits.
**Submission ID:** 169
**File:** `content/daytrip/na/ca/stones-n-bones-museum.md`

New: Stones 'N Bones Museum from Paul Drye

---

content/daytrip/na/ca/the-donkey-sanctuary-of-canada.md

**Venue:** The Donkey Sanctuary of Canada
**Location:** 6981 Concession 4, Puslinch, Ontario, Canada
**Website:** https://www.thedonkeysanctuary.ca/
A sanctuary farm for rescued donkeys. Some are quite friendly and yes, you can give them scritches through the paddock fence.
Open to the public on most Sundays from the first Sunday in May to the last Sunday in October, as well as some days during the December  holiday season. Tickets in advance are recommended.
**Submission ID:** 174
**File:** `content/daytrip/na/ca/the-donkey-sanctuary-of-canada.md`

New: The Donkey Sanctuary of Canada from Paul Drye

---

content/daytrip/eu/gb/castle-campbell.md
content/daytrip/eu/gb/castle-carr.md
content/daytrip/eu/gb/church-of-saint-peter-on-the-wall.md
content/daytrip/eu/gb/crinan-canal.md

Mostly just minor tweaks to location

Update URLs, addresses and locations

---

content/daytrip/eu/hr/nikola-tesla-technical-museum.md

**Venue:** Nikola Tesla Technical Museum
**Location:** Savska cesta 18 10000 Zagreb, Croatia
**Submitted by:** edent
**Website:** https://tmnt.hr/hr-hr/
Lots of technology exhibits. Mostly related to Croatia. Many industrial age engines. Good exhibit on Tesla.
**Submission ID:** 183
**File:** `content/daytrip/eu/hr/nikola-tesla-technical-museum.md`

New: Nikola Tesla Technical Museum from edent

---

content/daytrip/eu/ie/national-transport-museum.md

**Venue:** National Transport Museum
**Location:** National Transport Museum, Howth Road, Ben Eadair A ED, Howth, Fingal, County Dublin, Leinster, D13 DH52, Ireland
**Submitted by:** Nerd
**Website:** http://www.nationaltransportmuseum.org/
National Transport Museum of Ireland
**Submission ID:** 189
**File:** `content/daytrip/eu/ie/national-transport-museum.md`

New: National Transport Museum from Nerd

---

content/daytrip/eu/gde/bayerische-staatsbrauerei-weihenstephan.md

**Venue:** Bayerische Staatsbrauerei Weihenstephan
**Location:** Alte Akademie 2, 85354 Freising, Germany
**Website:** https://www.weihenstephaner.de/en
The oldest brewery in the world, brewing beer since 1040 and now exporting world wide and home to one of the most famous Weißbier in the world. The campus around the brewery now has a food research department of the TU Münich.
**Submission ID:** 196
**File:** `content/daytrip/eu/gde/bayerische-staatsbrauerei-weihenstephan.md`

New: Bayerische Staatsbrauerei Weihenstephan from TimoMicro

---

content/daytrip/eu/hr/video-game-history-museum.md

**Venue:** Video Game History Museum
**Location:** Draškovićeva ul. 10, 10000, Zagreb, Croatia
**Submitted by:** edent
**Website:** https://vghm.hr/
History of games consoles and computers. Many interactive exhibits including original cabinets, MAME emulators, and consoles.
**Submission ID:** 198
**File:** `content/daytrip/eu/hr/video-game-history-museum.md`

New: Video Game History Museum from edent

---

README.md

Just some minor tweaks to the readme.

One error and one re-wording

---

content/daytrip/eu/gb/worcester-cathedral.md

**Venue:** Cathedral Church of Christ and the Blessed Mary
**Location:** Cathedral Church of Christ and the Blessed Mary, the Virgin of Worcester, College Yard, Diglis, Worcester, Worcestershire, England, WR1 2LA, United Kingdom
**Website:** https://www.worcestercathedral.org.uk/
Worcester Cathedral is absolutely stunning - a proper medieval masterpiece perched right on the River Severn with King John's tomb and some cracking Norman architecture. The mix of styles from Norman to Gothic works brilliantly, and that cloister is genuinely impressive. 
It's well worth a visit if you're in the area, especially for the spectacular medieval stained glass. 
**Submission ID:** 208
**File:** `content/daytrip/eu/gb/worcester-cathedral.md`
Please review this venue submission …

New: Cathedral Church of Christ and the Blessed Mary from popey

---

content/daytrip/eu/de/psspeicher.md

**Venue:** PS.SPEICHER
**Location:** PS.SPEICHER, 3, Tiedexer Tor, Einbeck, Landkreis Northeim, Niedersachsen, 37574, Deutschland
**Website:** https://www.ps-speicher.de/
Europe's largest museum of classic vehicles. The collection includes nerd favorites like a DeLorean and the Sinclair C5.
**Submission ID:** 215
**File:** `content/daytrip/eu/de/psspeicher.md`

New: PS.SPEICHER from MarcN

---

content/daytrip/eu/de/deutsches-museum.md

**Venue:** Deutsches Museum
**Location:** Deutsches Museum, 1, Museumsinsel, Deutsches Museum, Ludwigsvorstadt-Isarvorstadt, München, Bayern, 80538, Deutschland
**Website:** https://www.deutsches-museum.de/
Probably the best German museum on technology and science. 
**Submission ID:** 224
**File:** `content/daytrip/eu/de/deutsches-museum.md`

New: Deutsches Museum from MarcN

---

content/daytrip/eu/de/sea-life.md

**Venue:** Sea Life
**Location:** Sea Life, 4a, Herrenhäuser Straße, Herrenhausen, Herrenhausen-Stöcken, Hannover, Region Hannover, Niedersachsen, 30419, Deutschland
**Website:** https://www.visitsealife.com/hannover/en/
Aquarium and tropical house. 
**Submission ID:** 227
**File:** `content/daytrip/eu/de/sea-life.md`

New: Sea Life from MarcN

---

content/daytrip/eu/it/capuchin-crypt.md

**Venue:** Capuchin Crypt
**Location:** Via Vittorio Veneto 27, Ludovisi, Municipio Roma I, Rom, Roma Capitale, Latium, 00187, Italy
**Website:** https://museoecriptacappuccini.it/en/the-crypt/
The crypt is decorated with skulls and bones. Impressive but not for the faint of heart. 
**Submission ID:** 231
**File:** `content/daytrip/eu/it/capuchin-crypt.md`

New: Capuchin Crypt from MarcN

---

content/daytrip/eu/de/miniatur-wunderland.md

**Venue:** Miniatur Wunderland
**Location:** Kehrwieder 2-4, 20457 Hamburg, Germany
**Submitted by:** pesco
**Website:** https://www.miniatur-wunderland.com/
A giant landscape of working model railroads, cars, airplanes, tons of custom miniatures, etc. One of the nerdiest places on earth.
**Submission ID:** 235
**File:** `content/daytrip/eu/de/miniatur-wunderland.md`

New: Miniatur Wunderland from pesco

---

content/daytrip/as/in/baps-shri-swaminarayan-mandir.md

**Venue:** BAPS Shri Swaminarayan Mandir
**Location:** BAPS Shri Swaminarayan Mandir, Akshardham Complex, Swami Vivekanand Road, Chanakya Nagar, P/N Ward, Zone 4, Mumbai, Maharashtra, 400067, India
**Website:** https://www.baps.org/
Second-largest Hindu temple complex in the world.  Open to the public.  Fountains, sculptures, magnificent architecture. Also has cafeteria and gift shop.
**Submission ID:** 238
**File:** `content/daytrip/as/in/baps-shri-swaminarayan-mandir.md`

New: BAPS Shri Swaminarayan Mandir from Mark Dominus

---

content/daytrip/na/us/air-mobility-command-museum.md

**Venue:** Air Mobility Command Museum
**Location:** Air Mobility Command Museum, 1301, Heritage Road, Dover, Kent County, Delaware, 19902, United States
**Website:** https://www.amcmuseum.org/
This is the nerdiest museum I have ever been to.  It's a museum about Air Force logistics.
There are many historical transport and cargo planes on display.  You can get a guided tour and walk around in the planes that are used to transport tank weapons cross the world.  There is an exhibit about the Berlin Airlift, which supplied Berlin with food and fuel for 15 months during the Soviet blockade of the city after World War 2.  There are also interesting oddities such as a howitzer-in-a-box that could be airdropped to advancing infantry positions.
**Submission ID:** …

New: Air Mobility Command Museum from Mark Dominus

---

content/daytrip/na/us/ben-franklin-house.md

The one described previously was a hotel known as "Ben Franklin House"

Correct location of Benjamin Franklin house and museum

---

content/daytrip/na/us/museum-of-jurassic-technology.md

**Venue:** Museum of Jurassic Technology
**Location:** Museum of Jurassic Technology, 9341, Venice Boulevard, Downtown Culver City, Culver City, Los Angeles County, California, 90232, United States
**Website:** https://www.mjt.org/themainpage/main2.html
This baffling museum has nothing to do with dinosaurs and defies explanation.
Come look at the baffling exhibits, then hang out in the roof garden, eat cookies with the doves, and listen to the founder play the nyckelharpa.
**Submission ID:** 263
**File:** `content/daytrip/na/us/museum-of-jurassic-technology.md`

New: Museum of Jurassic Technology from Mark Dominus

---

themes/ndt2/layouts/_default/rss.xml

Fix empty blog rss

---

content/daytrip/eu/mt/mdina.md

**Venue:** Mdina
**Location:** Mdina, Triq Inguanez, Sqaq Nru. 1, Mdina, Northern Region, MDN 1011, Malta
**Submitted by:** Stuart Langridge
**Website:** https://www.visitmalta.com/en/info/mdina-malta-old-capital/
Mdina. The Silent City. If you’re into history, it’s a very well preserved fortified city which has been inhabited continuously since before written records, and has many fine examples of baroque architecture dating from when it was the capital of Malta in the mediaeval period and later into the era of the knightly Order of St. John. If you’re more the computer game sort of nerd… it’s what every Assassins Creed level dreams of being when it grows up. The temptation to look for Indiana Jones-style secret doorways in statues and the like is almost irresistible. 
Easily accessible …

New: Mdina from Stuart Langridge

---

content/daytrip/eu/mt/national-museum-of-archaeology.md

**Venue:** National Museum of Archaeology
**Location:** National Museum of Archaeology, Republic Street, Strada Rjali, Valletta, South Eastern Region, VLT 1113, Malta
**Submitted by:** Stuart Langridge
**Website:** https://heritagemalta.mt/explore/national-museum-of-archaeology/
Divided into three parts: the Neolithic period, the Phoenician, and the Bronze Age. The Neolithic part has many well preserved prehistoric artefacts, as well as the actual stones from the temples at Tarxian, carved with flint tools into spirals and representations of animals. They have an audio guide which you can open as a website on your phone and provide a good explanation of some of the history which isn’t written on the cards, so take your headphones. (https://nma.myvisit.live/langlist)
**Submission ID:** 268 …

New: National Museum of Archaeology from Stuart Langridge

---

themes/ndt2/layouts/index.html

It needs more testing and a better icon that doesn't suck.

Hide cluster f button for now

---

content/daytrip/eu/gb/the-hat-works.md

**Venue:** The Hat Works
**Location:** Wellington Mill, Wellington Rd S, Stockport SK3 0EU
**Submitted by:** ant
**Website:** https://www.stockport.gov.uk/topic/hat-works
Learn how hats were made and what made hatters "mad"
**Submission ID:** 271
**File:** `content/daytrip/eu/gb/the-hat-works.md`

New: The Hat Works from ant

---

content/daytrip/na/us/connections-museum-seattle.md

This is a telecommunications museum located in a portion of a working telephone company central office in Seattle, Washington, United States.

Add Connections Museum Seattle

---

content/daytrip/eu/de/alte-sternwarte-tbingen.md

**Venue:** Alte Sternwarte Tübingen
**Location:** Sternwarte, Waldhäuser Str., 72076 Tübingen
**Submitted by:** Tim Süberkrüb
**Website:** https://uni-tuebingen.de/fakultaeten/mathematisch-naturwissenschaftliche-fakultaet/fachbereiche/physik/institute/astronomie-und-astrophysik/astronomie-hea/einrichtungen/observatorium/die-alte-sternwarte/
The Old Observatory (Alte Sternwarte) offers weekly Friday night sky tours from late September onward, weather permitting. These tours are conducted with great passion by local astronomy enthusiasts, and admission fees are very affordable.
**Submission ID:** 283
**File:** `content/daytrip/eu/de/alte-sternwarte-tbingen.md`

New: Alte Sternwarte Tübingen from Tim Süberkrüb

---

content/daytrip/eu/de/bmw-museum.md

**Venue:** BMW Museum
**Location:** Am Olympiapark 2, 80809 München, Germany
**Website:** https://www.bmw-welt.com/
The technical development of BMW is presented from the past to the present and into the future. On display are engines and turbines, aeroplanes, motorbikes and vehicles in a wide range of variations.
**Submission ID:** 287
**File:** `content/daytrip/eu/de/bmw-museum.md`

New: BMW Museum from MarcN

---

content/daytrip/eu/de/walchenseekraftwerk.md

Fix the slug/filename of Walchenseekraftwerk

---

content/daytrip/eu/nl/national-military-museum.md

**Venue:** National Military Museum
**Location:**  Verlengde Paltzerweg 1, 3768 MX, Soest, The Netherlands     
**Website:** https://www.nmm.nl/en/
Museum about the history of the Dutch armed forces, with a lot of military hardware on display. Located on a old airfield. If open: try to visit the ABC bunkers (Atomic, Biological, Chemical)
**Submission ID:** 299
**File:** `content/daytrip/eu/nl/national-military-museum.md`

New: National Military Museum from Frederik Dekker

---

content/daytrip/eu/nl/teylers-museum.md

**Venue:** Teylers Museum
**Location:** Spaarne 16, 2011 CH Haarlem, The Netherlands
**Website:** https://teylersmuseum.nl/en
The oldest museum in the Netherlands with a focus on both art and science.
**Submission ID:** 303
**File:** `content/daytrip/eu/nl/teylers-museum.md`

New: Teylers Museum from Frederik Dekker

---

content/daytrip/eu/nl/safari-ship-de-blauwe-bever.md

**Venue:** Safari ship "de Blauwe Bever'
**Location:** Various starting points (see website)
**Website:** https://deblauwebever.nl/
Educational wildlife sailing tours on a ship run by volunteers.
**Submission ID:** 307
**File:** `content/daytrip/eu/nl/safari-ship-de-blauwe-bever.md`

New: Safari ship "de Blauwe Bever' from Frederik Dekker

---

content/daytrip/eu/gb/conisbrough-castle.md

**Venue:** Conisbrough Castle
**Location:** Conisbrough Castle, Castle Hill, Conanby, Conisbrough, Doncaster, South Yorkshire, England, DN12 3BU, United Kingdom
**Submitted by:** Robin
**Website:** https://www.english-heritage.org.uk/visit/places/conisbrough-castle/
An old castle, the keep is still in good condition.
**Submission ID:** 309
**File:** `content/daytrip/eu/gb/conisbrough-castle.md`

New: Conisbrough Castle from Robin

---

content/daytrip/na/us/duquesne-upper-station.md

**Venue:** Duquesne Upper Station
**Location:** Duquesne Upper Station, 1220, Grandview Avenue, Mount Washington, Pittsburgh, Allegheny County, Pennsylvania, 15211, United States
**Website:** https://www.duquesneincline.org/
The Duquesne Incline is a funicular system that has been hauling people up and down Duquesne heights since 1877.  The machinery that makes it work is on display.  Where does the cable go?  What will happen if it breaks?  
When they built the incline, they wanted to build the power house with the engines an a straight line with the rest of the track.  But they couldn't get the land across Grandville Avenue.  So the cables have to make a right-angle turn at the top of the hill!
And the view from the top is great.
**Submission ID:** 311 …

New: Duquesne Upper Station from Mark Dominus

---

content/daytrip/eu/nl/de-spelerij-en-de-uitvinderij-the-playground-and-the-invention.md

**Venue:** De Spelerij en de Uitvinderij (the Playground and the Invention)
**Location:** Veldweg 5, 6952 GX, Dieren, The Netherlands
**Website:** https://www.spelerij.nl/
The Playground: special playground with unusual equipment designed to invite collaboration and imagination.
The Invention: big workshop and makerspace where children can make things themselves (under supervision).
For children and parents.
**Submission ID:** 327
**File:** `content/daytrip/eu/nl/de-spelerij-en-de-uitvinderij-the-playground-and-the-invention.md`

New: De Spelerij en de Uitvinderij (the Playground and the Invention) from Frederik Dekker

---

content/daytrip/eu/gb/the-treehouse-board-game-cafe.md

**Venue:** The Treehouse Board Game Cafe
**Location:** The Treehouse board game cafe 41 Boston Street, Sheffield, S2 4QF
**Submitted by:** GlennF
**Website:** https://www.treehousesheffield.com
The Treehouse is Sheffield's first board game café - it's this really cool, laid-back place where you can try out games from their massive collection of over 800 titles. Whether you've never touched a board game or you're already obsessed, the staff there are brilliant at helping you find something fun and explaining how everything works.
They've also got a great drinks menu with craft beers on tap, cocktails, milkshakes, and really good coffee, plus food that's made with ingredients from local suppliers around Sheffield. It's just a really welcoming spot for anyone who wants to hang out and play …

New: The Treehouse Board Game Cafe from GlennF

---

content/daytrip/eu/se/museum-of-artistic-process-and-public-art.md

**Venue:** Museum of Artistic Process and Public Art
**Location:** Finngatan 2, 223 62 Lund
**Submitted by:** magnus
**Website:** https://skissernasmuseum.se/en/
Skissernas Museum – Museum of Artistic Process and Public Art is a unique art museum that focuses on the artistic creative process. It features the world’s largest collection of sketches, models and preparatory work for Swedish and international public art.
**Submission ID:** 334
**File:** `content/daytrip/eu/se/museum-of-artistic-process-and-public-art.md`

New: Museum of Artistic Process and Public Art from magnus

---

content/daytrip/eu/gb/birmingham-city-centre-gardens.md
content/daytrip/eu/gb/birmingham-indoor-market.md
content/daytrip/eu/gb/birmingham-museum-art-gallery.md
content/daytrip/eu/gb/black-sabbath-bridge.md
content/daytrip/eu/gb/boulton-watt-murdoch-statue.md
content/daytrip/eu/gb/cathedral-church-of-saint-philip.md
content/daytrip/eu/gb/chamberlain-clock.md
content/daytrip/eu/gb/library-of-birmingham.md
content/daytrip/eu/gb/queen-victoria.md
content/daytrip/eu/gb/st-martins.md
content/daytrip/eu/gb/the-birmingham-man.md
content/daytrip/eu/gb/the-pen-museum.md
content/daytrip/eu/gb/waylands-forge.md

Add "poster" for Stuart's additions around Brum, before we had the "add" page.

Attribution fix for Stuart

---

content/daytrip/eu/nl/dwingeloo-radiotelescope.md

Fix spelling of Dwingeloo

---

content/daytrip/eu/de/designpanoptikum.md

Add Designpanoptikum, Berlin

---

content/daytrip/na/us/national-watch-and-clock-museum.md

**Venue:** National Watch and Clock Museum
**Location:** 514 Poplar Street, Columbia, PA, USA
**Submitted by:** Michael Wood
**Website:** https://museum.nawcc.org/
A really cool watch and clock museum.
**Submission ID:** 363
**File:** `content/daytrip/na/us/national-watch-and-clock-museum.md`

New: National Watch and Clock Museum from Michael Wood

---

content/daytrip/na/us/mmuseumm.md

**Venue:** Mmuseumm
**Location:** Mmuseumm, 4, Cortlandt Alley, Civic Center, Manhattan, New York County, New York, 10013, United States
**Submitted by:** fancybone
**Website:** https://www.mmuseumm.com/
Arguably the world's smallest museum, this is also located in one of the very few actual alleys in New York City. The size of a small garage, even when the museum is closed, exhibits can be viewed through a small window in the door.
**Submission ID:** 364
**File:** `content/daytrip/na/us/mmuseumm.md`

New: Mmuseumm from fancybone

---

content/daytrip/na/us/boone-scenic-valley-railroad.md

**Venue:** Boone & Scenic Valley Railroad
**Location:** Boone & Scenic Valley Railroad
**Submitted by:** RadagastTheNerd
**Website:** https://bsvrr.com/
Tourist railroad that operates steam locomotives on the weekends. They run historic diesel locomotives on weekdays.
Attached museum has lots of artifacts from all eras of railroading.
**Submission ID:** 365
**File:** `content/daytrip/na/us/boone-scenic-valley-railroad.md`

New: Boone & Scenic Valley Railroad from RadagastTheNerd

---

content/daytrip/eu/de/industriemuseum-region-teltow-e-v.md

**Venue:** Industriemuseum Region Teltow e. V.
**Location:** Oderstraße 23-25, 14513 Teltow, Germany
**Website:** https://imt-museum.de/
Museum of the local industrial heritage. With exhibitions on infrastructure (Teltow canal), electronics, automation, communication, chemical industry. Many devices produced in the GDR are on display.
**Submission ID:** 369
**File:** `content/daytrip/eu/de/industriemuseum-region-teltow-e-v.md`

New: Industriemuseum Region Teltow e. V. from debb1046

---

content/daytrip/na/us/university-of-alaska-museum-of-the-north.md

**Venue:** University of Alaska Museum of the North
**Location:** University of Alaska Museum of the North, 1962, Yukon Drive, Fairbanks, Fairbanks North Star Borough, Alaska, 99775, United States
**Submitted by:** Ellen
**Website:** https://www.uaf.edu/museum/
Stylish building filled with Alaska-related exhibits: geological specimens, animals, Native artifacts, ancient skeletons, paintings... perfect for getting out of the chilly weather for several hours but continuing to enjoy Alaska and feed your brain. A must-add to one of your upcoming Fairbanks itineraries.
**Submission ID:** 370
**File:** `content/daytrip/na/us/university-of-alaska-museum-of-the-north.md`

New: University of Alaska Museum of the North from Ellen

---

content/daytrip/eu/es/cosmocaixa.md

**Venue:** Cosmocaixa
**Location:** Cosmocaixa, Carrer del Cister, Sant Gervasi - la Bonanova, Sarrià - Sant Gervasi, Barcelona, Barcelonès, Barcelona, Catalonia, 08022, Spain
**Submitted by:** Sam D
**Website:** https://cosmocaixa.org/
Multistory environment, nature, science, and space museum on the outskirts of the city. Great option if you have kids. On the bottom floor of the museum there is a "flooded forest" section which replicates the climate of the amazon rainforest, and houses many of the unique species from that climate including caimans & a capybara.
**Submission ID:** 375
**File:** `content/daytrip/eu/es/cosmocaixa.md`

New: Cosmocaixa from Sam D

---

content/daytrip/eu/gb/the-national-space-centre.md

**Venue:** The National Space Centre
**Location:** Exploration Drive, SPACE CITY, Leicester LE4 5NS
**Submitted by:** trebor
**Website:** https://www.spacecentre.co.uk/
All things space, from vehicles to clothing.
**Submission ID:** 381
**File:** `content/daytrip/eu/gb/the-national-space-centre.md`

New: The National Space Centre from trebor

---

content/daytrip/eu/gb/abbey-pumping-station.md

**Venue:** Abbey Pumping Station
**Location:** Corporation Road Leicester LE4 5PX
**Submitted by:** trebor
**Website:** https://www.leicestermuseums.org/abbey-pumping-station/
Free to enter Victorian pumping station with some great examples of how the Victorians cleaned up the cites. 
**Submission ID:** 382
**File:** `content/daytrip/eu/gb/abbey-pumping-station.md`

New: Abbey Pumping Station from trebor

---

content/daytrip/eu/de/deutsches-technikmuseum.md

**Venue:** Deutsches Technikmuseum
**Location:** Trebbiner Str. 9, 10963 Berlin, Germany
**Website:** https://technikmuseum.berlin/en/
German museum of technology. Topics of the permanent exhibitions are: sugar, chemicals and pharmacy, network, printing, railways, film, photo, brewery, computers, aviation, telecommunications, paper making, shipping, jewelry manufacture, road transport, techlab, textile technology, machine tools, wind power. Has a DC3 hanging above the roof.
**Submission ID:** 385
**File:** `content/daytrip/eu/de/deutsches-technikmuseum.md`

New: Deutsches Technikmuseum from debb1046

---

content/daytrip/eu/es/fbrica-moritz.md

**Venue:** Fàbrica Moritz
**Location:** 41, Ronda de Sant Antoni, Sant Antoni, Eixample, Barcelona, Barcelonès, Barcelona, Catalonia, 08011, Spain
**Submitted by:** Sam D
**Website:** https://fabricamoritzbarcelona.com/es/
Brewpub for the oldest beer in Barcelona. They take reservations for groups, do beer tastings, good food and host events (such as beer yoga?) in the space. 
**Submission ID:** 374
**File:** `content/daytrip/eu/es/fbrica-moritz.md`

New: Fàbrica Moritz from Sam D

---

content/daytrip/eu/de/stadt-und-technikmuseum-ludwigsfelde.md

**Venue:** Stadt- und Technikmuseum Ludwigsfelde
**Location:** Stadt- und Technikmuseum Ludwigsfelde, 2, Am Bahnhof, Ludwigsfelde, Teltow-Fläming, Brandenburg, 14974, Germany
**Website:** https://www.ludwigsfelde.de/rathaus-und-buergerservice/staedtische-einrichtungen/museum/
Exhibition includes local industrial history since 1936. On display are cars, trucks, engines produced in the area. 
**Submission ID:** 389
**File:** `content/daytrip/eu/de/stadt-und-technikmuseum-ludwigsfelde.md`

New: Stadt- und Technikmuseum Ludwigsfelde from debb1046

---

content/daytrip/eu/gb/beamish-museum.md

**Venue:** Beamish Museum
**Location:** Beamish Museum Beamish County Durham DH9 0RG. United Kingdom
**Website:** https://www.beamish.org.uk/
An open-air museum bringing the history of North East England to life from different periods of history.
**Submission ID:** 393
**File:** `content/daytrip/eu/gb/beamish-museum.md`

New: Beamish Museum from AndiBing

---

content/daytrip/na/us/lyndon-b-johnson-space-center.md

**Venue:** Lyndon B. Johnson Space Center
**Location:** Lyndon B. Johnson Space Center, 2101, NASA Parkway, Houston, Harris County, Texas, 77058, United States
**Submitted by:** Allen Redding
**Website:** https://www.nasa.gov/johnson/
The Lyndon B. Johnson Space Center stands out as a uniquely compelling destination for those interested in space exploration, primarily because it functions as both an active NASA facility and a historical archive. Unlike conventional space museums, JSC offers direct access to working mission control centers, astronaut training facilities, and flight hardware, all within real ongoing space operations. The historic Mission Control Center, meticulously preserved from the Apollo era, provides tangible insight into the engineering and decision-making behind the …

New: Lyndon B. Johnson Space Center from Allen Redding

---

content/daytrip/eu/gb/shuttleworth-collection.md

**Venue:** Shuttleworth Collection
**Location:** Shuttleworth Alder Drive Biggleswade Bedfordshire  SG18 9EA SatNav USE SG18 9DT
**Submitted by:** Trebor
**Website:** https://www.shuttleworth.org/
Historic aircraft and vehicles. Also a nice garden
**Submission ID:** 404
**File:** `content/daytrip/eu/gb/shuttleworth-collection.md`

New: Shuttleworth Collection from Trebor

---

content/daytrip/na/us/kitt-peak-national-observatory-visitors-center.md

**Venue:** Kitt Peak National Observatory Visitor's Center
**Location:** Kitt Peak National Observatory Visitor's Center, Tucson, AZ 85634, USA
**Website:** https://kpno.noirlab.edu/
Visit the mountain top hosting a dozen optical telescopes and two radio telescopes.
**Submission ID:** 397
**File:** `content/daytrip/na/us/kitt-peak-national-observatory-visitors-center.md`

New: Kitt Peak National Observatory Visitor's Center from AndiBing

---

content/daytrip/eu/gb/south-pole.md

**Venue:** South Pole
**Location:** South Pole, Antarctica
**Website:** https://en.wikipedia.org/wiki/South_Pole
Snowy. 
Head North in every direction.
**Submission ID:** 398
**File:** `content/daytrip/eu/gb/south-pole.md`

New: South Pole from AndiBing

---

content/daytrip/eu/gb/amundsenscott-south-pole-station.md

**Venue:** Amundsen–Scott South Pole Station
**Location:** Amundsen–Scott South Pole Station, Antartica
**Website:** https://www.nsf.gov/geo/opp/ail/amundson-scott-south-pole-station
US Research base for scientific research. Nearby neutrino detector.
**Submission ID:** 399
**File:** `content/daytrip/eu/gb/amundsenscott-south-pole-station.md`

New: Amundsen–Scott South Pole Station from AndiBing

---

content/daytrip/eu/gb/national-motor-museum.md

**Venue:** National Motor Museum
**Location:** Beaulieu, New Forest, Hampshire, United Kingdom SO42 7ZN
**Website:** https://www.beaulieu.co.uk
A huge collection of cars and motoring memorabilia. Everything from pre-1900 cars to world land speed records.
There is also a stately home, abbey ruins, and a monorail, if the cars aren't enough.
**Submission ID:** 410
**File:** `content/daytrip/eu/gb/national-motor-museum.md`

New: National Motor Museum from Hugo

---

content/daytrip/eu/gb/scotlands-secret-bunker.md

**Venue:** Scotland's Secret Bunker
**Location:** Scotland's Secret Bunker, B940, Kingsmuir, Crail, Fife, Scotland, KY16 8QH, United Kingdom
**Submitted by:** WOPR
**Website:** https://secretbunker.co.uk/
A restored cold war bunker with many historical exhibits to explore.
**Submission ID:** 424
**File:** `content/daytrip/eu/gb/scotlands-secret-bunker.md`

New: Scotland's Secret Bunker from WOPR

---

content/daytrip/af/za/franschhoek-motor-museum.md

**Venue:** Franschhoek Motor Museum
**Location:** Franschhoek Motor Museum, Huguenot Road, Franschhoek, Western Cape, 7690, South Africa
**Submitted by:** ChrisC
**Website:** https://www.fmm.co.za
Explore over 220 vehicles from 1898 to 1974 at Franschhoek Motor Museum, a must-see venue for tourists and motor enthusiasts.
**Submission ID:** 442
**File:** `content/daytrip/af/za/franschhoek-motor-museum.md`

New: Franschhoek Motor Museum from ChrisC

---

content/daytrip/eu/gb/the-higgins-bedford.md

**Venue:** The Higgins Bedford
**Location:** Castle Lane Bedford MK40 3XD
**Submitted by:** Trebor
**Website:** https://www.thehigginsbedford.org.uk/Home.aspx
Watercolour, print and decorative art collections 
**Submission ID:** 448
**File:** `content/daytrip/eu/gb/the-higgins-bedford.md`

New: The Higgins Bedford from Trebor

---

content/daytrip/eu/de/internationales-maritimes-museum-hamburg.md

**Venue:** Internationales Maritimes Museum Hamburg
**Location:** Internationales Maritimes Museum Hamburg, 1, Koreastraße, Quartier Brooktorkai/Ericus, HafenCity, Hamburg-Mitte, Hamburg, 20457, Germany
**Submitted by:** The_Major
**Website:** https://www.imm-hamburg.de/en/
A very large museum catering to everyone interested in ships and the marine environment. 9 Floors to explore. Descriptions/Explanations could be more detailed, they close even before official closing time.
**Submission ID:** 451
**File:** `content/daytrip/eu/de/internationales-maritimes-museum-hamburg.md`

New: Internationales Maritimes Museum Hamburg from The_Major

---

content/daytrip/eu/de/geschichtserlebnisraum-bauspielplatz-roter-hahn.md

**Venue:** Geschichtserlebnisraum - Bauspielplatz Roter Hahn
**Location:** Roter Hahn, 58, Pommernring, Lübeck, Schleswig-Holstein, 23569, Germany
**Submitted by:** jfml
**Website:** https://www.geschichtserlebnisraum.de/home.html
Area where the community is rebuilding houses from history (including a cloiser?!) as well as playground / youth project, some animals, historical reenactments, musik, camfires etc. Good for history buffs.
https://de.wikipedia.org/wiki/Geschichtserlebnisraum_L%C3%BCbeck
**Submission ID:** 452
**File:** `content/daytrip/eu/de/geschichtserlebnisraum-bauspielplatz-roter-hahn.md`

New: Geschichtserlebnisraum - Bauspielplatz Roter Hahn from jfml

---

content/daytrip/eu/gb/trinity-house.md

**Venue:** Trinity House
**Location:** Trinity House, 99, Kirkgate, The Shore, Leith Harbour & Newhaven, City of Edinburgh, Scotland, EH6 6BG, United Kingdom
**Submitted by:** jfml
**Website:** https://www.historicenvironment.scot/visit-a-place/places/trinity-house/
Museum (only guided tours? I've been there during an open day) about the maritime history of Leith (the harbour area it is located in).
**Submission ID:** 454
**File:** `content/daytrip/eu/gb/trinity-house.md`

New: Trinity House from jfml

---

content/daytrip/na/us/international-printing-museum.md

**Venue:** International Printing Museum
**Location:** International Printing Museum, 315 W Torrance Blvd, Carson, CA, 90745, United States
**Submitted by:** Jeff Steidl
**Website:** https://www.printmuseum.org/
Museum dedicated to printing history with examples of printing presses, linotype machines and more. Great events scheduled through the year. Great for all ages!
**Submission ID:** 472
**File:** `content/daytrip/na/us/international-printing-museum.md`

New: International Printing Museum from Jeff Steidl

---

content/daytrip/eu/gr/hellenic-it-museum.md

**Venue:** Hellenic IT Museum
**Location:** Petrou Spiropoulou 2 & Thessalonikis, Moschato, 18346
**Submitted by:** George K.
**Website:** https://elmp.gr/en/home_en/
It is a museum for computers, software, and other IT items, donated by individuals, public and private organizations, and educational institutions. It features a very nice collection of exhibits, run by some very friendly people.
**Submission ID:** 475
**File:** `content/daytrip/eu/gr/hellenic-it-museum.md`

New: Hellenic IT Museum from George K.

---

content/daytrip/na/us/independence-mine.md
content/daytrip/na/us/integratron.md
content/daytrip/na/us/iron-hill-museum.md
content/daytrip/na/us/j-millard-tawes-museum.md
content/daytrip/na/us/jacksonville-zoo.md
content/daytrip/na/us/japanese-friendship-garden.md
content/daytrip/na/us/joseph-priestley-house.md
content/daytrip/na/us/jupiter-inlet-lighthouse-museum.md
content/daytrip/na/us/kazoo-factory.md
content/daytrip/na/us/kidspace-childrens-museum.md
content/daytrip/na/us/kimbell-art-museum.md
content/daytrip/na/us/kinzua-bridge-state-park.md

US I-K: Fix GPS and address, add URLs

---

content/daytrip/eu/se/arboretum-norr.md

**Venue:** Arboretum Norr
**Location:** Baggböle Herrgård, Baggböle, Umeå kommun, Västerbottens län, 901 37, Sverige
**Submitted by:** Tomas 
**Website:** https://www.arboretum-norr.se/en/
In 1975, the seed for Arboretum Norr began to grow. It was the Danish dendrologist Carl-Gustaf Thøgersen’s idea to establish the world’s northernmost arboretum in Baggböle. Carl-Gustaf, who came to Umeå University in 1974 to study, had previously worked in various arboreta and felt that northern Sweden lacked a place dedicated to botanical and dendrological science. He emphasized the importance of research material for both education and studies, but also for landscape architects, garden technicians, foresters and a wide range of educational activities in society. The location would also provide Umeå …

New: Arboretum Norr from Tomas 

---

content/daytrip/na/us/western-railway-museum.md

**Venue:** Western Railway Museum
**Location:** Western Railway Museum, CA 12, Rio Vista Junction, Solano County, California, United States
**Submitted by:** MysterC
**Website:** https://www.wrm.org
A large collection of operating electric railway equipment from the late 19th through late 20th centuries.
Offers both long and short rides most weekends.
**Submission ID:** 482
**File:** `content/daytrip/na/us/western-railway-museum.md`

New: Western Railway Museum from MysterC

---

content/daytrip/eu/nl/artis-micropia.md

**Venue:** Artis Micropia
**Location:** Plantage Kerklaan 38 — 40, Amsterdam
**Submitted by:** Edwin Martin
**Website:** https://www.artis.nl/nl/artis-micropia
ARTIS-Micropia is the world's first museum about microbes. In this interactive science museum you will see something you can hardly see anywhere else: microbes.
**Submission ID:** 480
**File:** `content/daytrip/eu/nl/artis-micropia.md`

New: Artis Micropia from Edwin Martin

---

content/daytrip/eu/se/mannaminne.md

**Venue:** Mannaminne
**Location:** Nordingrå, Ångermanland, Sweden
**Submitted by:** Anders Norén 
**Website:** https://www.mannaminne.se/
An exhibition dedicated to human civilisation. A myriad of buildings and things from different epochs and different parts of the world. 
**Submission ID:** 487
**File:** `content/daytrip/eu/se/mannaminne.md`

New: Mannaminne from Anders Norén 

---

content/daytrip/eu/tr/rahmi-m-ko-museum.md

**Venue:** Rahmi M. Koç Museum
**Location:** Piri Paşa, Rahmi M. Koç Caddesi No: 3, 34445 Beyoğlu/İstanbul, Türkiye
**Submitted by:** Sarah Dal
**Website:** https://www.rmk-museum.org.tr/en
Istanbul museum of Transport and Industry. Brilliant and extensive collection of transport and industry
**Submission ID:** 489
**File:** `content/daytrip/eu/tr/rahmi-m-ko-museum.md`

New: Rahmi M. Koç Museum from Sarah Dal

---

content/daytrip/na/us/shavers-creek-environmental-center.md

**Venue:** Shavers Creek Environmental Center
**Location:** 3400 Discovery Road, Petersburg, Pennsylvania, 16669, United States
**Submitted by:** JamesEndresHowell
**Website:** https://www.shaverscreek.org/about-us/visitor-information/
Nature center with hiking trails, a rescue aviary, kids activities, and much more.
**Submission ID:** 503
**File:** `content/daytrip/na/us/shavers-creek-environmental-center.md`

New: Shavers Creek Environmental Center from JamesEndresHowell

---

content/daytrip/as/cn/china-maritime-museum.md

**Venue:** China Maritime Museum
**Location:** 197 Shengang Avenue, Pudong New Area, Shanghai, China
**Submitted by:** Fras Smith
**Website:** https://www.shmmc.com.cn/EnglishV2/Museum
One of the largest most thorough maritime museums. Look carefully and you might spot some UK sourced positioning tech that they possibly shouldn't have.
**Submission ID:** 505
**File:** `content/daytrip/as/cn/china-maritime-museum.md`

New: China Maritime Museum from Fras Smith

---

themes/ndt2/assets/css/blog.css
themes/ndt2/layouts/blog/baseof.html
themes/ndt2/layouts/blog/single.html
themes/ndt2/layouts/partials/blogfooter.html
themes/ndt2/layouts/partials/bloghead.html
themes/ndt2/layouts/partials/blogheader.html

An attempt to make the blog look visually distinct from the rest of the pages.

Make blog style more distinct

---

content/daytrip/eu/nl/de-museumfabriek.md

**Venue:** De Museumfabriek
**Location:** De Museumfabriek, Het Rozendaal 11, 7523 XG Enschede
**Submitted by:** De Museumfabriek
**Website:** https://www.demuseumfabriek.nl/
De Museumfabriek in Enschede is a vibrant and interactive family museum, uniquely blending nature, culture, science, and technology. It's housed in a captivating space that combines a beautifully renovated old textile factory—a nod to Enschede's rich industrial past—with a sleek, modern new building. This isn't your typical quiet museum; it's designed for hands-on exploration and discovery.
Rather than simply observing, visitors of all ages are encouraged to participate, experiment, and create. The museum delves into "the coherence of things," showcasing how diverse fields intertwine. You'll encounter fascinating …

New: De Museumfabriek from De Museumfabriek

---

content/daytrip/eu/nl/museum-buurtspoorweg.md

**Venue:** Museum Buurtspoorweg
**Location:** Museum Buurtspoorweg
**Submitted by:** Museum Buurtspoorweg
**Website:** https://www.museumbuurtspoorweg.nl/
Step into Museum Buurtspoorweg and embark on a journey through fascinating railway equipment. Explore the locomotive shed and train workshop, meet Station Master Laponder and track worker Gait, and as the icing on the cake, enjoy an unforgettable steam train ride. There's something for everyone to see and do! Welcome to Museum Buurtspoorweg!
Museum Buurtspoorweg runs almost entirely on volunteers who work with passion and dedication to maintain a beautiful local railway museum. 
**Submission ID:** 512
**File:** `content/daytrip/eu/nl/museum-buurtspoorweg.md`
Please review this venue submission and edit the content as needed before …

New: Museum Buurtspoorweg from Museum Buurtspoorweg

---

content/daytrip/eu/de/40.md

**Venue:** 40
**Location:** 40, Detmoldstraße, Lerchenau, Hasenbergl-Lerchenau Ost, Feldmoching-Hasenbergl, Munich, Bavaria, 80935, Germany
**Submitted by:** Iαη 🍺
**Website:** https://giesinger-shop.de/Brewery-Tour-Giesinger-Braeu
A tour of the most modern brewery in Bavaria, including bottling plant, beer hall and the "oh my God!" of the Giesing deep well.
**Submission ID:** 522
**File:** `content/daytrip/eu/de/40.md`

New: 40 from Iαη 🍺

---

content/daytrip/eu/gb/framlingham-castle.md

**Venue:** Framlingham Castle
**Location:** Framlingham Castle, Wall Walk, Framlingham, East Suffolk, Suffolk, England, IP13 9BS, United Kingdom
**Submitted by:** Steve Engledow
**Website:** https://www.english-heritage.org.uk/visit/places/framlingham-castle/
The best, and nerdiest part of this castle is the guided battlements audio tour! This castle is a bit out of the way but it's 100% worth the effort to get there. They have occasional "tournaments" with people in armour battling in the centre of the castle keep.
**Submission ID:** 523
**File:** `content/daytrip/eu/gb/framlingham-castle.md`

New: Framlingham Castle from Steve Engledow

---

content/archive-index.md
themes/ndt2/layouts/_default/archive-index.baseof.html
themes/ndt2/layouts/_default/archive-index.html

This just makes a page that's not linked from anywhere, but links to all our pages. 
We can feed this to archive.org and have it spider the site nicely.
I also found it interesting scrolling to the bottom and seeing all the errors in the sites imported from the old site :D 
look for zz :) 
I used the blog theme so it's at least slightly human consumable.

Add complete site archive page for archive.org to index

---

content/daytrip/eu/gb/carlisle-castle.md

**Venue:** Carlisle Castle
**Location:** Carlisle Castle, Dacre Road, Caldewgate, Carlisle, Cumberland, England, CA3 8UR, United Kingdom
**Website:** https://www.english-heritage.org.uk/visit/places/carlisle-castle/
Sitting at the western end of Scottish-English border, Carlisle Castle is one of the most besieged castles in England.
**Submission ID:** 544
**File:** `content/daytrip/eu/gb/carlisle-castle.md`

New: Carlisle Castle from hiraethmarkb

---

content/daytrip/eu/gb/caerlaverock-castle.md

**Venue:** Caerlaverock Castle
**Location:** Caerlaverock Castle, B725, Shearington, Dumfries and Galloway, Scotland, DG1 4RU, United Kingdom
**Website:** https://caerlaverock.com/heritage/castle/
Built in the late 13th century, as  part fortress, part residence, Caerlaverock is unique as the only triangular layout Castle in Britain.
**Submission ID:** 545
**File:** `content/daytrip/eu/gb/caerlaverock-castle.md`

New: Caerlaverock Castle from hiraethmarkb

---

content/daytrip/eu/gb/belvedere-mill.md

**Venue:** Belvedere Mill
**Location:** Belvedere Mill, Chalford, Stroud, Gloucestershire, England, GL6 8PR, United Kingdom
**Website:** https://www.retrocollective.co.uk/the-cave.php
Home of the RMC: The Cave, a hands-on vintage and retro computing/gaming museum. Part of the Retro Collective.
**Submission ID:** 548
**File:** `content/daytrip/eu/gb/belvedere-mill.md`

New: Belvedere Mill from hiraethmarkb

---

content/daytrip/eu/de/computermuseum.md

**Venue:** Computermuseum
**Location:** Computermuseum, 8, Eichenbergskamp, Neumühlen-Dietrichsdorf, Kiel, Schleswig-Holstein, 24149, Deutschland
**Submitted by:** Jan
**Website:** https://www.fh-kiel.de/computermuseum/
History of computerscience located in an old World War II Bunker.
**Submission ID:** 553
**File:** `content/daytrip/eu/de/computermuseum.md`

New: Computermuseum from Jan

---

content/daytrip/eu/dk/regan-vest.md

https://openstreetmap.org/way/1072528730

New eu/dk: Koldkrigsmuseet REGAN Vest

---

content/daytrip/as/in/visvesvaraya-industrial-and-technological-museum.md

**Venue:** Visvesvaraya Industrial and Technological Museum
**Location:** Visvesvaraya Industrial and Technological Museum, Kasturba Road, Sampangirama Nagar, Shivajinagar, Bengaluru, Bangalore North, Bengaluru Urban, Karnataka, 560001, India
**Submitted by:** Pfft
**Website:** https://www.vismuseum.gov.in/
Visvesvaraya Industrial and Technological Museum, Bangalore (VITM), a constituent unit of National Council of Science Museums (NCSM), Ministry of Culture, Government of India, was established in memory of Bharat Ratna Sir M. Visvesvaraya. A modest building with a built up area of 4000 sq. mtrs., was constructed in the serene surrounding of the Cubbon Park, housing various industrial products and engines
- Google Maps link: [Search on Google …

New: Visvesvaraya Industrial and Technological Museum from Pfft

---

content/daytrip/as/in/sandesha-museum-of-communication.md

**Venue:** Sandesha Museum of Communication
**Location:** Sandesha Museum of Communication, Museum Road, Shanthala Nagar, Richmond Town, Bengaluru, Bangalore North, Bengaluru Urban, Karnataka, 560001, India
**Submitted by:** Pfft
**Website:** https://en.wikipedia.org/wiki/Sandesh_Museum_of_Communication
Sandesh Museum of Communication is a museum in Bangalore and is dedicated to the postal history of India and different modes of communication. The museum opened its doors in 2019 and is located inside a 140 year-old post office, preserved and refurbished as a museum.
- Google Maps link: [Search on Google Maps](https://www.google.com/maps/search/?api=1&query=Sandesha%20Museum%20of%20Communication%2C%20Museum%20Road%2C%20Shanthala%20Nagar%2C%20Richmond%20Town%2C%20Bengaluru%2C%20Bangalore%20N …

New: Sandesha Museum of Communication from Pfft

---

content/daytrip/eu/dk/regan-vest.md

Update description about the 3 different exhibitions and use links that point to English version of the pages.
This should make the information more accessible.

eu/dk: update description for regan vest

---

README.md

Just a couple of updates to the project README.

Minor tweaks to the readme.

---

content/daytrip/eu/gb/aldershot-military-museum.md

**Venue:** Aldershot Military Museum
**Location:** Aldershot Military Museum,  North Camp, Aldershot, Hampshire, England, GU11 2LG, United Kingdom
**Website:** https://www.hampshireculture.org.uk/aldershot-military-museum
The museum tells the story of the Aldershot military town.
- Google Maps link: [Search on Google Maps](https://www.google.com/maps/search/?api=1&query=Aldershot%20Military%20Museum%2C%20%20North%20Camp%2C%20Aldershot%2C%20Hampshire%2C%20England%2C%20GU11%202LG%2C%20United%20Kingdom)
- OpenStreetMap link: [Search on OpenStreetMap](https://www.openstreetmap.org/search?query=Aldershot%20Military%20Museum%2C%20%20North%20Camp%2C%20Aldershot%2C%20Hampshire%2C%20England%2C%20GU11%202LG%2C%20United%20Kingdom)
**Submission ID:** 584
**File:** …

New: Aldershot Military Museum from AndiBing

---

content/daytrip/eu/gb/milestones-museum.md

**Venue:** Milestones Museum
**Location:** Milestones Museum,  Basingstoke, Hampshire, England, RG22 6PL, United Kingdom
**Website:** https://www.milestonesmuseum.org.uk/
Milestones tells the story of how people used to live. The layout of the museum is a collection of streets, shops, factories and houses to explore.
- Google Maps link: [Search on Google Maps](https://www.google.com/maps/search/?api=1&query=Milestones%20Museum%2C%20%20Basingstoke%2C%20Hampshire%2C%20England%2C%20RG22%206PL%2C%20United%20Kingdom)
- OpenStreetMap link: [Search on OpenStreetMap](https://www.openstreetmap.org/search?query=Milestones%20Museum%2C%20%20Basingstoke%2C%20Hampshire%2C%20England%2C%20RG22%206PL%2C%20United%20Kingdom)
**Submission ID:** 585
**File:** …

New: Milestones Museum from AndiBing

---

content/daytrip/na/us/indiana-military-museum.md

**Venue:** Indiana Military Museum
**Location:** Indiana Military Museum, South 6th Street Road, Vincennes, Knox County, Indiana, 47591, United States
**Submitted by:** NorthernWolf
**Website:** https://www.indianamilitarymuseum.org/
Large collection of military artifacts from major conflicts.
- Google Maps link: [Search on Google Maps](https://www.google.com/maps/search/?api=1&query=Indiana%20Military%20Museum%2C%20South%206th%20Street%20Road%2C%20Vincennes%2C%20Knox%20County%2C%20Indiana%2C%2047591%2C%20United%20States)
- OpenStreetMap link: [Search on OpenStreetMap](https://www.openstreetmap.org/search?query=Indiana%20Military%20Museum%2C%20South%206th%20Street%20Road%2C%20Vincennes%2C%20Knox%20County%2C%20Indiana%2C%2047591%2C%20United%20States)
**Submission ID:** 582
**File:** …

New: Indiana Military Museum from NorthernWolf

---

content/daytrip/eu/de/militr-historisches-museum-berlin-gatow.md

**Venue:** Militär-Historisches Museum Berlin-Gatow
**Location:** Militär-Historisches Museum Berlin-Gatow, Am Flugplatz Gatow, Berlin, 14089, Germany
**Website:** https://www.mhm-gatow.de/de
Former airfield which is now a museum. Has many military airplanes on display, including some used by the Eastern Bloc.
- Google Maps link: [Search on Google Maps](https://www.google.com/maps/search/?api=1&query=Milit%C3%A4r-Historisches%20Museum%20Berlin-Gatow%2C%20Am%20Flugplatz%20Gatow%2C%20Berlin%2C%2014089%2C%20Germany)
- OpenStreetMap link: [Search on OpenStreetMap](https://www.openstreetmap.org/search?query=Milit%C3%A4r-Historisches%20Museum%20Berlin-Gatow%2C%20Am%20Flugplatz%20Gatow%2C%20Berlin%2C%2014089%2C%20Germany)
**Submission ID:** 594
**File:** …

New: Militär-Historisches Museum Berlin-Gatow from debb1046

---

content/daytrip/eu/gb/tate-modern.md

**Venue:** Tate Modern
**Location:** Tate Modern, Bankside, London SE1 9TG
**Website:** https://www.tate.org.uk/visit/tate-modern
An imposing red-brick building on the side of the River Thames. A great way to spend a bit of time trying (and maybe failing) to "get" "art".
- Google Maps link: [Search on Google Maps](https://www.google.com/maps/search/?api=1&query=Tate%20Modern%2C%20Bankside%2C%20London%20SE1%209TG)
- OpenStreetMap link: [Search on OpenStreetMap](https://www.openstreetmap.org/search?query=Tate%20Modern%2C%20Bankside%2C%20London%20SE1%209TG)
**Submission ID:** 597
**File:** `content/daytrip/eu/gb/tate-modern.md`

New: Tate Modern from popey

---

content/daytrip/eu/cz/czech-museum-of-music.md

**Venue:** Czech Museum of Music
**Location:** Karmelitská 2, Praha, Czechia
**Website:** https://www.nm.cz/en/visit-us/buildings/czech-museum-of-music
An amazing collection of musical instruments, including pianos that don't use a 12-semitone scale, musical automata, and some weird two-belled brass instruments called Šediphones.
- Google Maps link: [Search on Google Maps](https://www.google.com/maps/search/?api=1&query=Karmelitsk%C3%A1%202%2C%20Praha%2C%20Czechia)
- OpenStreetMap link: [Search on OpenStreetMap](https://www.openstreetmap.org/search?query=Karmelitsk%C3%A1%202%2C%20Praha%2C%20Czechia)
**Submission ID:** 613
**File:** `content/daytrip/eu/cz/czech-museum-of-music.md`

New: Czech Museum of Music from Hugo

---

content/daytrip/na/us/bay-model-visitor-center.md

**Venue:** Bay Model Visitor Center
**Location:** Bay Model Visitor Center, 2100, Bridgeway, Sausalito, Marin County, California, 94965, United States
**Submitted by:** sharp-meal
**Website:** https://www.spn.usace.army.mil/Missions/Recreation/Bay-Model-Visitor-Center/
A scale hydraulic model of the San Francisco Bay and Sacramento-San Joaquin River Delta System. Developed by Corps of Engineers in the 1950s when physical models were the only realistic way to model complex waterways.
- Google Maps link: [Search on Google Maps](https://www.google.com/maps/search/?api=1&query=Bay%20Model%20Visitor%20Center%2C%202100%2C%20Bridgeway%2C%20Sausalito%2C%20Marin%20County%2C%20California%2C%2094965%2C%20United%20States)
- OpenStreetMap link: [Search on …

New: Bay Model Visitor Center from sharp-meal

---

themes/ndt2/layouts/partials/header.html
themes/ndt2/layouts/partials/posts.html

Two more relative -> absolute url changes.

Fix sidebar links

---

edit.sh

Small usability update to tooling

Automatically create directories when renaming files

---

content/daytrip/na/mx/el-cosmovitral.md

clean up el cosmovitral cruft

---

content/daytrip/af/ug/fort-patiko.md
content/daytrip/af/ug/kabakas-lake.md
content/daytrip/af/ug/ziwa-rhino-sanctuary.md
content/daytrip/af/za/kirstenbosch-gardens.md
content/daytrip/as/pk/kallar-kahar.md
content/daytrip/eu/gb/birmingham-city-centre-gardens.md
content/daytrip/eu/gb/birmingham-indoor-market.md
content/daytrip/eu/gb/black-sabbath-bridge.md
content/daytrip/eu/gb/cathedral-church-of-saint-philip.md
content/daytrip/eu/gb/dungeness-b-power-station.md
content/daytrip/eu/gb/fossil-museum-at-the-square-and-compass.md
content/daytrip/eu/gb/industry-and-genius-statue.md
content/daytrip/eu/gb/m62-summit.md
content/daytrip/eu/gb/the-old-thirteenth-cheshire-astley-volunteer-rifleman-corps-inn.md

These entries were still missing URLs

Cleanup 1/3: URLs

---

content/daytrip/eu/gb/aerospace-bristol.md

Update description to new one provided by Zoe.

Merge in changes from Zoe

---

content/daytrip/na/ca/the-hangar-flight-museum.md
content/daytrip/na/ca/the-military-museum.md

These two places had exactly the same GPS location, which isn't either of the actual locations for them.

Fix locations for two places in Calgary
